### ISSUE TITLE
Add asset to media cards

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1000]
- [x] Mobile library
- [x] Desktop library
- [x] Component specs
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-11582)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8015)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-760)

**Comment by yceballost** [comment]
![asas](https://media.giphy.com/media/ENiumlTLGnpD8snXim/giphy-downsized-large.gif)
