### ISSUE TITLE
Missing icon weight on the Brand Factory's repository

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#1001]
### Context
If you think there is a icon missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new icon from Design to Development.

- [X] **Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute/how-to-contribute)?**  
- [X] **Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?**  

---

### Is your icon request related to a need? Please describe.
Accessing the icon repository on Brand Factory, downloading it and adding all of them to a Figma file, we noticed that some weights on some specific icons aren’t available.

### Describe or attach a screenshot of the solution you'd like and needs
We separated all the icons into a PDF file, indicating the weights of which icons we did not find in the repository.

### Describe icon alternatives you've considered
In this specific case, we would like to understand if we can find these missing weights on other repository or if you would make them available to us.

### Additional context?
Nothing to add.

### Attach your svg icon with 3 weights (light / regular / filled)
[Doc Icons Telefonica Ged - Desktop.pdf](https://github.com/Telefonica/mistica-design/files/10448406/Doc.Icons.Telefonica.Ged.-.Desktop.pdf)
 
- [X] Light
- [X] Regular
- [X] Filled

**Comment by yceballost** [comment]
Thanks for this exercise! We know about this problem, from Mística side we just download icons from the Brand Factory and include in the system, so.. we don't really know where is the place to find the missing font. We would like to have the editable files to make icons custom stroke through Mística but from Brand Factory team can't provide us this material. (don't know why, missing files or whatever)

You talk with AURORA ALONSO MORANTE to try to get these missing icons

On the other hand, in Mística we can include the missing icons if some team makes this work, and then we have a workflow with Brand Factory to include these new icons to Brand Factory, with this wow we can feed Brand Factory. (When BF includes new icons notice us and we include in Mística)
