### ISSUE TITLE
Mística Tokens | Border radius definition

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1048]
Define a set of border radius tokens to use across components
- button-radius
- radius-preset-1 = 0 (?)
- radius-preset-2 = 16 (?)

---

- [x] Definition specs
- [x] #1268
- [x] #1139
- [x]  Definition approved by Vivo Team
	- Media, Data, Snap card  → 16
	- Display media card → 16
	- Button → stadium
	- Input field → 12
	- Snackbar → 16
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-11940)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8300)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-817)

**Comment by AnaMontes11** [comment]
Dejo por aquí este esquema con la definición que a priori, es más flexible y puede escalar bien:

Figma: [Border radius](https://www.figma.com/file/PApssATUkePZnIOB4GmAeI/%F0%9F%94%B9-%E2%80%8E%E2%80%8ETokens-definition?node-id=1505%3A178)

**Comment by AnaMontes11** [comment]
Como siguiente paso, la idea es crear una tabla/listado con los borderRadius que existen actualmente especificando cuales son susceptibles de cambiar por marca con el objetivo de tener una foto general que ayude a bajarlo a semantic tokens

**Comment by yceballost** [comment]
> * [x]  Definition specs
> * [ ]   Definition approved by Vivo Team
> * [ ]  Android ticket
> * [ ]  iOS ticket
> * [ ]  Web ticket

lo subo arriba!

**Comment by yceballost** [comment]
Reopen this issue to include all border radius in specs
