### ISSUE TITLE
Android modal

### ISSUE THREAD

**Issue by DiegodeMiguel** [Telefonica/mistica-design#1056]
### Describe the bug

I´m trying to create an android modal into figma, but the modal component brokes when I insert the copy of the action that I want. Neither I can put 3 actions, it´s possible 2 as maximum. Do I have to create a bastard component for it?

I copy here a screen shot about the screen I want to create in Android:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/106736588/217193597-77dafc36-a53e-467b-960a-097e4254da9d.png">
There you can see how the first action text button brokes into the component.

Thanks!

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

Button copy problem

### Expected behavior

I want if it´s possible to put more than 2 actions in Android modal (I need 3 actions into the modal). Also I need for one of it a large copy text for one of the 3 actions.

**Comment by PatriRoman** [comment]
¡Hola!

Juto me encuentro ante la misma necesidad. Ahora mismo no existe en el componente de alert de android la posbilidad de tener 3 acciones y necesitábamos recrear en diseño esta pantalla:
<img width="149" alt="image" src="https://github.com/Telefonica/mistica-design/assets/108683238/c22e7d53-3bf3-43f4-971d-499045771d1c">

¿Hago el diseño "bastardo" o es una opción que se plantea añadir al componente?

**Comment by aweell** [comment]
Buenas! De momento no hay problema en que se haga bastarda porque es un componente full nativo. Aún así, el plan es soportar las 3 acciones de Android en la modal, estará disponible a partir de la próxima release.

**Comment by yceballost** [comment]
igual es buen momento de hacer update a material 3?
