### ISSUE TITLE
Inactive tag has different background in dark

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1062]
### Describe the bug

tag inactive has different background

### Steps to reproduce

![image](https://user-images.githubusercontent.com/6722153/217878325-e079e36d-0f3b-482d-9699-96f9422f3043.png)

### Expected behavior

Keep the same background

**Comment by aweell** [comment]
He estado haciendo algunas pruebas

El único impacto que tendría modificar `neutralLow` en dark para que utilice el mismo hexadecimal que el resto de background de las tags es que se utiliza para el estado `readOnly` del input.

Veo varios caminos aquí:

1. Modificar el token actual y reducir la diferencia que existe entre un input `default` y un `readonly`
2. Crear un token e.j. `inactiveLow` que utilice la tag inactive como `background-color`, en light será un `grey1` y en dark ese `white` al 0.05.
3. Crear un token específico para el `readOnly` manteniendo su color actual o incrementándolo y dejando `neutralLow` siempre con un `white` al 0.05

**Comment by yceballost** [comment]
Esto parece estar solucionado 🤔 @aweell 
https://mistica-web.vercel.app/?path=/story/components-tag--default

Si ves conveniente, cierra el ticket!
