### ISSUE TITLE
Improve slideshow bullets contrast

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1067]
## Description

La implementación actual puede se potencialmente inaccesible en los siguientes casos:

* Imágenes con areas claras en la zona donde se posicionan los bullets
* Nueva implementación del hero con slideshow

## Tasks

- [ ] Update specs
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [ ] Web ticket

**Comment by yceballost** [comment]
Se está teniendo en cuenta en la issue de #682 y el resto de brands que se están tocando el contraste (aprovecharemos para cubrir también telefónica)
