### ISSUE TITLE
Rethink specs structure

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1073]
## Description
We have problems to make visible new features or what part of the component is developed or not in the current specs for developers teams.

We need to find the way to show what parts of the specs are developed.

Two fast ideas to solve this:
1. Manage versions of the specs using different pages in the specs file
2. Manage part of the component developed and non-developed with some design resource (color, tags, etc) in the actual specs.

**Comment by AnaMontes11** [comment]
Would it make sense to put the discarded studies on another page? adding a rationale?
