### ISSUE TITLE
Color in some components in Movistar dark mode

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1081]
### Describe the bug

![image](https://user-images.githubusercontent.com/6722153/221796229-dbf2c647-ff62-4274-a45e-9f74bd832133.png)
![image](https://user-images.githubusercontent.com/6722153/221863992-6a79b80e-bbbe-4b9d-a9f3-a1863ef26e8e.png)
![image](https://user-images.githubusercontent.com/6722153/221863811-5a55564d-4ead-48ec-b348-75e2222750ea.png)

Chip background when hover is wrong in dark mode in movistar

### Steps to reproduce

1. Go chip
2. Mouse hover

### Expected behavior

Use blued colors for this hover state

**Comment by aweell** [comment]
Link con los fixes:

* Arreglados todos los grises que no estaban virados a azul en la nueva skin de movistar

https://mistica-5yp58h56q-aweell.vercel.app/?path=/story/welcome--welcome

Hay un detalle con las chips en dark:

Al usar `brandLow` y `backgroundContainer` en mismo recurso de la paleta (darkModeGrey) no se diferencia al hacer `:hover`

**Comment by yceballost** [comment]
> Hay un detalle con las chips en dark:
> 
> Al usar `brandLow` y `backgroundContainer` en mismo recurso de la paleta (darkModeGrey) no se diferencia al hacer `:hover`

Yep, pero esto tb ocurre en light con un brandLow y un hover... eso habrá que resolverlo en la #677 

---

Creéis que los skeletons deberían tener un color menos intenso en dark mode?

**Comment by AnaMontes11** [comment]
Pues hice pruebas del tema skeletons, y si no me equivoco, el siguiente menos intenso quedaba muy sutil...

**Comment by AnaMontes11** [comment]
> Pues hice pruebas del tema skeletons, y si no me equivoco, el siguiente menos intenso quedaba muy sutil...

Arreglados también skeletons y el icon circle.
