### ISSUE TITLE
Icon circle not visible on dark mode

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1102]
### Describe the bug

When Dark mode is on, the circled icon on account cards is not visible because the circle background has the same color as the card background.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/95479574/223102571-c8633fdc-cb77-4b24-b361-76737cbd6024.png">

### What libraries are you seeing the problem on?

Mobile Library, Desktop Library, Movistar Library

### Steps to reproduce

1. Go to account [cards](https://www.figma.com/file/htlH7rATSBGDkNzhrYQPUv/Mis-productos_HUB?node-id=1%3A448)
2. Apply Themer -> Movistar Dark on cards with circled icon

### Expected behavior

I don't know how to solve this :/

**Comment by aweell** [comment]
Related to #1081

**Comment by AnaMontes11** [comment]
Arreglado, lo verás en la próxima Release 8.0.0
