### ISSUE TITLE
backgroundAlternative color in dark mode

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1111]
## Description

Al permitir la posibilidad de que existan camas con `backgroundAlternative` se genera una serie de problemáticas en dark mode con todos aquellos componentes que usan `backgroundContainer`, ya que los dos pasan a usar `darkModeGrey`

[Ejemplo -> ](https://rebrand.ly/u422711)

La solución para este problema es cambiar el valor de `backgroundAlternative` a `darkModeBlack`.

**¿Qué ocurriría con aquellos componentes que utilizan el backgroundAlternative en su container?**

En el caso del callout, su variante inverse utiliza `backgroundContainer`, por lo que funcionaría sobre `backgroundAlternative` si siempre que cuando vaya en un contexto Alternative se pinte como `inverse`.

[Ejemplo -> ](https://rebrand.ly/1ntk1f0)

**¿Qué ocurriría con aquellos componentes que utilizan el backgroundAlternative en alguno de sus estados?**

En la propuesta actual ya se están perdiendo lo estados en darkMode:

[Ejemplo ->](https://rebrand.ly/g9q6dia)

En el caso de todos aquellos elementos que utilizan el backgroundAlternative para su estado :hover:

* Cards
* Listas
* PasswordField (ShowPassword)
* Select (OptionItem)

En estos casos esos estados deberían utilizar otro token de color que no sea el alternative:

Se añade complejidad a https://github.com/Telefonica/mistica-design/issues/677

Ya que estos estados deberían funcionar en los dos contextos, ya sea teniendo dos tokens diferentes o un token con un valor que no se iguale al background sobre el que están los elementos (en el caso del alternative)

**Comment by AnaMontes11** [comment]
Si cambiamos el valor de backgroundAlternative a darkModeBlack solucionamos el problema que comentas pero ese cambio provocaría que las camas no se vean ya que tendríamos en background (darkModeBlack) y las camas (darkModeBlack).

**Comment by AnaMontes11** [comment]
<img width="611" alt="prueba" src="https://user-images.githubusercontent.com/88187691/223672387-94db16db-7fb3-4222-9973-e480168bff53.png">

**Comment by aweell** [comment]
Tiene sentido que se vean las camas en darkMode?
