### ISSUE TITLE
Snackbar bug

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1127]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1126

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** March 14, 2023</sup>
Buenas tardes.

@yceballost 

Estaba jugando con el componente Snackbar y noté una posible modificación.

La versión de Android cambia de tamaño en altura (de 48 a 52) cuando la opción "critical" está activa.

<img width="1792" alt="Captura de Tela 2023-03-14 às 15 14 14" src="https://user-images.githubusercontent.com/127137234/225099675-88bd702e-9ac7-4f13-b73c-af1b87f80441.png">

</div>

**Comment by yceballost** [comment]
@annefranca puedes adjuntar un archivo donde pueda ver el problema? soy incapaz de replicar el bug sacándolo de la librería

**Comment by annefranca** [comment]
@yceballost probé este archivo https://www.figma.com/file/ubUZYvoFfbXAWph7TpwtWV/Snackbar%2FCrouton?node-id=0%3A1&t=jok8HhOeQyaUkfG3-1

**Comment by yceballost** [comment]
![](https://media4.giphy.com/media/3ca1zyaiFAuPLlHDFy/giphy.gif?cid=ecf05e47qhe528kou0a8axv9ho015q9f40w1j2eatogd0ool&rid=giphy.gif&ct=g)

cazado! en la 8.0.0 estará arreglado :) muchas gracias!!
