### ISSUE TITLE
Change highlight color in Blau skin

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1141]
- [ ] Web ticket
- [ ] iOS ticket
- [ ] Android ticket

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1134

<div type='discussions-op-text'>

<sup>Originally posted by **MontseTelefonica** March 16, 2023</sup>
### Goal
Necesitamos definir como solucionar el problema de globalidad de los componentes que usan el color Highligh, ya que en Blau el highligh es azul y pierde el tono rojizo que se utiliza para informar de gastos extras

### Context
Hay algunos módulos en CPS que necesitan generar una excepción de color en la marca Blau y puesto que se está utilizando una "if" para esto, desde CPS nos piden una Mistificación con una nueva variable para dar solución a esto.

### Impact
Esto es necesario de cara a mantener la globalidad de los componentes y evitar "ifs" en CPS

### Discussion Questions
¿Es necesario crear nueva variable llamada "extra_charges" para poder dar a cada marca una variable de color distinta ?
¿Cabe considerarse la opción cambiar el color highlight en todas las marcas a un error?

### Do you have a visual proposal?

https://www.figma.com/file/xNUwhH29z3Fre4foNltgtX/CPS_Specs?node-id=8537-137500</div>

**Comment by MontseTelefonica** [comment]
Figma with "Signal 3" color applied as Blau Highlight
https://www.figma.com/file/xNUwhH29z3Fre4foNltgtX/CPS_Specs?node-id=8736-138646&t=8MK4WnVAyR6itENK-4
