### ISSUE TITLE
Image as asset in callout component

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1157]
### Tasks

- [x] #1220
- [x] Update Brand Factory documentation (Anatomy + Interactive example)
- [ ] iOS Ticket
- [ ] Android Ticket

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1148

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** March 24, 2023</sup>
### Goal

Incluir nas Variants uma propriedade de imagem (icon/image) e possibilidade de desligar o título (esse opção está como possível no Brand Factory).

### Context

Dentro do fluxo de assinaturas, o componente Callout precisa ser aplicado dessa forma para a pessoa usuária. Atualmente o Callout que temos no Mística não suporta imagem e a opção de desligar (Figma).

### Impact

Proposta Work & Co - Novo App.

### Discussion Questions

Esse update poderia ser implementado no Mística? Qual equipe ficaria responsável pelo desenvolvimento.

### Do you have a visual proposal?

https://www.figma.com/file/seiNjy7YmPWEY3BfY4WYpp/Novos-componentes---Sprint-1?node-id=4%3A10046&t=gYOdlKhORV0w5rhF-1</div>

**Comment by yceballost** [comment]
This task should be include the possibility to add images in callouts in Figma, right?

**Comment by aweell** [comment]
The callout uses the asset wrapper so, is technically possible to replace the icon by an image ATM
