### ISSUE TITLE
Chips update size and include badge

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1160]
### Description

**Only mobile**

* Update chip height to 40px
* Update chip padding to 20px (without icon) / 16px (with icon)

### Tasks

- [x] Update specs
- [x] #1269
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Android ticket
- [ ] iOS ticket
- [x] Web ticket

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1114

<div type='discussions-op-text'>

<sup>Originally posted by **pihcardozo** March  8, 2023</sup>
Seguindo a atualização visual do novo APP da Vivo, vamos precisar do componente Chips com mais variantes:

**- Chips com novo tamanho de 40px (large)**
Vamos precisar criar uma variante do Chips no Figma, no tamanho de 40px de altura.

**- Background transparente. Modo on/off**
Vamos precisar de uma variante com fundo transparente na versão default, isso se aplica para a versão small e large (nova) do Chips.
 
**- Variante com Badge do lado direito**
Vamos precisar de uma variante com Badge na área interna direita do Chips, isso se aplica para a versão small e large (nova) do Chips.</div>

**Comment by yceballost** [comment]
branch created to add this evolution @BrunoBiagioniNeto 
https://www.figma.com/file/512a5Ke4EldL0GYffCXGCJ/branch/bVqAhYysigAoyzhLELLUtd/%F0%9F%94%B8-Chips-Specs?node-id=0%3A1&t=z0ix9ewxjnwNsqc7-1
