### ISSUE TITLE
ButtonLink small

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1163]
### Describe the bug

El Button [D] hace una cosa muy rara si eliges ButtonLink y luego Small. Se activa por defecto el loading y sale en verde
<img width="535" alt="MicrosoftTeams-image (278)" src="https://user-images.githubusercontent.com/95479574/228808138-dc1e96d9-db75-44ac-bb9a-13b432f8da05.png">

### What libraries are you seeing the problem on?

Desktop Library

### Steps to reproduce

.Go to Button [D]
.Select buttonLink
.Select small

### Expected behavior

La opción small no debería estar disponible en buttonLink

**Comment by yceballost** [comment]
deberíamos separar los botones y que sean componentes diferentes para evitar mezclar props?

Para ser fiel a Mística Web deberíamos de tratarlos como componentes diferentes

---

sobre la issue, no logro replicar el problema, no será que estás cogiendo un button antiguo y/o no actualizado? puedes pasar link del archivo donde ocurre eso?

**Comment by MontseTelefonica** [comment]
Pues extraño, porque el componente era de Mistica Desktop cuando lo probé (me cercioré) pero ahora veo que se muestra azul :/ anyway, solucionado :)

**Comment by aweell** [comment]
Creo discussion con esto:

> deberíamos separar los botones y que sean componentes diferentes para evitar mezclar props?
> 
> Para ser fiel a Mística Web deberíamos de tratarlos como componentes diferentes


https://github.com/Telefonica/mistica-design/discussions/1201

Estando resuelta cierro esta issue
