### ISSUE TITLE
Add new Vivo Type with Vivinho in Figma

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1171]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1166

<div type='discussions-op-text'>

<sup>Originally posted by **BrunoBiagioniNeto** April  3, 2023</sup>
### Goal

Objetivo é utilizar o ícone Vivinho nos componentes de Cards 

### Context

Criando uma fonte com um ícone vivo como caracter especial nos dá a possibilidade de utilizar o ícone em qualquer lugar.

### Impact

O ícone será utilizado diretamente na fonte.

### Discussion Questions

[ ] - Validar fonte criada
[ ] - Atualizar a fonte atual Vivo Type.

Ícone utilizado = ¦ 

### Do you have a visual proposal?

https://www.figma.com/file/dWdeVR4RYaX7wOj3YAqlrx/Vivo-Type-%2B-Glypho?node-id=0-1
</div>

**Comment by yceballost** [comment]
@BrunoBiagioniNeto hay problemas con el kerning
![image](https://user-images.githubusercontent.com/6722153/230973564-d50b50f3-b332-48b4-ae28-27760b07201f.png)


https://rebrand.ly/sqo21ax

**Comment by BrunoBiagioniNeto** [comment]
Irei ajustar para 1 space entre ícone e texto.

**Comment by BrunoBiagioniNeto** [comment]
Kernel ajustado.

<img width="811" alt="image" src="https://user-images.githubusercontent.com/123083886/231186239-1ee262a9-e6fb-4c98-953f-a674bcd79abf.png">

**Comment by yceballost** [comment]
Ahora está perfeito ✨

**Comment by yceballost** [comment]
añadido a Figma, el siguiente paso sería añadir que la Vivo Type se utilice por defecto en la nueva skin de vivo en desarrollo.

Cierro esta tarea y lo meto como parte de la https://github.com/Telefonica/mistica-design/issues/1173

**Comment by yceballost** [comment]
@BrunoBiagioniNeto hemos detectado que el caracter que usaste para el Vivinho lo lee como `brokenbar` por haber sustituido este caracter por el vivinho. Esto puede provocar problemas de accesibilidad y lo ideal sería actualizar este "name" para que cuando pase el VoiceOver lea el nombre que queramos que se lea en el asistente de voz

- vivo?
- vivologo?
- vivinho?

No sé, es vuestra decisión :) 

![image](https://user-images.githubusercontent.com/6722153/232763194-6a7db17a-5954-4cb5-9d80-92b20b9fb7c7.png)

**Comment by yceballost** [comment]
Añadida a Figma la última versión enviada por Vivo
