### ISSUE TITLE
Change Telefonica typography style to regular

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1200]
## Description
Change type definition from light to regular to be more similar to Telefonica.com

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Android ticket
- [x] iOS ticket
- [x] Web ticket

**Comment by HectorSancho** [comment]
No me queda muy claro cómo manejamos la light en otras marcas en el text preset 3 y 4. ¿Duplicamos el peso regular?¿Eliminamos el light? ¿Cuál aplica al title de las cards? (en ese caso debería ser regular también)
