### ISSUE TITLE
Web Navigation evolution for large navigations

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1209]
- [x] Update specs
- [x] Design documentation
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1397)

Update specs with
- https://github.com/Telefonica/mistica-design/issues/1084
- https://github.com/Telefonica/mistica-design/issues/799

---
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1186

<div type='discussions-op-text'>

<sup>Originally posted by **HectorSancho** April 14, 2023</sup>
### Goal

Evolucionar la navegación web para que contemple y escale a arquitecturas más complejas.

### Context

El actual componente no escala.

### Impact

Producción

### Discussion Questions

A priori, podría solucionarse en base a lo desarrollado

- Double Navigation Bar
- Secondary Navigation

### Additional considerations

Parece que hay hueco en desarrollo para encajarlo.

### Do you have a visual proposal?

![Captura de pantalla 2023-04-14 a las 15 09 33](https://user-images.githubusercontent.com/56122343/232052741-79cf842f-7e68-4b92-bcfb-18b8f1855493.png)
</div>

**Comment by HectorSancho** [comment]
https://jira.tid.es/browse/WEB-1397
