### ISSUE TITLE
Fix Image size in callout

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1214]
### Describe the bug

En el componente Callout en mobile, al cambiar la prop al asset image, este pasa a 24 px en vez de mantenerse a 40px
<img width="194" alt="Captura de Pantalla 2023-04-28 a las 12 17 31" src="https://user-images.githubusercontent.com/88187691/235121847-31c02380-8103-48ab-98f4-736faa65c7f9.png">

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

1. Ir a la librería mobile.
2. Callout.
3. Probar la prop del asset image.

### Expected behavior

El asset image debería mantenerse a 40 px, igual que el circled image o el avatar.

**Comment by aweell** [comment]
Hay un truco del almendruco para ponerla a 40: 
1. Cambiar el `type` del componente image a `square rounded` o `square fit`
2. Cambiar el horizontal resizing de `fixed` a `hug`
