### ISSUE TITLE
Conflict between the background color of the image error case in inverse context with the design of the new component "Stacking Group"

### ISSUE THREAD

**Issue by brunocezar-tlf** [Telefonica/mistica-design#1218]
Problem:
The default background color used in the Image component "backgroundSkeletonInverse" for the error case has opacity when the theme context is inverse this opacity conflicts with the design definition of the new component “Stacking Group” where it should not have opacity in this case.

This is due to the “backgroundSkeletonInverse” in the skins it calls the applyAlpha function where it adds this opacity to the color.

Solution:
Change the default background color of the image error case from “backgroundSkeletonInverse” to “brandHigh” based on that it is the inverted background color of the Avatar component that will also be used in the new component.

Component Image
<img width="386" alt="component image" src="https://user-images.githubusercontent.com/123959276/235216015-92afb4df-b365-44b6-9601-0b7be0dd4bf8.png">

Skins - vivo
![skins vivo](https://user-images.githubusercontent.com/123959276/235215873-0a94c5f4-357b-4e18-8834-e321cb7905da.png)

Problem:
<img width="263" alt="problem" src="https://user-images.githubusercontent.com/123959276/235221311-d6e0cf0f-2eb3-4c12-bb3d-4b629a092b96.png">

Solution:
<img width="263" alt="problem solution" src="https://user-images.githubusercontent.com/123959276/235221368-0d6bff2e-1e8d-4447-8ad4-7cb016e7a294.png">

**Comment by brunocezar-tlf** [comment]
Another more refined solution to avoid any change in the image error of the Image component where it is currently being used would be the creation of a prop where if the value is true it will use the colors for the "Stacking Group" if it is false it will continue with the default palette from "backgroundSkeleton".

Solution:
<img width="545" alt="Refined Solution" src="https://user-images.githubusercontent.com/123959276/235752553-5b56c79e-bbff-4ad9-b1b4-aa31bb1d4b44.png">

**Comment by aweell** [comment]
Hi @BrunoGuimaraes103, 

Thanks for your input.

Just keep the tokens as they are in the current implementation of the error image. We will modify the values of backgroundSkeletonInverse to fix this problem.

**Comment by aweell** [comment]
The update of the `backgroundSkeletonInverse` is included in: https://github.com/Telefonica/mistica-web/pull/724/files
