### ISSUE TITLE
Deprecate slot examples from Figma

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1225]
Maybe include slot examples in Mística, Figma and you document

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1223

<div type='discussions-op-text'>

<sup>Originally posted by **MontseTelefonica** May  3, 2023</sup>
### Goal

Especificar como debe comportarse el card slot de progress cuando no cabe y debe pasar a 2 lineas
![image](https://user-images.githubusercontent.com/95479574/235899011-d92c850f-a4b1-4b5d-bcc3-8a1a44450807.png)

### Context

Mientras analizábamos el impacto de aumentar el espacio del _next visible element_ en los carrousels, detectamos que en pantallas pequeñas o con textos largos, la data cards con el slot de progress se rompía

![image](https://user-images.githubusercontent.com/95479574/235899318-49e4000a-09e7-4d7f-bc74-4b0076ea2e24.png)

### Impact

Ahora que vamos a aumentar el espacio destinado a visualizar el _next visible element_ vamos a encontrarnos más con este problema y necesitamos tener definido como debe comportarse este slot cuando pasa a 2 lineas. 

### Discussion Questions

-¿Esta definición debe proveerla Mistica o al ser un slot deben realizarse unas specs adhoc para esto?
-Al ser un componente que se utiliza mucho, ¿tiene sentido un Novum extended de las _cards slots_ que tenemos disponibles en Figma?
![image](https://user-images.githubusercontent.com/95479574/235899929-b5977095-2f83-4d0a-9742-d53e04ea2250.png)

### Do you have a visual proposal?

_No response_</div>

**Comment by yceballost** [comment]
@aweell @AnaMontes11 creéis que deberíamos eliminar este componente/ejemplos directamente de la librería y que se "detachen" automaticamente? en lugar de poner una capa

**Comment by aweell** [comment]
Si se eliminan de la librería lo único que pasará es que seguirán apareciendole a los que lo hayan usado como componente, pero cuando clicken en el enlace al componente original no exista no?

**Comment by yceballost** [comment]
> Si se eliminan de la librería lo único que pasará es que seguirán apareciendole a los que lo hayan usado como componente, pero cuando clicken en el enlace al componente original no exista no?

exacto. Bueno, seguimos el proceso habitual, capita roja y más adelante nos cargamos el componente
