### ISSUE TITLE
Mística Tokens | Border radius definition | Include border radius definition in all component specs

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1268]
Included:

- [x] Image & video Specs
- [x] Buttons
- [x] Inputs fields & forms
- [x] Boxed
- [x] Circle

**Comment by yceballost** [comment]
cuál es el estado de esto @AnaMontes11 ?

**Comment by AnaMontes11** [comment]
Las que están actualizadas las voy añadiendo al listado de arriba.
