### ISSUE TITLE
Header slot mantiene el fondo verde a pesar de meter un componente 

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1272]
### Describe the bug

Cuando introduzco un componente en el slot, éste mantiene el fondo verdecillo y no se ajusta a la altura del componente si no que mantiene el de la cajita verde de slot

Aquí ejemplo
<img width="799" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/1284abf6-667a-49c5-978d-ffa9a8403cf1">

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

1. Coge componente Header 
2. Activa slot
3. Introduce un componente

### Expected behavior

El slot debe insertar el componente en con su altura y sin el color verde de fondo

**Comment by aweell** [comment]
Para el tema de la altura, por regla general es aconsejable meter los componentes dentro de un frame antes de que vayan en el slot, de esa manera se evita que determinada configuración en el layout de una instacia del componente colisione con el layout del contenedor del slot

**Comment by yceballost** [comment]
> Para el tema de la altura, por regla general es aconsejable meter los componentes dentro de un frame antes de que vayan en el slot, de esa manera se evita que determinada configuración en el layout de una instacia del componente colisione con el layout del contenedor del slot

entiendo que esa gráfica Montse la tiene dentro de un componente, por lo que el frame lo tiene, igual lo que falla es que ese frame/componente no tiene autolayout activo

**Comment by yceballost** [comment]
Es importante poner un enlace al figma que pones esa captura para que podamos analizar mejor el bug :)

**Comment by aweell** [comment]
Dejo aquí un ejemplo de los dos casos con otro componente

https://www.figma.com/file/8Xz0TJFGje3xNRZWh8haZW/Slot-replace-change?type=design&node-id=0%3A1&t=uXhYM7AIPz2Q9iZn-1

Y el figma al caso en cuestión que plantea Montse:
https://www.figma.com/file/xNUwhH29z3Fre4foNltgtX/CPS_Specs?type=design&node-id=242%3A34697&t=I4hoLHXInKbupfrG-1

**Comment by yceballost** [comment]
Para el problema del fondo, hay que desligar el background del main level del slot, y que se incluya una capa debajo del texto con position absolute
