### ISSUE TITLE
Fix badge size

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1275]
### Describe the bug

Badge has different size from mistica-web implementation

### What libraries are you seeing the problem on?

Mobile Library, Desktop Library

### Steps to reproduce

Compare with web

### Expected behavior

The correct size is 18x18 and 8x8 in the non-numeric variant

**Comment by aweell** [comment]
Aprovecho para corregir un error en desktop:

Cuando cambias la badge a non numeric en un avatar mantiene el tamaño:

![Screenshot 2023-05-29 at 09 53 59](https://github.com/Telefonica/mistica-design/assets/44420072/ab4d31c7-0ab2-4cd3-9b56-863ec4c39691)
