### ISSUE TITLE
New token for tabs label

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1286]
- [x] Update specs
- [ ] Design documentation
- [ ] Add to brand libraries (wait to Figma Variables)
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13468)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9078)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1432) 

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1278

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** May 30, 2023</sup>
### Goal

Melhorar a  leiturabilidade da experiência da pessoa usuária e deixar o sistema mais consistente.

### Context

Nos fluxos do Novo App as abas ganham caráter de título em alguns contextos, precisamos ter um tamanho e peso de fonte equivalentes em outras páginas para garantir conforto na leitura das informações e consistência no sistema. Por esta razão, solicitamos o ajuste de text-preset 3 para text preset 4 (de: 16 -> para: 18).

### Impact

Aumentar o tamanho da tipografia no componente Tabs melhoraria a consistência no sistema e a experiência da pessoa usuária.

### Discussion Questions

Seria possível fazer esse ajuste na biblioteca Mística?

### Do you have a visual proposal?

https://www.figma.com/file/VkXWMSV45UmSpbwsiJ1svN/Tabs?type=design&node-id=1210%3A19304&t=ARPzIWPV9NTCCf3F-1</div>

**Comment by aweell** [comment]
Updated specs: https://www.figma.com/file/PApssATUkePZnIOB4GmAeI/branch/XrVdts3xEHrQAFC3ztaQgE/%F0%9F%94%B9-%E2%80%8E%E2%80%8ETokens-definition?type=design&node-id=2190%3A1642&t=YEXCdIpDM34dvtqa-1
