### ISSUE TITLE
Include new Figma Features (Part 2)

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1324]
_This part2 is because the Figma variables are at a very early stage and we have to wait for it to settle down more to see how it will work with skin changes, etc._

## Description
- Colors as variables (palette) and constants using palette aliases.
- Use all variables in components

What happend with styles? Maybe include some mechanism to migrate styles to variables.

All indications are that we will not need the dark libraries. 🙌

- [x] #1407

**Comment by aweell** [comment]
Closed as done
