### ISSUE TITLE
Add title scale to header component

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1341]
Include definition to manage title size through props in the header component

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Android ticket
- [ ] iOS ticket
- [x] Web [ticket](https://jira.tid.es/browse/WEB-1469)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1125

<div type='discussions-op-text'>

<sup>Originally posted by **AnaMontes11** March 14, 2023</sup>
A veces se usa el título del Header como solución a casos en los que se requiere de un título principal para abrir página.

¿Tiene sentido crear una escala de "titles" más completa, que evite este tipo de usos?

Podríamos establecer una escala de titles acotada por jerarquías de uso tipo:

<img width="486" alt="titles" src="https://user-images.githubusercontent.com/88187691/224999437-c09b0497-ffe7-4d5e-af94-8dd5b9f78cfe.png">
</div>

**Comment by AnaMontes11** [comment]
Finalmente se ha añadido una variante Small al Header que cambia el tamaño del Title y la Description 
Se añade también la posibilidad de mostrar/ocultar los paddingY internos del header
