### ISSUE TITLE
Change backgroundBrandSecondary for Vivo New

### ISSUE THREAD

**Issue by annefranca** [Telefonica/mistica-design#1349]
## Description

Alterar a cor do token backgroundBrandSecondary (de: #660099 / para: #751AA3 - vivoPurpleLight90)

## Tasks

- [x] Add to vivo new library
- [x] Web pr

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1339

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** July  3, 2023</sup>
### Goal

Alterar a cor do token backgroundBrandSecondary.

### Context

Os tokens backgroundBrand e backgroundBrandSecondary estão recebendo a mesma cor e gostaríamos de fazer essa alteração para aplicação nas interfaces.

De: #660099 / Para: #751AA3 (vivoPurpleLight90)

### Impact

Adicionar essa nova cor em um token existente nos oferece mais opções para explorar contrastes diferentes.

### Discussion Questions

Como podemos fazer essa alteração? Seria responsabilidade do time da Vivo?

### Do you have a visual proposal?

_No response_</div>

**Comment by yceballost** [comment]
Reopen this ticket with new change to `vivoPurpleLight80`

- [x] update tokens
- [x] update figma library
- [x] update web
