### ISSUE TITLE
Bug in Over Alternative Tags (Telefónica skin)

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1357]
- [x] Update tokens (create PR)
- [x] Add to Telefónica library
- [x] Update Specs

### Describe the bug

En la skin de Telefónica, las tags con theme context "Over Alternative" sobre `backgroundAlternative` no se visualizan correctamente ya que `brandLow` y `backgroundAlternative` tiran del grey1.

<img width="204" alt="tags" src="https://github.com/Telefonica/mistica-design/assets/88187691/1ca1dd1e-c921-4278-acdb-d52fa6648583">

### What libraries are you seeing the problem on?

Telefónica Library

### Steps to reproduce

1. Abrir un archivo figma
2. Crear un frame con backgroundAlternative
3. Meter tag estado Active
4. Pasar Themer Telefónica
5. El fondo de la tag se pierde con el background

### Expected behavior

Diferencia visual entre la tag y el background como en el resto de brands.

### Link a Figma file with your bug

https://www.figma.com/file/wseConngNv2MYEXgCk5uI4/%F0%9F%94%B8-Tag-Specs?type=design&node-id=2216%3A1926&mode=design&t=p18guWhnuP8mQjc3-1

**Comment by aweell** [comment]
Pasa en [otros casos](https://mistica-web.vercel.app/playroom/preview/#?code=N4Igxg9gJgpiBcIA8BnALgTwDYwHwB0A7AAmOAAMiqSA6SQtAQwEtCYAnYI4qZlAByyMM8YqyysYAWgBmOAB4BubgCMI7WOykB3ZlDQALUQEZ+S1es1T02GKJQQJUZSTUaOU9o14BXFKIBOILMXYn5vXkIAc1EAJhDubgBfahpWfh80MiI3TVFCCDYXcKhImOIABhddfSNiABYADgSGGHk0KUYJKMJRMBhW9hcVRjAAayj2CB9CKFE0L0IBRnYBtBcUwmpianJNpAB6GxwCLcJgAAoLgEpiAF5cbJJienRiAEl6e+IL4GIANy6PhgxCStweT1IpGYMh+gKwwOISDuxGMty4zyhxFWaB87BIF24WKhSE+hQAKl4UAYAMKMQgAJRgUR8QnYROJUJQzAAXjA7sBjAA2TacrGQLDqAUS9QoOiFBaOACi7Cm7FFYtwhzJhEpjGpdMZzNZK1OnOuoShSWIMCwKBBGM5OLxJCQ5LaaHqL0cUuAMvYcvoiqwAEEwGhmIC0DAoElcFJDu72vVcJbSBqki4ia8sjTpoNvr8xCgQ1ho-jGBH-iCUTIuvaADTF96EasBmvEOt2kFg+6PR1QnPEADa8OBTftaAAakCYABdb5M0ZoGh+GAAZSY0YuFQtHO9Syyw74ABEYGBVvqYAAJCBtmMTmBod4oM8XmBX2-3qALlFL8Orvam6VjAFxdvae6YgebzHigLbvp+d4cA+xCTi+8GXvaX7IT+i4fgBa7Adu4EwJB+5DgY9JQDgGEfvahbgv2+6kJOM4IqBFz8Ks-xscCjFhNxvEggA1KikFYpm2yDoUbyUbMOBvphHY3H2kLEjCcKzsQjxompnKsbOVxcTAPGzvxxmmexxBSGJaZWvuklnOKMlZGAzDsGAOCbrY3wDliNSGKI+AgAAzPE8jBQ2zHEAYMDMFEBhoEFoXhZF0W5BwDLeMwfjJQArBUACkaVQaQIzjJM+ZQHmkrsMlCz0ssqwMCVnK8AIQgiDsIByG0rXEgAVn4EYyBgeatAwyX9IM-VYl08WEO80YALb+N103lrNg54g4dXdfwECsJtIBRVBjnkS5MVUQp55Kdh7CFnw90xvxflck+L6KXRN5IasUAXE9v0vXZ51QRR10wLRiFto9KDPVAr3RWhcGEAhWFA-9gPfuJVpZlBzr4j80VILw-zRaQnn6igAByjDLfywVBiwbDsiA5OoZgOACm9nIZewNXqKIfAtm29EAPzerVcrlRMUwzNVCrMxwxB9D6AY0Hzp1ilCMuVfLQslmWHCEJWkYwOzWIS-60ujLLVWluWJtVubpViqrUsa7beuzONTCSOwWtikkGpYmaYputMYCUSoODEIUAAKqwoCgApydRMBfVecYW0ipM5xTQjJ7T9N3Iz7meebbOu-pnP8sAPPa8QNDN25HlebXgeNzrXtyz7asG5n6PfvnxIS2OII6SPnJW2r0uLFAAAyEDaFPxLu7KNAcGqS8r9Xjf1YsTVrFt2vByPhQALLTPaSqDAKKkQmnN1oz9bYXAsfEh43l-XzAC8ftWe+-En4Z1ut9e6YF6ykS-pyMOXdSRfHHgKce1oDhwPDgcUm6CsSJkjtHE47MkDpEyDnY4dc-j+nXuraM7RE7MGWisDAoIYHEkpkXOmDMQDELQMFHOmB+CcMID4ZaKgOC8L3qQJBwAUE50vFAAA8oQLAGB2ZoMIeSPBjAY4ggTknFOwAQFQ3tNnCRudIwjzYTTDhpdwDlxwOIruLFa7c1Xs3OgdiNwd1XrrXuCtaoGyMa-HCq9SAzw9ioeeO8Qkq26g1JY4Rmo8JOiPM+pjSA-zXLfcsQDVKGNRndX6792Cf3PoQK+a5-6MEAZcYBENAkQJItcFhocR5ug9F6f00pZ7ygYFMUM4ZIwgVjLgYSiZ2nYOJIcLBhCDgaJ8FHLRBDXZTMjOgnGoNSAEwJPuJAEykCJxMswGA2gNGOBQFqA4Bz-hHJORAM5eymQCBkmbBewhphoAmaQJAAAhCA8gwgRFYFEAUsR6gmPgXmGY5ZiBqL3ocX58g9kHEeQdJYLy3mZAeTAJ5aLqyvIwO8gEKxmD0jQDY1gotK6fKRAigFpQgUgrBdSr5kKCzC1bBweisLtbwr+UilFzy8UYo+cTAVuK-7CqJewElDAbFdEdqbaswVqU-L+XSsojLwWNyQKy6FfAHbG0VSCblGCEX8uxai7kQqCWYp2SayCYIbibBOiAQwMB6YIBAO6HAMhCjMDAIwEASQgA), aquí la verdad, tengo mis dudas...si deberíamos subir un poco el `brandLow` o bajar el `backgroundAlternative`

**Comment by yceballost** [comment]
> Pasa en [otros casos](https://mistica-web.vercel.app/playroom/preview/#?code=N4Igxg9gJgpiBcIA8BnALgTwDYwHwB0A7AAmOAAMiqSA6SQtAQwEtCYAnYI4qZlAByyMM8YqyysYAWgBmOAB4BubgCMI7WOykB3ZlDQALUQEZ+S1es1T02GKJQQJUZSTUaOU9o14BXFKIBOILMXYn5vXkIAc1EAJhDubgBfahpWfh80MiI3TVFCCDYXcKhImOIABhddfSNiABYADgSGGHk0KUYJKMJRMBhW9hcVRjAAayj2CB9CKFE0L0IBRnYBtBcUwmpianJNpAB6GxwCLcJgAAoLgEpiAF5cbJJienRiAEl6e+IL4GIANy6PhgxCStweT1IpGYMh+gKwwOISDuxGMty4zyhxFWaB87BIF24WKhSE+hQAKl4UAYAMKMQgAJRgUR8QnYROJUJQzAAXjA7sBjAA2TacrGQLDqAUS9QoOiFBaOACi7Cm7FFYtwhzJhEpjGpdMZzNZK1OnOuoShSWIMCwKBBGM5OLxJCQ5LaaHqL0cUuAMvYcvoiqwAEEwGhmIC0DAoElcFJDu72vVcJbSBqki4ia8sjTpoNvr8xCgQ1ho-jGBH-iCUTIuvaADTF96EasBmvEOt2kFg+6PR1QnPEADa8OBTftaAAakCYABdb5M0ZoGh+GAAZSY0YuFQtHO9Syyw74ABEYGBVvqYAAJCBtmMTmBod4oM8XmBX2-3qALlFL8Orvam6VjAFxdvae6YgebzHigLbvp+d4cA+xCTi+8GXvaX7IT+i4fgBa7Adu4EwJB+5DgY9JQDgGEfvahbgv2+6kJOM4IqBFz8Ks-xscCjFhNxvEggA1KikFYpm2yDoUbyUbMOBvphHY3H2kLEjCcKzsQjxompnKsbOVxcTAPGzvxxmmexxBSGJaZWvuklnOKMlZGAzDsGAOCbrY3wDliNSGKI+AgAAzPE8jBQ2zHEAYMDMFEBhoEFoXhZF0W5BwDLeMwfjJQArBUACkaVQaQIzjJM+ZQHmkrsMlCz0ssqwMCVnK8AIQgiDsIByG0rXEgAVn4EYyBgeatAwyX9IM-VYl08WEO80YALb+N103lrNg54g4dXdfwECsJtIBRVBjnkS5MVUQp55Kdh7CFnw90xvxflck+L6KXRN5IasUAXE9v0vXZ51QRR10wLRiFto9KDPVAr3RWhcGEAhWFA-9gPfuJVpZlBzr4j80VILw-zRaQnn6igAByjDLfywVBiwbDsiA5OoZgOACm9nIZewNXqKIfAtm29EAPzerVcrlRMUwzNVCrMxwxB9D6AY0Hzp1ilCMuVfLQslmWHCEJWkYwOzWIS-60ujLLVWluWJtVubpViqrUsa7beuzONTCSOwWtikkGpYmaYputMYCUSoODEIUAAKqwoCgApydRMBfVecYW0ipM5xTQjJ7T9N3Iz7meebbOu-pnP8sAPPa8QNDN25HlebXgeNzrXtyz7asG5n6PfvnxIS2OII6SPnJW2r0uLFAAAyEDaFPxLu7KNAcGqS8r9Xjf1YsTVrFt2vByPhQALLTPaSqDAKKkQmnN1oz9bYXAsfEh43l-XzAC8ftWe+-En4Z1ut9e6YF6ykS-pyMOXdSRfHHgKce1oDhwPDgcUm6CsSJkjtHE47MkDpEyDnY4dc-j+nXuraM7RE7MGWisDAoIYHEkpkXOmDMQDELQMFHOmB+CcMID4ZaKgOC8L3qQJBwAUE50vFAAA8oQLAGB2ZoMIeSPBjAY4ggTknFOwAQFQ3tNnCRudIwjzYTTDhpdwDlxwOIruLFa7c1Xs3OgdiNwd1XrrXuCtaoGyMa-HCq9SAzw9ioeeO8Qkq26g1JY4Rmo8JOiPM+pjSA-zXLfcsQDVKGNRndX6792Cf3PoQK+a5-6MEAZcYBENAkQJItcFhocR5ug9F6f00pZ7ygYFMUM4ZIwgVjLgYSiZ2nYOJIcLBhCDgaJ8FHLRBDXZTMjOgnGoNSAEwJPuJAEykCJxMswGA2gNGOBQFqA4Bz-hHJORAM5eymQCBkmbBewhphoAmaQJAAAhCA8gwgRFYFEAUsR6gmPgXmGY5ZiBqL3ocX58g9kHEeQdJYLy3mZAeTAJ5aLqyvIwO8gEKxmD0jQDY1gotK6fKRAigFpQgUgrBdSr5kKCzC1bBweisLtbwr+UilFzy8UYo+cTAVuK-7CqJewElDAbFdEdqbaswVqU-L+XSsojLwWNyQKy6FfAHbG0VSCblGCEX8uxai7kQqCWYp2SayCYIbibBOiAQwMB6YIBAO6HAMhCjMDAIwEASQgA), aquí la verdad, tengo mis dudas...si deberíamos subir un poco el `brandLow` o bajar el `backgroundAlternative`

yo subiría un poco el brandLow

**Comment by AnaMontes11** [comment]
Hago pruebas con las dos alternativas y decidimos

> > Pasa en [otros casos](https://mistica-web.vercel.app/playroom/preview/#?code=N4Igxg9gJgpiBcIA8BnALgTwDYwHwB0A7AAmOAAMiqSA6SQtAQwEtCYAnYI4qZlAByyMM8YqyysYAWgBmOAB4BubgCMI7WOykB3ZlDQALUQEZ+S1es1T02GKJQQJUZSTUaOU9o14BXFKIBOILMXYn5vXkIAc1EAJhDubgBfahpWfh80MiI3TVFCCDYXcKhImOIABhddfSNiABYADgSGGHk0KUYJKMJRMBhW9hcVRjAAayj2CB9CKFE0L0IBRnYBtBcUwmpianJNpAB6GxwCLcJgAAoLgEpiAF5cbJJienRiAEl6e+IL4GIANy6PhgxCStweT1IpGYMh+gKwwOISDuxGMty4zyhxFWaB87BIF24WKhSE+hQAKl4UAYAMKMQgAJRgUR8QnYROJUJQzAAXjA7sBjAA2TacrGQLDqAUS9QoOiFBaOACi7Cm7FFYtwhzJhEpjGpdMZzNZK1OnOuoShSWIMCwKBBGM5OLxJCQ5LaaHqL0cUuAMvYcvoiqwAEEwGhmIC0DAoElcFJDu72vVcJbSBqki4ia8sjTpoNvr8xCgQ1ho-jGBH-iCUTIuvaADTF96EasBmvEOt2kFg+6PR1QnPEADa8OBTftaAAakCYABdb5M0ZoGh+GAAZSY0YuFQtHO9Syyw74ABEYGBVvqYAAJCBtmMTmBod4oM8XmBX2-3qALlFL8Orvam6VjAFxdvae6YgebzHigLbvp+d4cA+xCTi+8GXvaX7IT+i4fgBa7Adu4EwJB+5DgY9JQDgGEfvahbgv2+6kJOM4IqBFz8Ks-xscCjFhNxvEggA1KikFYpm2yDoUbyUbMOBvphHY3H2kLEjCcKzsQjxompnKsbOVxcTAPGzvxxmmexxBSGJaZWvuklnOKMlZGAzDsGAOCbrY3wDliNSGKI+AgAAzPE8jBQ2zHEAYMDMFEBhoEFoXhZF0W5BwDLeMwfjJQArBUACkaVQaQIzjJM+ZQHmkrsMlCz0ssqwMCVnK8AIQgiDsIByG0rXEgAVn4EYyBgeatAwyX9IM-VYl08WEO80YALb+N103lrNg54g4dXdfwECsJtIBRVBjnkS5MVUQp55Kdh7CFnw90xvxflck+L6KXRN5IasUAXE9v0vXZ51QRR10wLRiFto9KDPVAr3RWhcGEAhWFA-9gPfuJVpZlBzr4j80VILw-zRaQnn6igAByjDLfywVBiwbDsiA5OoZgOACm9nIZewNXqKIfAtm29EAPzerVcrlRMUwzNVCrMxwxB9D6AY0Hzp1ilCMuVfLQslmWHCEJWkYwOzWIS-60ujLLVWluWJtVubpViqrUsa7beuzONTCSOwWtikkGpYmaYputMYCUSoODEIUAAKqwoCgApydRMBfVecYW0ipM5xTQjJ7T9N3Iz7meebbOu-pnP8sAPPa8QNDN25HlebXgeNzrXtyz7asG5n6PfvnxIS2OII6SPnJW2r0uLFAAAyEDaFPxLu7KNAcGqS8r9Xjf1YsTVrFt2vByPhQALLTPaSqDAKKkQmnN1oz9bYXAsfEh43l-XzAC8ftWe+-En4Z1ut9e6YF6ykS-pyMOXdSRfHHgKce1oDhwPDgcUm6CsSJkjtHE47MkDpEyDnY4dc-j+nXuraM7RE7MGWisDAoIYHEkpkXOmDMQDELQMFHOmB+CcMID4ZaKgOC8L3qQJBwAUE50vFAAA8oQLAGB2ZoMIeSPBjAY4ggTknFOwAQFQ3tNnCRudIwjzYTTDhpdwDlxwOIruLFa7c1Xs3OgdiNwd1XrrXuCtaoGyMa-HCq9SAzw9ioeeO8Qkq26g1JY4Rmo8JOiPM+pjSA-zXLfcsQDVKGNRndX6792Cf3PoQK+a5-6MEAZcYBENAkQJItcFhocR5ug9F6f00pZ7ygYFMUM4ZIwgVjLgYSiZ2nYOJIcLBhCDgaJ8FHLRBDXZTMjOgnGoNSAEwJPuJAEykCJxMswGA2gNGOBQFqA4Bz-hHJORAM5eymQCBkmbBewhphoAmaQJAAAhCA8gwgRFYFEAUsR6gmPgXmGY5ZiBqL3ocX58g9kHEeQdJYLy3mZAeTAJ5aLqyvIwO8gEKxmD0jQDY1gotK6fKRAigFpQgUgrBdSr5kKCzC1bBweisLtbwr+UilFzy8UYo+cTAVuK-7CqJewElDAbFdEdqbaswVqU-L+XSsojLwWNyQKy6FfAHbG0VSCblGCEX8uxai7kQqCWYp2SayCYIbibBOiAQwMB6YIBAO6HAMhCjMDAIwEASQgA), aquí la verdad, tengo mis dudas...si deberíamos subir un poco el `brandLow` o bajar el `backgroundAlternative`
> 
> yo subiría un poco el brandLow

**Comment by AnaMontes11** [comment]
Finally, the solution has been changing the actual brandLow `grey1` by `telefonicaBlue10`
