### ISSUE TITLE
Link to BF in components Library

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1368]
## Description
Hacer una revisión general en las librerías para detectar los componentes que puedan no estar enlazados a la documentación de BF y enlazarlos.

## Tasks

- [x] Review mobile library
- [x] Review desktop library

**Comment by yceballost** [comment]
Pls, include a list of the component with missing documentation link in the body issue 🙏

**Comment by AnaMontes11** [comment]
**Componentes enlazados a BF en la librería mobile**

- fixedFooterLayout
- Media Card
- Data Card
- Display Data Card
- Naked Card
- Display Media Card
- Poster Card
- Slot
- Controls/PageBullets (carousels)
- Counter (enlazado en input fields a falta incluir su doc correspondiente)
- Logo
- Modals -> Android Alert
- Select
- SkeletonText
- SkeletonLine
- SkeletonRow
- SkeletonCircle
- SkeletonRectangle
- iOS, Android, Web Slider (documentación en WIP)
- StackingGroup
- TextLink
- Title1
- Title2
- Title3
- 

**Sin documentación para enlazar:**

- Video
- Image
- _Icon sizes*
- Circle*
- Boxed*_
- Divider
- Splash Screen

*¿Es necesario tener documentación específica sobre estos componentes?

**Existe en BF pero no en las librerías**
Menu

**Comment by AnaMontes11** [comment]
> Pls, include a list of the component with missing documentation link in the body issue 🙏

Lo he metido en un comentario a parte por dejar separados mobile y desktop.

**Comment by AnaMontes11** [comment]
**Componentes enlazados a BF en la librería desktop**

- ButtonSecondary
- ButtonLink
- ButtonDanger
- ButtonLayout
- ButtonGroup (internal use)
- fixedFooterLayout
- ButtonFixedFooterLayout
- Breadcrumbs
- Media Card
- Data Card
- Display Data Card
- Naked Card
- Display Media Card
- Poster Card
- Header
- Hero
- Input fields (todos)
- Select
- Skeletons (todos)
- Slider
- StackingGroup
- TextLink
- Title1
- Title2
- Title3
