### ISSUE TITLE
ButtonLink bleed properties

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1374]
## Description
Now the alignment in title component with slot is baseline. Change to center.

Test: https://tinyurl.com/2nmrt3q8

## Tasks

- [x] Update specs
- [x] Add to mobile library
- [x] Add to desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1481)

**Comment by aweell** [comment]
Closed as duplicated of: https://github.com/Telefonica/mistica-design/issues/1378
