### ISSUE TITLE
Icones subtract-circle e subtract

### ISSUE THREAD

**Issue by pihcardozo** [Telefonica/mistica-design#1380]
### Contribution guidelines

- [X] Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/contribute/how-to-contribute)?
- [X] Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?

### What brand do you need to include these icons?

Vivo

### Is your icon request related to a need?

Estamos criando o componente [Counter](https://github.com/Telefonica/mistica-design/discussions/1325), e vamos precisar dos ícones adicionar "+" (já existente) e subtrair "-", que ainda não existe na lib. 

### Describe or attach a screenshot of the solution you'd like and needs

Componente Counter com o ícone subtrair "-" já aplicado:

![componente_counter](https://github.com/Telefonica/mistica-design/assets/124393542/c197cd99-5f37-4f81-9261-f97f01501f2d)

### Describe icon alternatives you've considered

Variações dos ícones:

![Variação_icones](https://github.com/Telefonica/mistica-design/assets/124393542/119edd35-44a5-440f-9bc0-4019126eccf9)

### Attach your svg icon with 3 weights (light / regular / filled)

Icone **"subtract-circle"**:

![subtract-circle-light](https://github.com/Telefonica/mistica-design/assets/124393542/7fa26536-550f-4eec-ba9e-7850115b9c25)

![subtract-circle-regular](https://github.com/Telefonica/mistica-design/assets/124393542/c70289b1-1368-417a-ae6d-6beb2a92c777)

![subtract-circle-filled](https://github.com/Telefonica/mistica-design/assets/124393542/a61c5de3-f05f-4c62-9e52-6e9012f99a4f)

Icone **"subtract"**:

![subtract-light](https://github.com/Telefonica/mistica-design/assets/124393542/48652533-47d5-4082-9844-c11f4d91f7f9)

![subtract-regular](https://github.com/Telefonica/mistica-design/assets/124393542/a8b8dda9-f33a-4aaf-9b4a-bdc748adb143)

**Comment by AnaMontes11** [comment]
Hello @pihcardozo,

Can you provide us with the "subtract" and "subtract-circle" icon in different weights so that we can include it in the library?

Thank you!
