### ISSUE TITLE
Button link in ButtonFixedFooterLayout is showing the navigation chevron at the end of the container

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1382]
## Description

The button link content should be set to `hug` instead of `fill`

![Screenshot 2023-07-28 at 14 28 22](https://github.com/Telefonica/mistica-design/assets/44420072/774b8096-b6b1-4a7e-ab0f-276a599cad34)

## Tasks

- [x] Add to mobile library
- [ ] Add to desktop library

**Comment by yceballost** [comment]
is it breaking?
