### ISSUE TITLE
Chevron | alignment regarding text size

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1399]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1392

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** August  7, 2023</sup>
### Goal

Verificar a inconsistência e atualizar alinhando o icon-chevron ao texto do componente.

### Context

Notamos que o icon-chevron no componente Botão Link não está alinhado ao centro na atualização que subiu no aplicativo atual da Vivo.

### Impact

Manter a consistência visual.

### Discussion Questions

ND

### Do you have a visual proposal?

https://www.figma.com/file/NKjZPayMwravBsOEv7ZnFh/Alignment-x-Text-size-(chevron)?type=design&node-id=1444%3A9206&mode=design&t=bY7LjZP0paJyy8T1-1</div>

## Tasks

- [x] Update specs
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13641)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9244)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1499)

**Comment by yceballost** [comment]
alignment x text? or y? 😬

**Comment by aweell** [comment]
> alignment x text? or y? 😬

Fixed
