### ISSUE TITLE
Carousel peek

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1415]
- [x] Update specs
- [x] Specs -> Renombrar `peek` a `mobilePageOffset`
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library (do not apply(?))
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1525)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/979

<div type='discussions-op-text'>

<sup>Originally posted by **MontseTelefonica** January  3, 2023</sup>
Uno de los insights de los data reviews es lo poco que se hace scroll horizontal en los elementos que lo tienen. 
Nuestra hipótesis desde producto es que el elemento segundo elemento no es lo suficientemente visible y que aumentando el item per page en 0.2 en snap cards y 0.1 en media, highlighted y data card hasta hacer visible el icono o parte del texto del siguiente elemento mejoraría el ratio de scroll.

Hace tiempo, en targeting realizaron test con esta misma hipótesis y el resultado fue que aumentó el scroll en los carruseles que tenían los segundos elementos más visibles. Lamentablemente no hemos podido localizar los resultados de estos tests porque son antiguos.

Además en Brasil se han quejado del bajón de CTR al cambiar las featured cards y las han cambiado a este modelo:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/95479574/210326293-879d8b0d-e690-4d52-aa61-e7f5d39692c2.png">

Una opción sería lanzar un test A/B en producción para comprobar esta hipótesis o tirarnos directamente a la piscina con el cambio.

<img width="647" alt="image" src="https://user-images.githubusercontent.com/95479574/210512213-3bb73cd4-ee05-44f0-9791-ee900d54246a.png">

</div>

**Comment by AnaMontes11** [comment]
Renombrar `peek` a `mobilePageOffset` en las specs
