### ISSUE TITLE
"Deprecated" status in Cover Project Starter Template

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1416]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1387

<div type='discussions-op-text'>

<sup>Originally posted by **MontseTelefonica** August  4, 2023</sup>
### Goal

El objetivo principal el eliminar el uso incorrecto de las tags de estado que se hace para poder documentar que un flujo ha sido deprecado ya que actualmente se usa otro estado diferente al que se cambia el texto para indicar el estado deprecado

<img width="551" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/013c1a3d-6cb9-46a3-960d-e8c8e2f32f9e">

### Context

Lo indicado arriba

### Impact

Al generar este estado podemos estandarizar este estado en todos los flujos y que en futuras evoluciones del cover no se rompa.

### Discussion Questions

-

### Additional considerations

-

### Do you have a visual proposal?
https://www.figma.com/file/OJzyf3I6GpCPz4TdY0ilRW/Start-Tab-MovEs-UI?type=design&node-id=255-8214&mode=design&t=djBLCMilmhw58fFz-4
</div>

**Comment by AnaMontes11** [comment]
Añadido Status Deprecated y mejorado el componente para que sea más user friendly
