### ISSUE TITLE
Stacking Group Figma improvements with flex size

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1444]
- [x] Update specs
- [x] Add to mobile library
- [ ] Add to desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1591) (crear ticket a desarrollo para meter los text sizes el el max item igual que en el avatar)

### Additional task

We updated specs to include the 2 text sizes for the max item elements
≤ 40= text-preset-2 / regular
+40px= text-preset-3 / regular

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1431

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** August 29, 2023</sup>
### Goal

Discutir e avaliar a possibilidade de refletir o comportamento do componente que está no código na biblioteca do Figma.

### Context

No fluxo de Seguros, temos a necessidade de espelhar o comportamento do StackingGroup que está no código no Figma. Nesse caso, estamos usando o Stacking Group no advancedCard.

A evolução no Figma seria:
- Ter a opção de carregar um icon;
- Ter a opção de carregar um circle icon;
- Ter a opção de ter apenas 1 elemento;
- Alterar tamanho com múltiplos de 8.

### Impact

Fazer essa evolução no componente, vai nos possibilitar aplicar o advancedCard no fluxo de Seguros ao invés de criar cards novos, dessa forma, podemos reduzir o tempo de desenvolvimento e também não aumentaria o número de componentes em Extended ou Mística.

### Discussion Questions

ND

### Do you have a visual proposal?

https://www.figma.com/file/o6e4TMmc3InCthqcsCO8cZ/Evolu%C3%A7%C3%A3o-Stacking-Group?type=design&node-id=0%3A1&mode=design&t=4bk3PTGROm7eQHXs-1</div>

**Comment by AnaMontes11** [comment]
We are maintaining a conversation with Vivo to clarify what multiples of 8 they require to include

**Comment by AnaMontes11** [comment]
Abrimos para incluir el punto:

-  Alterar tamanho com múltiplos de 8.
