### ISSUE TITLE
Playroom Componente Header 

### ISSUE THREAD

**Issue by LucasAlbuquerque0** [Telefonica/mistica-design#1446]
### Describe the bug

In Playroom it is available to add Subtitle and Button which has been deprecated. Being able to access ends up creating a view that it is possible to use.
[Link do playroon](https://mistica-web.vercel.app/playroom/#?code=N4Igxg9gJgpiBcIA8AJGBDWAnAMugnhAK4AuAOgHYAEVAFhtgLzCoMxaU1dUDOAtugA2g5gHMYJAMol0JGAAoyIfkMFKAlAF9O3KrB5gsASwAOJIxArMlAERgHjZixSXbquk1glGSgmNZAATWIsKhljADMI1x1uc19-YCUAMQBVSQBJAHkAOSoAFQgZQSoANgAGcr4AIxj3XV1Yrh4iavi-AJa2nz9XBoammmrSEktmJAAhEcsABWMBLHwqWa8eHmZ5dSpGAD4qYE1NHYBBMHNLJAB6KZJRijmjBfwdtwH6qkuXwZgADxIsdDjGaCdBgGC0CCCbAfL4UT6UEAAGhAJHofHsCAA2iAAGpGABuEAA%2BjkYAB3EAAXWRZKMUFRPCxAGYKpTNEA)

### What libraries are you seeing the problem on?

Telefónica Library

### Steps to reproduce

No playroom dentro do Mística 

1.  Componente
2.  Header 
3. Interactive Demo
4. Playroom
 

### Expected behavior

Do not display these Subtitle and Button options in the playroom.

### Link a Figma file with your bug

https://www.figma.com/file/R6kE4IGknHKzwNWsQ8Q5Cc/Header?type=design&node-id=2-95&mode=design&t=hxVMdORiXyeazQag-0

**Comment by yceballost** [comment]
Yes, Header component in code still has this elements inside but the elements is marked as deprecated in console. In the next major release we are going to remove all of this elements from headers.

In Web there are a lot of breaking changes pending to release, It is common to make a "bundle" of breaking changes to release together as much as possible

**Comment by LucasAlbuquerque0** [comment]
So is it intentional to keep it in the playroom available for these tests?

**Comment by yceballost** [comment]
yes, playroom reflects (almost 100%) what can be done in code. Right now, in the latest version of Mística in code, you can use those header elements, but a warning will appear that those elements will soon be deprecated.

When these elements will be deprecated, you cannot use it in playroom and you cannot use it in the last version of code
