### ISSUE TITLE
Component Header Slot 

### ISSUE THREAD

**Issue by LucasAlbuquerque0** [Telefonica/mistica-design#1447]
### Describe the bug

Slot is not working inside the component, there was a need to add a button inside the component and it doesn't appear inside, it breaks the component.

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

1. In figma
2. Enable Mobile Mystical Library
3. Import Header component
4. Slot Type
5. Replace
6. Primary Button

### Expected behavior

Wait for the button to appear below the description.

### Link a Figma file with your bug

https://www.figma.com/file/R6kE4IGknHKzwNWsQ8Q5Cc/Header?type=design&node-id=4-102&mode=design&t=jjDOkqnMaRFyFTSX-0

**Comment by yceballost** [comment]
Nice catch! we are going to look into it for the [next release ](https://github.com/Telefonica/mistica-design/milestone/32)
