### ISSUE TITLE
Chip-sim-card icon improvement

### ISSUE THREAD

**Issue by LucasAlbuquerque0** [Telefonica/mistica-design#1453]
### Contribution guidelines

- [X] Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/contribute/how-to-contribute)?
- [X] Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?

### What brand do you need to include these icons?

Telefónica

### Is your icon request related to a need?

Considerando a entrada dos novos ícones de eSIM e a melhora de design que foi desenvolvida principalmente no com a versão filled do ícone, que representa melhor a aparência de um SIM card.

### Describe or attach a screenshot of the solution you'd like and needs

Novos componentes para o SIM Card pensando na melhoria da experiência e acompanhando os novos estilos do eSIM.

### Describe icon alternatives you've considered

![image](https://github.com/Telefonica/mistica-design/assets/143555843/15f60d95-3d28-4382-968e-3da70ff1153c)

### Attach your svg icon with 3 weights (light / regular / filled)

![chip-sim-card-light](https://github.com/Telefonica/mistica-design/assets/143555843/89c2579b-5aa4-4410-9101-741e076775ef)
![chip-sim-card-regular](https://github.com/Telefonica/mistica-design/assets/143555843/8dd5f7b7-d0ce-42e4-adc8-f40dae8b0ebc)
![chip-sim-card-filled](https://github.com/Telefonica/mistica-design/assets/143555843/857f31d5-edac-4f74-8d56-9fe762c788af)

**Comment by yceballost** [comment]
Hi @LucasAlbuquerque0 

I think that the new proposal for regular weight is quite different compared with other icons

For example:
![image](https://github.com/Telefonica/mistica-design/assets/6722153/d0b23f18-0574-4d33-9638-77f13001cd9a)

The line in your proposal in regular weight is quite thinner than the current style. I think this little change would cause a readaptation of all of Mística icons to keep the line style equally :(

I think light and filled version are correct

**Comment by LucasAlbuquerque0** [comment]
Hey @yceballost 
I believe there are no problems with the regular one, the most important thing would be the change of light and filled. Can we continue with this regular icon and apply the improvements to light and filled?

**Comment by yceballost** [comment]
Sure, no problem! Thanks Lucas

**Comment by yceballost** [comment]
Released in web! The icon update in Figma will be released with [10.0.0](https://github.com/Telefonica/mistica-design/milestone/30)
