### ISSUE TITLE
Error feedback component

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1456]
## Description

Al igual que existe actualmente un componente succesFeedback que no ocupa el total de la pantalla, crear un componente errorFeedback con las mismas propiedades.

EDIT 3/10/23

Se replantea que las variantes info y error traigan soporte para pintarse en alternative y descartar la opción del componente inline.

## Tasks

- [x] Update specs
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1533)

**Comment by AnaMontes11** [comment]
Esto enlaza con la #1187
