### ISSUE TITLE
ProgressBar stepped

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1469]
- [x] Update specs
- [x] [Design documentation](https://brandfactory.telefonica.com/document/1846#/components/progress-bar/stepped)
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1572)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1434

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** August 30, 2023</sup>
### Goal

Discutir e avaliar a proposta de um novo componente Stepper ao sistema de design e determinar qual workflow esse componente deve seguir.

### Context

Precisamos de um componente novo de Stepper que seja consistente e reutilizável para que os times não apliquem soluções próprias em cada fluxo do App Vivo.

### Impact

Adicionar esse componente em uma das bibliotecas melhoraria a consistência na experiência da pessoa usuária.

### Discussion Questions

Esse componente ficaria em Mística ou em Extended?

### Do you have a visual proposal?

https://www.figma.com/file/4kwrFyZ5h9gi4vJjZiQbgR/Stepper?type=design&node-id=0%3A1&mode=design&t=jZc8b2XOmpExRBND-1</div>

**Comment by aweell** [comment]
Added documentation for review: https://brandfactory.telefonica.com/document/1846#/components/progress-bar/stepped
