### ISSUE TITLE
Avatar - parity in texts with development

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1475]
## Description
Actualmente en el avatar no existe paridad entre los text-preset implementados en desarrollo y los que tenemos en el componente en Figma.

Lo que hay en desarrollo es:  
≤40dp -> 14pt (text-preset-2/regular) 
+40-64dp -> 16pt (text-preset-3/regular) 
+64dp -> 18pt (text-preset-4/regular) -_este no aplica porque no tenemos este tamaño en Figma._

## Tasks

- [x] Add to mobile library
- [x] Add to desktop library

**Comment by yceballost** [comment]
@AnaMontes11 link web ticket pls!

**Comment by AnaMontes11** [comment]
> @AnaMontes11 link web ticket pls!

@yceballost En web esto está correcto, el ticket [WEB-1591](https://jira.tid.es/browse/WEB-1591) aplica al More item del stackingGroup que busca paridad a como está en el Avatar. Puedes verlo [aquí](https://github.com/Telefonica/mistica-design/issues/1444)

**Comment by yceballost** [comment]
Cierto, me había confundido! sorry!
