### ISSUE TITLE
Paragraph definition

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1479]
## Description
Include in Text specs a definition for paragraph spacing (1em)

## Tasks

- [x] Update specs
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1571) Update ticket when definition is done

**Comment by AnaMontes11** [comment]
@yceballost Metida definición dentro de [Primitives components] (lo saqué de las specs de text-presets)(https://www.figma.com/file/dvMqeg6s8tDh9Hyxu7IYDl/branch/2oHRYbtWu8RXt3m8CWFYEp/%F0%9F%94%B9-Primitive-Components?type=design&node-id=2017%3A365&mode=design&t=VFshfIsJTYuvdsKI-1)
