### ISSUE TITLE
token cardTitle

### ISSUE THREAD

**Issue by annefranca** [Telefonica/mistica-design#1480]
### Describe the bug

Os componentes que usam o elemento Title com o token mobile/componente/cardTitle não está sendo alterado para o tema Vivo New ao passar o plugin Themer.

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

ND

### Expected behavior

ND

### Link a Figma file with your bug

https://www.figma.com/file/seiNjy7YmPWEY3BfY4WYpp/Estudos?type=design&node-id=1148%3A1210&mode=design&t=Cbb7wjeOicMuuYxm-1

**Comment by aweell** [comment]
It seems to be working fine after release 10.0.0, could you check again?

https://www.figma.com/file/04zR2U5I73ZXMv8ni30CYq/Estudos-(Copy)?type=design&node-id=1148%3A1210&mode=design&t=xo0CRNEPdH0aH0XE-1

**Comment by annefranca** [comment]
Obrigada, @aweell 

Testei novamente e foi corrigido.

**Comment by aweell** [comment]
Glad to hear. Closed as solved!
