### ISSUE TITLE
Move Media Content in Cards to Primitive section in BF

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1483]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1422

<div type='discussions-op-text'>

<sup>Originally posted by **AnaMontes11** August 24, 2023</sup>
### Goal

Crea página "Media Content" en Brand Factory

### Context

Al incluir la documentación de las Naked Card en BF veo que en cada tipología repetimos la parte de Media Content.
Para evitar crear documentación demasiado extensa, creo que podría estar bien tener una sección específica "Media Content" que hable de Imagen (tipos de aspect ratio, formatos soportados y calidad de imágenes), a la vez hacer lo mismo e incluir documentación específica para video. De esta manera podemos enlazar a esta página y no duplicar info.

### Impact

Mejora en el consumo de la documentación agilizando a la vez su mantenimiento.

### Discussion Questions

..

### Do you have a visual proposal?

_No response_</div>

**Comment by yceballost** [comment]
Changed, please take a look! @aweell @AnaMontes11 

https://brandfactory.telefonica.com/document/1846#/components/cards

**Comment by AnaMontes11** [comment]
@yceballost I can´t find Primitive section in BF

**Comment by yceballost** [comment]
> @yceballost I can´t find Primitive section in BF

![image](https://github.com/Telefonica/mistica-design/assets/6722153/aee7f59f-0720-4eb8-8877-c7ca49305a0a)
👀
