### ISSUE TITLE
Fixed footer component forces buttonlink width

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1499]
### Describe the bug

When using the fixed footer component, the button link has a fixed width that can be changed even when choosing "hug content" in the configuration

<img width="758" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/aa133eb2-876d-45fe-986e-93aa5f36734e">

<img width="529" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/929a2c01-e23a-4221-8cdb-d22c85f11ec9">

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

> Go to Mistica Mobile
> Choose fixed footer 
> Choose add link and write down something

### Expected behavior

The button link should also adapt to container width to allow larger texts

### Link a Figma file with your bug

https://www.figma.com/file/xNUwhH29z3Fre4foNltgtX/CPS_Specs?type=design&node-id=11081-59778&mode=design&t=W0JUbtQhQJxv2aVn-4

**Comment by yceballost** [comment]
arreglau!
