### ISSUE TITLE
Circle icon disappears on row lists

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1500]
### Describe the bug

When updating Figma, i realized that all rows with circle icon have changed for normal icon instead of keeping the circle prop On.

<img width="537" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/7737cf59-3072-49b7-a769-f533ce08cf21">

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

Go to a design with a row list with circled icons 

https://www.figma.com/file/PQQntaDAEZhpnwVgz7GdzJ/CONSUMPTION-POSTPAID?type=design&node-id=2043-3484&mode=design&t=rQeVxwalla2S0wSC-4

### Expected behavior

Could we have an update so this changes automatically and mantains the circle icon on?

### Link a Figma file with your bug

https://www.figma.com/file/PQQntaDAEZhpnwVgz7GdzJ/CONSUMPTION-POSTPAID?type=design&node-id=2043-3484&mode=design&t=rQeVxwalla2S0wSC-4

**Comment by aweell** [comment]
Hey @MontseTelefonica 

Seems that this could be related with this [breaking change in 6.0.0](https://github.com/Telefonica/mistica-design/blob/pre-production/changelog-versions/6.0.0.md#%EF%B8%8F-breaking-changes) or #1137 released in 8.0.0. The easiest way to solve this is select all instances and activate the prop "Circled Icon".

<img width="685" alt="Screenshot 2023-10-06 at 16 06 33" src="https://github.com/Telefonica/mistica-design/assets/44420072/d8eb8b82-037e-4ced-a0d8-eb2bebab3de5">

Let us know if the solution works
