### ISSUE TITLE
Aspect ratio is forced to 1:1 in data cards

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1503]
### Describe the bug

New update forces data cards to 1:1 aspect ratio and has broken many screens

<img width="212" alt="MicrosoftTeams-image (336)" src="https://github.com/Telefonica/mistica-design/assets/95479574/e4696579-2862-446d-a48f-f5903b68c149">

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

This happens in all files using data cards

Ejample:
https://www.figma.com/file/xNUwhH29z3Fre4foNltgtX/CPS_Specs?type=design&node-id=9423-147900&mode=design&t=4fo3lhAYdxAfKiqP-4

### Expected behavior

The default snap card should be "no aspect ratio" to mantain the current aspect

### Link a Figma file with your bug

https://www.figma.com/file/2fS7RoZDd01IZGjBx9d6Le/Soporte?type=design&node-id=624-32037&mode=design&t=3R53oDBnW1GOx83w-4

**Comment by aweell** [comment]
This seems to be solved in 11.1.0, please reopen if the problem persists.
