### ISSUE TITLE
Update text weight definition in component specs

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1515]
## Description

Some components that were changed to use weight tokens, still have the weight definition of the preset in their specs (e.g. tags).

This specs should be updated to avoid: https://github.com/Telefonica/mistica-ios/pull/314

- [x] Tag specs
- [x] Empty states
- [x] Cards
- [x] Buttons
- [x] Tabs
- [x] Chips
- [x] Badge
- [x] Stepper
- [x] Text link

## Tasks

- [x] Update specs

**Comment by AnaMontes11** [comment]
Incluir [textLink](https://www.figma.com/file/81rPCqGchGf54aoh2kpF1o/%F0%9F%94%B8-TextLink-Specs?type=design&node-id=0%3A1&mode=design&t=mGH8GLbLXS4mIDet-1)
