### ISSUE TITLE
textLink specs: update + Tokens

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1521]
## Description
Separar las specs de textLink de las specs de Buttons e incluir la parte de A11y y text weight definition (#1515)

## Tasks

- [x] Update specs

**Comment by yceballost** [comment]
no se puede hacer todo junto en la #1490 ?

**Comment by AnaMontes11** [comment]
> no se puede hacer todo junto en la #1490 ?

A parte de eso es revisar las specs xq al separarlo, hay que meter el resto de info x ejemplo tokens, que ahora o no existe o está como parte de buttons
