### ISSUE TITLE
Add double interaction with right slot in rows

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1553]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1546

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** November  1, 2023</sup>
### Goal

Avaliar a proposta de evoluir, corrigir e ajustar pontos específicos no componente Boxed Row.

### Context

Na nova Tab de Casa Inteligente, temos a necessidade de ajustar e evoluir algumas propriedades do componente, que são: 

- Subtitle (true/false)
- Description (true/false)
- Double interaction - Slot (Icon Button)
- Custom Color (ref: Poster Card) 

Para o slot, vamos aplicar o Icon Button, com isso, precisamos confirmar se existe a possibilidade de criar states para o componente, pois no Figma, não está disponível.

- Default
- Selected
- Disabled
- Loading

Encontramos algumas questões no componente que precisam ser corrigidas, segue abaixo.

**BUG Double interaction**

Ao selecionar a opção para aplicar um slot, o Divider que separa uma ação da outra, desaparece.

**BUG Theme Variant/Context**

Ao alterar de ”default” para ”inverse”, o componente perde 2px na altura.

### Impact

Fazendo essas correções e aplicando as evoluções propostas, não precisaríamos criar uma nova versão do Boxed Row na biblioteca Vivo Extended.

### Discussion Questions

N/D

### Do you have a visual proposal?

https://www.figma.com/file/nfPtfLecvO1oy4efGCSUDP/Evolu%C3%A7%C3%A3o-Boxed-Row?type=design&node-id=1%3A86&mode=design&t=jglWX0aTaxkjJeo2-1</div>

**Comment by aweell** [comment]
Que pasa si el right slot no es interactivo?
 
Se me ocurre que podríamos hacer los siguiente:

* Si la lista lleva navegación con/sin right slot: chevron y no divider
* Si la lista lleva acción con/sin right slot: no chevron y no divider
* Si la lista lleva navegación y acción: divider y no right slot (igual que los controles)

La acción cuando hay doble interacción estaría cerrada a un action button con icono

Aquí una imagen con el ejemplo:

![Screenshot 2023-11-15 at 10 09 01](https://github.com/Telefonica/mistica-design/assets/44420072/d118805a-ddf7-4f32-82f6-3c1a277188f3)
