### ISSUE TITLE
Documentación de Grid en Desktop Extra Large no se ajustan

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#1557]
### Describe the bug

En los grids de Mística, para las resoluciones extra large, los valores entre la anchura de las columnas, los gutters y el contenedor no coinciden.

En la documentación se menciona que en estas resoluciones las columnas deben tener 76px de ancho con 24px de gutter, y que el container central donde están estas columnas se bloquea en 1224px, dejando solamente fluido (o en modo auto), los márgenes laterales. Pero cuando aplico esto las medidas no coinciden, porque todavía quedan 24px de cada lado entre la columna y el margen.

Como referencia, en la aplicación de lo grid en la resoluciónno large no tenemos estos gutters entre las columnas y los márgenes. Haciendo un pequeño ajuste por aquí, para estudio, y cambiando el ancho de las columnas de 76px a 80px, pero manteniendo gutter en 24px y encajó en la medida de lo container de 1224px.

### Steps to reproduce

1. Construí la cuadrícula de extra large usando las configuraciones disponibles en Brand Factory
2. Activar la visualización de grids en la Figma
3. Ver el error

### Expected behavior

Las columnas deben estar con 80px de ancho, y específicamente las columnas 1 y 12 deben tocar en los márgenes laterales, sin tener un espacio/gutter de 24px entre ellos.

### Link a Figma file with your bug

https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/fundamentals/layouts/responsive-layout

**Comment by yceballost** [comment]
solucionado! muito obrigado @henriquebr85 !! good catch ;)
