### ISSUE TITLE
List specs - Update border radius

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1561]
## Description

Actualizar specs con los token de Border radius en el boxed y en el asset image.

## Tasks

- [x] Update specs (esto incluye los token de Border radius en el boxed y en el asset image)

**Comment by yceballost** [comment]
mmm en realidad es posible poner un tamaño y un aspect ratio custom, no?

PD: Puedes poner un title de la issue más concreto?

**Comment by AnaMontes11** [comment]
> mmm en realidad es posible poner un tamaño y un aspect ratio custom, no?
> 
> PD: Puedes poner un title de la issue más concreto?

Actualicé las specs con el cambio unicamente de los border radius.
