### ISSUE TITLE
Update tooltip specs

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1570]
## Description
Añadir a las specs de tooltip
- En mobile se cierra en cualquier parte de la pantalla menos en el target
- en desktop con hover o con TAB / se hace FOCO
- delay 500ms
- quitar padding mobile 16px
- Si hay un tooltip abierto con focus se hace hover en otro tooltip desaparece el tooltip del focus
- revisar animación
- Quitar boxed de tokens / no usa boxed
- La animación ocurre siempre
- Añadir que cuando está abierto el tooltip y le doy ESC se cierra

## Tasks

- [x] Update specs
- [x] Design documentation

**Comment by AnaMontes11** [comment]
Creado [ticket a web](https://jira.tid.es/browse/WEB-1704) para que cuando exista contenido mínimo, el texto se muestre centrado. De esta manera estaría alineado con lo que tenemos en las specs.
