### ISSUE TITLE
New Icon Consumption

### ISSUE THREAD

**Issue by LucasAlbuquerque0** [Telefonica/mistica-design#1582]
### Contribution guidelines

- [X] Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/contribute/how-to-contribute)?
- [X] Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?

### What brand do you need to include these icons?

Vivo, Telefónica

### Is your icon request related to a need?

We need a **Consumption Icon**, which will be used to indicate the consumption environment within the application.

When we use 5G, 4G, we use icons that already show what type of connection is being used. This new icon indicate how much of the data package was consumed, following the idea of the bars used for connection signals.

### Describe or attach a screenshot of the solution you'd like and needs

With the evolution of Vivo, the need for a specific icon for consumer use was realized.

![image](https://github.com/Telefonica/mistica-design/assets/143555843/945bdeec-770b-4eb7-9a58-44f01de2a24e)

### Describe icon alternatives you've considered

Suggested Tokens: 

- consumption-filled
- consumption-regular
- consumption-light

### Additional context?

Link in figma to see the proposal:

https://www.figma.com/file/fVf7qaHquX7rOdDNQAmn2w/Icon-Consumo?type=design&node-id=1%3A86&mode=design&t=sGPsxuk845LHry0n-1

### Attach your svg icon with 3 weights (light / regular / filled)

![consumption-light](https://github.com/Telefonica/mistica-design/assets/143555843/2e570a1d-7a9f-4863-a351-57e0381caf88)
![consumption-regular](https://github.com/Telefonica/mistica-design/assets/143555843/a14f7a21-d7e6-428c-b51d-9331a2566772)
![consumption-filled](https://github.com/Telefonica/mistica-design/assets/143555843/9eceaf48-73c9-4351-a845-cc74a49066f9)

### Add at least 3 synonyms to improve the search for this icon (don't repeat words that exist in the icon name)

Consumption, Use, Connection, Expenditure

**Comment by yceballost** [comment]
Hi Lucas!

We are going to rename the icon to a `bar chart`. This name is more agnostic than "consumption". "Consumption" is the use of the icon within a specific product, but this icon could be used to change the display of a graph for example.

**Comment by LucasAlbuquerque0** [comment]
Perfect, it becomes something more comprehensive.
