### ISSUE TITLE
Input Field Border Radius Vivo New

### ISSUE THREAD

**Issue by annefranca** [Telefonica/mistica-design#1584]
### Describe the bug

Mesmo fazendo a aplicação com Border Radius Vivo New, o componente permanece com 8px.

### What libraries are you seeing the problem on?

Vivo Library

### Steps to reproduce

ND

### Expected behavior

Ao invés de 8px, deveria ser 12px.

### Link a Figma file with your bug

https://www.figma.com/file/seiNjy7YmPWEY3BfY4WYpp/Estudos?type=design&node-id=1499%3A4958&mode=design&t=MNrbMBp7Gs3e3Jxq-1

**Comment by yceballost** [comment]
Should be fixed now! :)
