### ISSUE TITLE
Button Primary Border Radius Vivo New

### ISSUE THREAD

**Issue by annefranca** [Telefonica/mistica-design#1585]
### Describe the bug

Mesmo fazendo a aplicação com Border Radius Vivo New, o componente permanece com 4px.

### What libraries are you seeing the problem on?

Vivo Library

### Steps to reproduce

ND

### Expected behavior

Ao invés de 4px, deveria ser 999px.

### Link a Figma file with your bug

https://www.figma.com/file/seiNjy7YmPWEY3BfY4WYpp/Estudos?type=design&node-id=1499%3A4959&mode=design&t=MNrbMBp7Gs3e3Jxq-1

**Comment by yceballost** [comment]
Should be fixed now!
