### ISSUE TITLE
Border Radius Button Group

### ISSUE THREAD

**Issue by annefranca** [Telefonica/mistica-design#1589]
### Describe the bug

Mesmo aplicando Border Radius Vivo New do componente Button Group, apenas o Button Secondary puxa a propriedade certinha de arredondamento da borda (999).

### What libraries are you seeing the problem on?

Vivo Library

### Steps to reproduce

ND

### Expected behavior

Fazer com que o Button Primary também possa puxar a propriedade de borda Vivo New.

### Link a Figma file with your bug

https://www.figma.com/file/seiNjy7YmPWEY3BfY4WYpp/Estudos?type=design&node-id=1532%3A141&mode=design&t=N8Tju7vRcmsB8XjL-1

**Comment by aweell** [comment]
Couldn't be reproduced, seems to be solved
