### ISSUE TITLE
Color token change not working in a few icons

### ISSUE THREAD

**Issue by BiancaMach** [Telefonica/mistica-design#1604]
### Describe the bug

We are having trouble with the color token changing of the following icons:

buy-data-regular
buy-data-light
chip-sim-card-filled
chip-sim-card-light
eco-light
justice-regular
pause-regular
pause-light
play-regular
play-light
singleparent-family-regular
singleparent-family-filled
subtract-circle-regular
subtract-circle-light

### Steps to reproduce

When we click on the color and try to chose another token, it just doesn't change (check the video below)

https://github.com/Telefonica/mistica-design/assets/153837409/e9f9c13e-9c8d-4a62-8e4a-e13e8f5aca74

### Expected behavior

The token would suppose to change when we pick another

### Link a Figma file with your bug

https://www.figma.com/file/JHuzksh01yxExMeMQBvymq/M%C3%ADstica-Icons?type=design&node-id=0%3A71&mode=design&t=ag9ZscwWBLL18wI6-1

**Comment by yceballost** [comment]
Should be already fixed!
