### ISSUE TITLE
Icon Pause regular has burnt color and can't be overwritten

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1616]
### Describe the bug

The color is set to neutral height and can't be changed. For buttons we need to have it in brand.

<img width="290" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/0f0e2f7f-d117-4647-912b-08c583dd5381">

### Steps to reproduce

Go to a button, select "with icon" and select pause icon regular.

### Expected behavior

The icon color should be the same as the text color.

**Comment by yceballost** [comment]
will be release today!
