### ISSUE TITLE
Stacking group resources bugged

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1619]
## Description
Sizes in stackinggroup are reset by some reason

![image](https://github.com/Telefonica/mistica-design/assets/6722153/07a87f41-4eb3-4cdf-9f2a-a9073dfce3dd)

**Comment by AnaMontes11** [comment]
Match this component on desktop

**Comment by aweell** [comment]
Seems to be a Figma visual bug, it was solved only by uncollapsing the image layer in the resources with border.
