### ISSUE TITLE
Global definition for hyphens

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1622]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1617

<div type='discussions-op-text'>

<sup>Originally posted by **yceballost** January 12, 2024</sup>
### Goal

Keep consistency between all texts and components of Mística

#### Info about hyphens
Text in Mística have the property to break words with hyphens. Hyphens is used to join words or parts of words when:

**Avoiding excessive white spaces**: If a word is not split and there is sufficient space at the end of a line, it could result in large white spaces between words instead of a uniform distribution. Splitting a word allows for a more efficient utilization of that space.

**Maintaining visual consistency**: Hyphenating words helps maintain visual consistency by preventing a line from having only a few words while the next one is completely filled. This facilitates readability and enhances the overall presentation of the text.

#### Hyphen definition in Mística
**If the word does not fit in the width of the container, the hyphen appears**

#### Current hyphen usage in Mística
- `<Text>` components in Mística have de property to use or not hyphens manually using `hyphens="auto"` / `"manual"`
- Some components always force the usage of hyphens
	- cards
	- tabs
	- lists

### Impact

Consistency in the usage of hyphen

### Discussion Questions

- Should we make default the usage of hyphen and not only in certains component?
- What happens with callout? Should the callout be used as well?
- Use hyphen always or never?

In my opinion, the hyphen behavior should be a global behavior, not only in certain components

### Additional considerations

The definition explained in the context section has some incompatibility issues with some versions of browsers. In Firefox, it does not work in any version

### Do you have a visual proposal?

https://tinyurl.com/ypjcmynb</div>

**Comment by yceballost** [comment]
Communicated to OBPMs
https://teams.microsoft.com/l/message/19:b01b8b7087c943989981ad7d93e506f8@thread.tacv2/1705445097831?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=65f8d85c-7437-43ab-ab26-c14f56045954&parentMessageId=1705445097831&teamName=CDP%20-%20Customer%20Digital%20Products&channelName=OB%20Communications&createdTime=1705445097831
