### ISSUE TITLE
Figma's rows don't allow 64x64 images

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1629]
### Describe the bug

In figma, i can place a 64x64 imagen in the row
<img width="1069" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/d3a4d11a-9a82-4755-8344-cf9887663928">
But then i select the circle prop, the images decrease to 40x40
<img width="964" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/689d32d7-b268-41ec-8c23-d81453fa97ef">

### Steps to reproduce

Go to boxed row
Select asset>image
Go to square-> it looks 64px
Then select circle -> it looks 40px

### Expected behavior

Both options, square and circle should allow to choose 40px ot 64px

**Comment by yceballost** [comment]
@aweell list should be refactored xDD

**Comment by aweell** [comment]
This bug, should be easily solved with the two zero-frame + spacebetween hack.
But I Agree...
