### ISSUE TITLE
Naked card BF - top actions + circular image

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1652]
## Description

The current naked card example allows to display top actions or dismiss with the circular image selected in the "media type" property.

![Screenshot 2024-02-14 at 18 53 36](https://github.com/Telefonica/mistica-design/assets/44420072/860f03d9-0043-4052-bd36-c016e0797f82)

The current definition of the component doesn't allow to use this combination, so should be updated in the documentation to hide them when "Circular image" is selected.

![Screenshot 2024-02-14 at 18 55 48](https://github.com/Telefonica/mistica-design/assets/44420072/63e498f7-4b33-4080-94b9-31744c0f0162)

## Tasks

- [ ] Update design documentation

**Comment by yceballost** [comment]
should be fixed now! check it out and close the issue :)
https://brandfactory.telefonica.com/document/1846#/components/cards/naked-card
