### ISSUE TITLE
→ Inverse | Progress bar

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1655]
- [x] Update specs
- [ ] Design documentation
- [x] [Add to mobile library](https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/branch/HRjIjMZr0wBbZZyiVohuYr/M%C3%ADstica-Mobile?m=auto&t=emiGOhm9p16Dkr7K-1)
- [x] [Add to desktop library](https://www.figma.com/design/DSWhPLyJzbliP1fBrLxDUR/branch/TMvB9XsnSp2E92BJHcvEnk/M%C3%ADstica-Desktop?m=auto&t=ROZqEHCUTG8WPa2Y-1)
- [ ] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-15310)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10643)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2084)

### Describe the bug

In the CMS, any module can be represented in 3 possibles backgrounds, and when used in brand background, the progress bar "dissapears"
![imagen (1)](https://github.com/Telefonica/mistica-design/assets/95479574/6e692347-de83-4759-8edd-42963b861317)

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

New CMS module, still not possible to redirect to an URL

### Expected behavior

The progress bar should have a inverse behavior. Here are some ideas, but I know you will find a best definition :)
<img width="478" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/d973d2fc-e0d2-4636-8d6c-da3e6b6c3ffb">

**Comment by aweell** [comment]
Hi @MontseTelefonica, this issue it has been already identified in https://github.com/Telefonica/mistica-design/issues/948

I'll use this one as a subissue

**Comment by HectorSancho** [comment]
For the widget with the new O2 brand, we have the same problem.

We should review the controlInverse constants and probably include a barTrackInverse.

controlErrorInverse may also be necessary.


<img width="204" alt="Captura de pantalla 2024-05-23 a las 11 28 51" src="https://github.com/Telefonica/mistica-design/assets/56122343/8fa9cdd8-18d8-43e2-9489-f33b3ec81fff">
<img width="212" alt="Captura de pantalla 2024-05-23 a las 11 28 44" src="https://github.com/Telefonica/mistica-design/assets/56122343/0601a51c-679d-4441-8d3d-ab8bf62061d5">
