### ISSUE TITLE
Pricing en Fixed Footer Layout

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1659]
- [x] Deprecar price en fixedFooterLayout en Figma
- [x] Ampliar documentación en BF

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1648

<div type='discussions-op-text'>

<sup>Originally posted by **JoseTelefonica** February 12, 2024</sup>
### Goal

Mejorar la jerarquía de la info del pricing que aparece en este componente en conjunto con las pantallas donde se usa.

### Context

Es un componente que se utiliza en muchos flujos que tienen que ver con la contratación de servicios, donde incluso a veces es el importe total correspondiente a la suma de varios elementos como facturas.

En pantallas anteriores vemos que este concepto de pricing o importe está mucho más presente visualmente y tiene una posición más importante en la jerarquía de información, sin embargo en el componente actual, en conjunto con el resto de elementos, queda poco destacado.

### Impact

Crear un footer donde se refleje información importante como el pricing o cantidad total de una manera más visible y diferenciada de importes secundarios (como importe de una factura por ejemplo)

### Discussion Questions

Podríamos modificar el estilo actual text-preset-3-medium (que es el mismo que se usa en row list y en boxed row para mostrar el precio de un servicio o factura único) por un text-preset-5 para crear una mejor jerarquía en el Footer Fixed Layout.

![asisTobe](https://github.com/Telefonica/mistica-design/assets/129079621/fa7ffe14-3519-481e-9897-3405081cf70f)

### Do you have a visual proposal?

https://www.figma.com/file/cL8KKUna805Zf9ezYjML1r/Mistica-Requests?type=design&node-id=1-464&mode=design</div>

**Comment by aweell** [comment]
Updated documentation:

https://brandfactory.telefonica.com/document/1846#/fundamentals/layouts/fixed-footer-layout
