### ISSUE TITLE
Telephone icon

### ISSUE THREAD

**Issue by LucasAlbuquerque0** [Telefonica/mistica-design#1668]
### Contribution guidelines

- [X] Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/contribute/how-to-contribute)?
- [X] Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?

### What brand do you need to include these icons?

Vivo, Telefónica

### Is your icon request related to a need?

Icone exists in the O2 flow and fits with the needs we have at Vivo.

### Describe or attach a screenshot of the solution you'd like and needs

![image](https://github.com/Telefonica/mistica-design/assets/143555843/1be089f0-2566-4e01-9858-764faf90b67c)

### Additional context?

Figma link: https://www.figma.com/file/Llr2ir3qsE84Amo2rUbQNM/Novos-Icons?type=design&node-id=701-7246&mode=design

### Attach your svg icon with 3 weights (light / regular / filled)

![telephone-ip-filled](https://github.com/Telefonica/mistica-design/assets/143555843/4026b1ee-9a8e-4fd3-96cb-e4a0d57941e0)
![telephone-ip-regular](https://github.com/Telefonica/mistica-design/assets/143555843/855f7a92-348e-4d18-bfd6-63f4e91eda62)
![telephone-ip-light](https://github.com/Telefonica/mistica-design/assets/143555843/cbcba6fe-8b5f-47f2-beb6-c98bcd85576d)

**Comment by yceballost** [comment]
nice! You have permissions in Vivo New library to create a branch and include this new icon right? @annefranca can you help @LucasAlbuquerque0 to do this?

1. Create new branch with the name: `#1668 - Icon Telephone Request `
2. Include icons
3. Ensure that it meets all the requirements for putting icons in mistica (inside the icon page you have intructions)
4. Put me as a reviewer in the branch :)

or would you prefer us to be the ones to include this?

**Comment by annefranca** [comment]
Claro! Posso sim :)
