### ISSUE TITLE
Make `description` field optional for Highlghted Cards

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1673]
- [x] Update documentation
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1758)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1657

<div type='discussions-op-text'>

<sup>Originally posted by **carlosgarciaibanez** February 19, 2024</sup>
### Goal

We want to simplify the management of this type of components, it doesn't seem to make much sense to have a mandatory description in a component like this.

### Context

We are currently using the Highlighted Cards for modules that do not require a description, like our Airtime Rewards module:
![image](https://github.com/Telefonica/mistica-design/assets/4517448/4ee577af-8358-486d-9f0d-ab386e8419e9)
To achieve this, we are currently setting the _description_ field to a blank space, but this is a brittle and problematic solution.
The proper way to go would be to make the field completely optional.

### Impact

This will simplify things and will allow us to remove some dirty hacks.

### Discussion Questions

- Why was the reason to make the _description_ field mandatory in this component?
- If that is a compelling reason, why did we allow these modules without a description on them?

### Do you have a visual proposal?

_No response_</div>

**Comment by aweell** [comment]
The documentation has already been updated in #1650
