### ISSUE TITLE
Text components desaligned on Stepper desktop component

### ISSUE THREAD

**Issue by BiancaMach** [Telefonica/mistica-design#1685]
### Describe the bug

The text components from the steps 4 and 5 are desaligned from the other text components.

<img width="823" alt="Screenshot 2024-02-29 at 16 48 40" src="https://github.com/Telefonica/mistica-design/assets/153837409/6f8ff1ac-0779-4e20-b0df-339febb96ac0"><br>
<img width="766" alt="Screenshot 2024-02-29 at 16 48 53" src="https://github.com/Telefonica/mistica-design/assets/153837409/48360f1e-dbf5-49de-ab68-2ec9deacab2f">

### What libraries are you seeing the problem on?

Desktop Library

### Steps to reproduce

You can see the error on Figma, selecting the component in it's default form

### Expected behavior

The text components should be aligned.

**Comment by aweell** [comment]
Thank you @BiancaMach!, the fix will be released in 13.0.0
