### ISSUE TITLE
Rowlist danger

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1708]
- [x] Update specs
- [x] Dev tickets
	- Web ticket 
	- iOS ticket
	- Android ticket
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add new tokens to Brand libraries
   - [x] Movistar light
   - [x] Movistar dark
   - [x] Vivo new light
   - [x] Vivo new dark
   - [x] O2 light
   - [x] O2 dark
   - [x] O2-new light
   - [x] O2-new dark
   - [x] Blau light
   - [x] Blau dark
   - [x] Telefonica light
   - [x] Telefonica dark
   - [x] Tu light
- [ ] Design documentation
- [ ] Add to UI Kit
- [ ] Review PR
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1835)
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-14560)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10031)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1682

<div type='discussions-op-text'>

<sup>Originally posted by **MontseTelefonica** February 29, 2024</sup>
### Goal

¿Qué solución es más correcta y ejecutable en Mistica?
<img width="885" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/5a5e8b6d-4583-414e-a3b1-cf5bd5e3a2d5">

### Context

Nuestro objetivo es poder tener una acción destructiva en la parte final de la página, en Moves quieren un buttonLink desctructuvo centrado, para O2ES se plantea como row..

### Impact

CMS needed

### Discussion Questions

-¿Puede una row ser destructiva? ¿Existe esa prop¿
-Se puede alinear a la izquierda un botón si está en un button layout?

### Do you have a visual proposal?

https://www.figma.com/file/eE87dEhhkHw8esqhfvoZ0c/Figma-para-poner-ejemplos-de-cosas?type=design&node-id=270-3735&mode=design</div>

**Comment by paulasuarezb** [comment]
☝🏼🤓

**Comment by paulasuarezb** [comment]
Android and Web tickets created. Waiting to get access to iOS Jira!

WEB - https://jira.tid.es/browse/WEB-1835 
Android - https://jira.tid.es/browse/ANDROID-14560

**Comment by paulasuarezb** [comment]
iOS ticked created

https://jira.tid.es/browse/IOS-10031
