### ISSUE TITLE
Bug - Advanced Data Card & Row Block

### ISSUE THREAD

**Issue by LucasAlbuquerque0** [Telefonica/mistica-design#1711]
### Describe the bug

**Row Block - Bug and improvement**
- Left alignment of description text (Improvement)
- When very large text is added to the description, it pushes the title which breaks the text (Bug)

**Advanced Data Card - Bug and improvement**
- Currently the component is being used in place of Button Link Mística, an old Button Type Button Link

**Link do figma para ilustrar melhor as informações:** 
https://www.figma.com/file/ktuYsHucmQyNMRuU9slFX2/Evolu%C3%A7%C3%A3o-e-Melhorias---Advanced-(Buntton)-%26-Row-Block?type=design&node-id=432%3A6211&mode=design&t=D5qekbmCTKM01H4n-1

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

Cartão de dados avançado
1. Vá sem cartão de dados avançado
2. Ative algumas das opções do rodapé que contém link
3. Visualize o erro clicando dentro do componente

Bloco de linha
1. Escreva textos grandes
2. Observe ele quebrando o título e esmagando com o preenchimento

### Expected behavior

**Bug & Improvement**

- The current Row Block has a problem with spacing and line wrapping. It ends up crushing the title information depending on the number of elements. And the Description alignment is on the left and should be on the right.

<s>- Inside the Advanced Data Card, the button link is incorrect, it currently has a Button Link type, it needs to change to the Mística Button Link.</s>

### Tasks

- [x] [Update mobile library](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/RZzxyqCicaRBvFxjioBjw2/M%C3%ADstica-Mobile?type=design&node-id=713%3A0&mode=design&t=1XijKBMLwaGHCAEl-1)
- [x] Update desktop library

**Comment by LucasAlbuquerque0** [comment]
@yceballost Could you open a branch so I can make these adjustments?

**Comment by aweell** [comment]
> Inside the Advanced Data Card, the button link is incorrect, it currently has a Button Link type, it needs to change to the Mística Button Link.

This is breaking and will not be considered in this issue.
