### ISSUE TITLE
Allow carriage return in text properties

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1719]
## Description

Some components now allow to have multiple paragraphs, the idea behind this issue is to support also carriage returns so content can be either be in a new paragraph or in a new line.

TBD the list of components that allow this configuration

Linked to https://github.com/Telefonica/mistica-design/issues/1628

## Tasks

- [x] [Update specs](https://www.figma.com/design/f9tAOJproMIiJJuPchDEhG/branch/qkM6BqAyFdQW5LEN4rrYQs/%F0%9F%94%B8-%5BDRAFT%5D-Text-Specs?m=auto)
- [ ] Design documentation
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1919)

**Comment by aweell** [comment]
This should be compliant with https://www.w3.org/WAI/WCAG22/Understanding/text-spacing.html

**Comment by tuentisre** [comment]
Figma branches linked to this issue

| File | Branch | Last Modification |
| --- | --- | --- |
| 🔸 Callout Specs | [#1719 feat(callout): updates container tokens for callout](https://www.figma.com/file/LzhzNPzE8nY9d7Yvo10d5d/branch/IxqbKTFmeHOiJ3D8pRlgF4) | Today |
