### ISSUE TITLE
→ Accessibility: Components | Use aria-live in input field errors

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1766]
**Error messages**
Use aria-atomic-true and aria-live: assertive to show error messages to screen readers

References:
[ARIA19: Using ARIA role=alert or Live Regions to Identify Errors](https://www.w3.org/TR/WCAG20-TECHS/aria#ARIA19)
[Understanding Success Criterion 3.3.1: Error Identification](https://www.w3.org/WAI/WCAG21/Understanding/error-identification.html)

#1794 Dependency

### Tickets

- [x] UXW: https://jira.tid.es/browse/PRODUCTDSN-2613
- [X] LOC: https://jira.tid.es/browse/LOC-1650
- [x] Web: https://jira.tid.es/browse/WEB-1958

**Comment by aweell** [comment]
There's also another attribute that could work: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-errormessage
