### ISSUE TITLE
NavigationBar hidden tabs are broken

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1785]
### Describe the bug

When you enable Tab 6 (initially hidden) the tab is not adjusting correctly to autolayout
![image](https://github.com/Telefonica/mistica-design/assets/6722153/cacb0e60-a143-4fb7-8623-0df914db80eb)

### What libraries are you seeing the problem on?

Mística Desktop

### Steps to reproduce

1. Put navigationBar
2. Go to layer panel
3. Open Tabs group
4. Unhide Tab6

### Expected behavior

Hidden tabs should accomodate correctly with the rest of the tabs

**Comment by aweell** [comment]
This has another associated issue since the icon in the navigation tab resource is using a broken instance of the Circle component under the hood instead of using iconSizes, this change will be breaking:

https://github.com/Telefonica/mistica-design/issues/1792
