### ISSUE TITLE
Vivo: themer issues in dark mode

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1802]
### Describe the bug

Then using themer for Vivo new y vivo old, chips are not working properly in dark mode. Also the constant "background" is not working in dark mode.
Maybe there are other issues but these are the ones I identified.
https://www.figma.com/design/7oGfCcnzS1okDr2xyRIE54/Entrypoints?node-id=5156-107328&t=IUdnDadiL8rC7Vgi-4
<img width="419" alt="image" src="https://github.com/Telefonica/mistica-design/assets/95479574/0e8f9dd6-7ce0-4e07-b9ae-08e40c985cb2">

### Steps to reproduce

Add add a chip over a "background" background 
Apply themer Vivo(new) dark mode and Vivo dark mode

### Expected behavior

Correct color aplication

**Comment by yceballost** [comment]
Vivo is not using Dark Mode theme

**Comment by MontseTelefonica** [comment]
We know, but the CMS has dark mode prop for all brands and we detect these kind of things :)

**Comment by aweell** [comment]
This bug should no be related to dark mode, the underlying problem is that `textActivated` and `textBrand` are not updated in Themer JSON and are not changing between brands. We changed recently the chips to use this two tokens.

All brands should be updated in Themer to solve the issue
