### ISSUE TITLE
Different colors in Button Primary and Button Primary [D]

### ISSUE THREAD

**Issue by henriquebarrosr** [Telefonica/mistica-design#1813]
### Describe the bug

There has been some change in the “standard” color of some Mísitca components. We noticed that there was a change in the hexadecimal code of the tokens of some components (like Button Primary, for example) and the color became a little darker.
It seems that there was an error in the case of Button Primary, which although it loads the token with the correct hexadecimal color, when we add it to the screen it still comes with the old (lighter) color.
![image](https://github.com/Telefonica/mistica-design/assets/161517581/c99201a9-c675-443b-94d7-000eb350cfd7)
![image](https://github.com/Telefonica/mistica-design/assets/161517581/70a67bf6-bc3a-4f33-bf1d-f1e7f1bd3b8b)

### What libraries are you seeing the problem on?

Mobile Library, Desktop Library

### Steps to reproduce

1. Navigate to the `Assets` tab;
2. Add the `Button Primary` and `Button Primary [D]` components;
3. Use the eyedropper tool to check the hex code of the color;
5. See the result;
6. Also compare with what is available in Mística’s Storybook;

### Expected behavior

Understand if there has been a change in the color of the component and, if so, make the adjustment to the component with the old color.

**Comment by aweell** [comment]
The desktop library was not updated with the latest Movistar skin changes. We'll release a new version with the solution of this bug.
