### ISSUE TITLE
MMS icon in O2 Brand

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1834]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/1830

<div type='discussions-op-text'>

<sup>Originally posted by **JoseTelefonica** July 17, 2024</sup>
### Goal

Get an icon to represent MMS messages.

### Context

We need to differentiate between SMS and MMS message.

### Impact

Feed the O2 icon library.

### Discussion Questions

Could we have this new icon?

### Do you have a visual proposal?

https://www.figma.com/design/qKsUe3xW8wDOoySLOzWw3I/My-O2-App-Master-2024?node-id=1680-112447&t=SBFI7BIGirh3f1Zh-4</div>

**Comment by yceballost** [comment]
@joseTelefonica can you include light and filled weight too? Just to keep the set as complete as possible

**Comment by JoseGonzalz** [comment]
I have left the light and filled icon on figma.
https://www.figma.com/design/qKsUe3xW8wDOoySLOzWw3I/My-O2-App-Master-2024?node-id=1680-112447&t=nqOwVIQIO0TZ5U9K-4
