### ISSUE TITLE
Vivo-type medium weight

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1839]
## Description

https://jira.tid.es/browse/OBVIVO-2687

Update the typekit definition adding vivo type medium and, update some of the weights of the current tokens. 

The file with the font weight is attached to the JIRA ticket

## Tasks

- [x] [Update specs](https://www.figma.com/design/IrcHGIgsF5Cq4ZX1LRhuis/branch/whW0NZOo6A16eLaJ5hZXEm/Vivo-New?m=auto&node-id=1312-2979&t=NMkNu5CSnn2c5Vm9-1)
- [ ] Android ticket
- [ ] iOS ticket
- [ ] Web ticket

**Comment by yceballost** [comment]
Missing update tokens files, right?

**Comment by aweell** [comment]
Updated token files, and action launched: https://github.com/Telefonica/mistica-design/actions/runs/11552442757/workflow
