### ISSUE TITLE
Title text is lost in the android/navigation bar component.

### ISSUE THREAD

**Issue by andredelramo-hm** [Telefonica/mistica-design#1853]
### Describe the bug

In navigation bar component, when you change to Inverse theme, you lost the title.

![example](https://github.com/user-attachments/assets/4f33545e-629c-4ca1-9c94-1b2017716902)

### What libraries are you seeing the problem on?

Mobile Library

### Steps to reproduce

1. Take an instance of **_Navigation Bar + Status Bar_**
2. Change the property _**Theme Variant**_ to **_alternative_** o **_default_** 

### Expected behavior

If you change the title, it should keep the new text you included.

**Comment by aweell** [comment]
In order to avoid the breaking change we'll keep the variants in the component available until 16.0.0
