### ISSUE TITLE
Mística & Figma onboarding with variables

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1856]

**Comment by yceballost** [comment]
Should we add documentation about Brand logic variables? Would be useful this logic to designer who design to multiples brand?

**Comment by aweell** [comment]
Updated document: https://www.figma.com/design/t4zLZLdqFLHOCf1DIaxS8e/%F0%9F%94%B9-M%C3%ADstica-%26-Figma-onboarding?m=auto&node-id=0-1&t=yWUM39RFen4T0rXB-1
