### ISSUE TITLE
Evolution Advanced DataCard - Divider + update Button Link

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1882]
## Description

* Remove the divider that separates the slots. And a spacing of 32px between slots.
* Update Link button in component resources

https://jira.tid.es/browse/OBVIVO-2287

## Tasks

- [x] Add to mobile library
- [x] Add to desktop library

**Comment by LucasAlbuquerque0** [comment]
@aweell todo esta bien?
Hubo una nueva evolución en la tarjeta de datos avanzados, se agregó la propiedad NoExtraDivider y necesitamos agregarla a esta implementación, si lo prefieres puedo agregar la propiedad directamente a la Branch.
Enlace para ver el accesorio en el libro de cuentos:
https://mistica-web.vercel.app/?path=/story/community-advanceddatacard--default&args=noExtraDivider:!true
