### ISSUE TITLE
Update Large Navigation Bar on mobile to support an icon on the left

### ISSUE THREAD

**Issue by andredelramo-hm** [Telefonica/mistica-design#1898]
## Description
In the Navigation Bar component (large option) in the mobile library, we don't have an option to add an icon in the upper left part.

Material 3 Ex: 
![image](https://github.com/user-attachments/assets/9432ce9b-65f3-4c95-a6d2-fc918df89313)

## Tasks

- [ ] Update specs
- [ ] Design documentation
- [x] Add to mobile library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [ ] Web ticket

**Comment by aweell** [comment]
Questions open about this topic: https://teams.microsoft.com/l/message/19:9d2d0d5e2fb6472bb80f534bd702cf20@thread.tacv2/1729179049061?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=e265fe99-929f-45d1-8154-699649674a40&parentMessageId=1729179049061&teamName=M%C3%ADstica&channelName=design-appscore&createdTime=1729179049061&ngc=true
