### ISSUE TITLE
Release 15.18.0 — Radio Button

### ISSUE THREAD

**Issue by ipozuelo** [Telefonica/mistica-design#1904]
Buenas, queremos un comportamiento que no logramos hacer con los componentes de mistica. Utilizamos RadioGroup y RadioButton para seleccionar dos opciones. Pero en un caso, una de las opciones tiene que estar deshabilitada dependiendo de la información que nos llega. Solo vemos la opción de deshabilitar en el RadioGroup, queremos en el RadioButton. Hemos visto que en RadioButton hay un render que tiene algo de disabled, pero no logramos hacerlo funcionar. Está dentro de una BoxedRow, que si está deshabilitada, pero se puede seguir pulsando el RadioButton. 
![image](https://github.com/user-attachments/assets/052d76ad-6904-4279-b4d5-bfd13d15158b)

**Comment by ipozuelo** [comment]
![image](https://github.com/user-attachments/assets/41011b8d-63e9-4969-9043-e96017192a4a)
esto es lo que queremos evitar

**Comment by yceballost** [comment]
Hola @ipozuelo ! Lo analizamos!

Puedes pasarnos un ejemplo de lo que tienes construido en Playroom?

[mistica-web.vercel.app/playroom](mistica-web.vercel.app/playroom)

**Comment by yceballost** [comment]
A día de hoy no es posible tener un valor de un radio group disabled. O están todos o ninguno.

Me parece que puede tener sentido lo que comentas, voy a mover esto a discussion para hablarlo con el equipo y de ahí decidir si se incluiría o no.
