### ISSUE TITLE
El componente pop over de desktop esta roto

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#1916]
### Describe the bug

El aspa de cerrar no se adapta al ancho del pop over

### What libraries are you seeing the problem on?

Desktop Library

### Steps to reproduce

https://www.figma.com/design/oGhp04P687JMPfGoOKKsqk/Untitled?node-id=5-1017&t=0vq3g7BEk1NXI7Mu-4

### Expected behavior

El aspa deberia adaptarse al ancho del popover

**Comment by aweell** [comment]
Solved, will be included in [15.1.0](https://github.com/Telefonica/mistica-design/milestone/59)
