### ISSUE TITLE
Pin Field (icon-warning-regular)

### ISSUE THREAD

**Issue by annefranca** [Telefonica/mistica-design#1937]
### Describe the bug

No Storybook e nas documentações existe o ícone warning-regular quando o componente está no estado de erro, mas no Figma o ícone não existe.

<img width="824" alt="Captura de Tela 2024-10-22 às 16 33 35" src="https://github.com/user-attachments/assets/6ad66ca5-92c2-435d-af63-011ce4b81c8e">

<img width="681" alt="Captura de Tela 2024-10-22 às 16 35 37" src="https://github.com/user-attachments/assets/7489b796-052b-4a1e-9904-fd18ea9ab4b0">

### Steps to reproduce

N/A

### Expected behavior

Espelhar no componente disponível no Figma o icon-warning-regular.

**Comment by yceballost** [comment]
oh, we forgot to add it in #1794 🫣

Thanks @annefranca we will include it asap
