### ISSUE TITLE
Include Theme Context in Input Fields

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1945]
## Description
https://teams.microsoft.com/l/message/19:067f481b0bca426a9abd653dd989cee7@thread.tacv2/1730804810339?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=e265fe99-929f-45d1-8154-699649674a40&parentMessageId=1730804810339&teamName=M%C3%ADstica&channelName=M%C3%ADstica%20-%20Latch&createdTime=1730804810339&ngc=true

## Tasks

- [x] Add to mobile library
- [x] Add to desktop library

**Comment by aweell** [comment]
Select component is not working as expected:

https://mistica-web.vercel.app/playroom/#?code=N4Igxg9gJgpiBcIA8AFATjAbgSxgdwBUIIAbAZwD4kB6dLXQ48igHQDskAlGMgBwjZlsmGABkAhgE8IAVwAuAAmxkAkmxFoyMVmwUKkAIQgAPBb3FQo2NgHMAmgF5gAFgAcAXx169SAjGNyAGK4JFAKABYwJLwwaH4BDiwg4thQAEYAZgCPANbYBgAiAIIAygCLANKBaeI5WWRQGUkKbOIAtjCJIK0dzSTiaVFdAHLtMM0YFgDybCSSCtRe3qjhAjDDMm2DaMFRYT2dSbyrbOMgCv2DJF0oJ2cLSz4lUTBgipHRsfFyXVDiZBkAFatchQNiAjL-RpJdjebwHLoZNAybByMgw3Rwi4DIZJADCqwgWgU4gUSJRcgxWIUEF4cmwAjITgA2rDqQpgApMOISDIYPAFEkIGhxLYzgAaBRyfxyAVJKYisXNdzitnUznc3n8wUgGqtVpJSXSgJykAGUUW5WqzFwgC67jVD2AzSSDsxNCMxh0NG4fEZwjEUlkch0IHFIDkkQ6ZAQzJAfhIMAyAmwYHEIFt4bwqUjMfgzIAzAA2AAM4oAjMXXPagA

Web ticket: https://jira.tid.es/browse/WEB-2120
