### ISSUE TITLE
iOS Switch Inverse on figma

### ISSUE THREAD

**Issue by vinrosa** [Telefonica/mistica-design#1946]
### Describe the bug

![image](https://github.com/user-attachments/assets/dba1f0c6-3720-47da-95ab-d12dda39cf02)

The iOS Switch in Figma seems to have a problem with the control token, in Brand Factory when unchecked it seems to use a white token but in Figma a token appears in the brand color

### Steps to reproduce

On figma

1. Import a IOS/Switch from the Mistica mobile library
2. Select the Theme Context Inverse
3. Leave the prop State unchecked

### Expected behavior

Figma should reproduce exactly as it is in Brand Factory because the color difference helps to differentiate the component states.

![image](https://github.com/user-attachments/assets/af86003f-3a4e-4b91-9bdf-9605c33d2247)

**Comment by yceballost** [comment]
Ops! se coló un token! Muchas gracias Vini! lo corregimos ASAP
