### ISSUE TITLE
floppy-disk for o2 style

### ISSUE THREAD

**Issue by iveneva1** [Telefonica/mistica-design#1956]
### Contribution guidelines

- [X] Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/contribute/how-to-contribute)?
- [X] Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?

### What brand do you need to include these icons?

O2

### Is your icon request related to a need?

We need an icon to symbolyze saving action. The save icon exists in the most standard icon sets and is beeing used for saving actions in different application. 

### Describe or attach a screenshot of the solution you'd like and needs

Save Icon. 

[icons_save.zip](https://github.com/user-attachments/files/17732973/icons_save.zip)

### Describe icon alternatives you've considered

We didn't find any similar alternative for the save action

### Additional context?

The icon should be used in the o2 for You App, where the user can actively save an action - for example the user fills out a form and wants to save the changes.

### Attach your svg icon with 3 weights (light / regular / filled)

![save_light](https://github.com/user-attachments/assets/42fb3deb-1ed4-40de-8095-0ad83d45d186)
![save_regular](https://github.com/user-attachments/assets/95090261-875e-4177-b84e-0e42a2ebcd7e)
![save_filled](https://github.com/user-attachments/assets/ff25a2e8-7c6e-4f34-b380-7295a4a1fa79)

**Comment by yceballost** [comment]
thanks for your contribution 🥰 we will include it for the next release https://github.com/Telefonica/mistica-design/milestone/65

**Comment by yceballost** [comment]
We changed the name from `save` to `floppy-disk` to make the name more objective

**Comment by iveneva1** [comment]
@yceballost , thank you a lot for the quick implementation. Our developers are asking me something, I hope you can help us. They are telling me, that they can see the icon in the design library, but they are telling me, that they can not use the icon, because it wasn't deployed in any web-releases yet. Could that be and do you know when it is going to be released?

**Comment by yceballost** [comment]
We usually wait for more new icons before to generate a new PR in code repository to avoid too much reviews for each new icon include but, no problem, I will create a PR in web repo to include it in code side :)
https://github.com/Telefonica/mistica-web/pull/1304
