### ISSUE TITLE
Icon prop on main navigation bar tabs not working

### ISSUE THREAD

**Issue by andredelramo-hm** [Telefonica/mistica-design#1960]
## Description
![image](https://github.com/user-attachments/assets/7c2c94f5-1002-479f-bbea-5780aa1597da)

Inside the Main navegation bar component, inside Tabs, there is a prop that shows or hides the tab icons and it doesn't work.

## Tasks

- [ ] Add to mobile library
- [ ] Add to desktop library

**Comment by yceballost** [comment]
We detached Tabs instance in this [issue](https://github.com/Telefonica/mistica-design/issues/1836), so this ticket is not longer need it
