### ISSUE TITLE
Input fields/card - improve width relationship of 50-50% between date field and CVV

### ISSUE THREAD

**Issue by raulredondoj** [Telefonica/mistica-design#303]
### Context
If you think there is a component missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new component from Design to Development.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
(Write your answer here.)

---

## Is your component request related to a problem? Please describe.
- In Spanish, the Date field is not wide enough for the copy "Fecha de caducidad".
- at the same time the CVV field is too wide in relation to the data that can uphold (3-4 digits)

## Describe the solution you'd like and needs
Update the width relationship of 50-50% of these components to something like 60 (date)-40%(CVV) so:
- there is enough space for long copies in the date field label
- the CVV width reinforces the length of the content

## Describe alternatives you've considered
<img width="766" alt="Captura de pantalla 2020-11-23 a las 10 30 47" src="https://user-images.githubusercontent.com/68385124/99950782-60047980-2d7d-11eb-9dbf-87a3e6bdc689.png">

## Additional context
Also, we can reconsider the use of shorter copy text like validez, caducidad instead of fecha de caducidad. But I think we will have a more bulletproof credit card component with the suggested changes (more versatility in the label length for other languages) with no major impact on other issues or components.

**Comment by yceballost** [comment]
Merged in mistica-web
https://github.com/Telefonica/mistica-web/pull/223#event-4533333360

You can try in [Playroom](https://mistica-web.now.sh/playroom#?code=N4Igxg9gJgpiBcIA8AhCAPABABwIZSgEsA7AcwF5gBGANgF8A%2BAHWM0yQGUAXXMAa0wBnPGBiVajFmzZIAIhACuAIwA2MAGKEYKqJhW4Anoq7kmIACwAGAPQ1LZ5q2kyO2mGC5Tn04rgC2YmYAKoRcamZe3nq4StqmICFhMBFOURDYXIQQxIKUANqRUZjAmABuuCoKMPCYZn4ATmYANJhcMOhcNWYAso0gmHRNhVEl5ZXVtSANgs2t7Z2TvTP9g8PSALp0a9aOUUhB85raur4B8afJ-fqxKvEAcv6XmDuFSNbyympHOrvScoqqDRaHTRIwKExmOzWKwONacNweNZsC7xRLhEBI6I3VGhdGY9KZbK5YAFVJFUYVKpdKZ9FptDrU3pmAZDMkjMqUiZ1erLOnzRk85mrNkbLYil4i-aHYEnR7nR7M65xMwPALMiXON4fQHfKC-GQABQAFtkYHcFH5YvVdZgUWZsCbiE8lbczMbTerfm9uLw%2BI43mh0I4QE0QFwjTAAoIEHkQN0IKVCIIePUAPqEADyHBDIAAaoRShB01mcxmAEzF7Oh8upgDC%2BkEgkIYErIHWoYA7oQoOHo-A8gBmMuWJpUSxl8ybIA)
