### ISSUE TITLE
IBAN / Bank account field

### ISSUE THREAD

**Issue by raulredondoj** [Telefonica/mistica-design#352]
### Context
Para payments necesitamos un componente de formulario que responda a las necesidades del IBAN y cuenta bancaria de diferentes países.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
(Write your answer here.)
sí
---

## Is your component request related to a problem? Please describe.
No tenemos un componente que valide el formato exclusivo de IBAN/número de cuenta.

## Describe the solution you'd like and needs
Un componente que responda a la validación el formato de IBAN/Cuenta bancaria. En cuanto:
- Número de caracteres alfanuméricos: pues llevar el código del pais (ES) y números.
-  En otros países incluso llevan letras identificatorias. 
- Cada país tiene unos caracteres máximos.
- Autoespaciado 
- Sin error en línea, sólo al abandonar el campo

## Describe alternatives you've considered
Eventbrite están insistiendo mucho, la verdad

## Additional context
Ya tengo las specs. Zeplin: https://zpl.io/V4d0W54
<img width="737" alt="Captura de pantalla 2021-03-02 a las 15 16 10" src="https://user-images.githubusercontent.com/68385124/109661413-40de6a80-7b6a-11eb-9ff8-72dd37a11209.png">

**Comment by yceballost** [comment]
Can you attach more info about all the logic about this requirement? For example, how it is work in different countries? Do your team have all this technical information?

By other side, make sense the label include IBAN acronym?, for example `Bank account (IBAN)`

**Comment by raulredondoj** [comment]
hey, yayo. 
I think that each country should implement their local requirements. The field validation and specifications for IBAN varies from country to country. Digits allowed, characters, etc. so it's complicated to have a one fits all solution.

Okay with labelling Bank Account (IBAN)

**Comment by yceballost** [comment]
@atabel what do you think?

**Comment by atabel** [comment]
What do we expect from a mistica component implementing this?
I'd expect the mistica component to format the IBAN number and validate it.
If we want that from the mistica component, we need the definition of formatting and validation for the countries we intend to support.

If we don't want that from the mistica component? then what's the point of the component? why don't use a regular TextField?

**Comment by isaacperezestrada-telefonica** [comment]
Maybe the component could format known IBANs for now. I mean, European and Brazilian

**Comment by Marcosld** [comment]
As for the validation I'd propose a basic mod-97 operation as specified here: https://en.wikipedia.org/wiki/International_Bank_Account_Number#Validating_the_IBAN (we already have this implemented). We should set the max number of digits to the corresponding one depending on the country. Here is our bank account component for movistar ES: https://github.com/Telefonica/global-checkout/blob/master/packages/management-sdk/src/components/bank-account-field.js. Maybe it should also allow jest letters and digits to be typed.

**Comment by yceballost** [comment]
Have we agreement with the way to go to this component? What is the status? 

@raulredondoj @isaacperezestrada-telefonica @Marcosld

**Comment by raulredondoj** [comment]
@yceballost specs completed: https://zpl.io/V4d0W54 

Added format  and spacing definition per country: ES, UK, DE and BR

**Comment by yceballost** [comment]
Added tickets to development teams

https://jira.tid.es/browse/WEB-169
https://jira.tid.es/browse/ANDROID-9256
https://jira.tid.es/browse/IOS-6700
