### ISSUE TITLE
CTAs in Media Card

### ISSUE THREAD

**Issue by alvaromillans** [Telefonica/mistica-design#360]
## Describe the bug
It seems there are no CTA adapted to the size of the cards. What happens when the Card size is less than the "normal size?" 

## To Reproduce
![Screen Shot 2021-03-08 at 12 32 13](https://user-images.githubusercontent.com/2741457/110316100-87b8de00-800a-11eb-8634-cb0714b2041b.png)

## Expected behavior
Should we have some "button layouts" for minor sizes?

## Details (please complete the following information):

- [x] iOS Library 
- [ ] Android Library

**Comment by yceballost** [comment]
It is a good point, do you think that we really need two actions in these sizes? I think that the recommendations will be don't use two actions in small cards

If you are agree we can update documentation with this information

**Comment by yceballost** [comment]
ping @alvaromillans

**Comment by alvaromillans** [comment]
Totally agree. The problem here as always is... Will teams break the component to put 2 links If we don't allow this behaviour?
