### ISSUE TITLE
Tag Size

### ISSUE THREAD

**Issue by alvaromillans** [Telefonica/mistica-design#361]
## Describe the bug
When the card size gets reduced, the tag seems giant. It seems a CTA.

## To Reproduce

![Screen Shot 2021-03-08 at 12 40 57](https://user-images.githubusercontent.com/2741457/110316829-918f1100-800b-11eb-9b6f-e285c1ac2e28.png)

## Expected behavior
There are components that should be reduced if the card size is less than a specific size

## Details (please complete the following information):

- [x] iOS Library 
- [ ] Android Library

**Comment by yceballost** [comment]
this is the size of the tag component, you can create a new component request providing a possible solution, but I think that change component size depending on the context may is not the best way to evolve a component.

A ring to govern them all. I don't really want to have 3 different types of tags, again, PLEASE.

**Comment by yceballost** [comment]
Can I close this issue? @alvaromillans

**Comment by alvaromillans** [comment]
Yes, we can evolve this component with the work Vivo did. We can see it next week
