### ISSUE TITLE
Nuevo componente de Explore Evolution

### ISSUE THREAD

**Issue by saraenriquez** [Telefonica/mistica-design#372]
### Context
Para la nueva evolución de Explore Evolution vamos a necesitar nuevos componentes que den respuesta a las nuevas necesidades del producto Explora.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
(Write your answer here.)

---

## Is your component request related to a problem? Please describe.
En Explora hay demasidado contenido sin jerarquía y necesitamos un distribuidor para poder ordenar el contenido y que el usuario pueda acceder más fácil y rápidamente a el.

## Describe the solution you'd like and needs
Este componente nos aporta un primer nivel en el cual podremos acceder a diferentes páginas en Explora, además de permitirnos personalizar la Home con contenido más relevante.

## Describe alternatives you've considered
Hemos pensado hacer mejor los filtros, pero se necesitan más páginas y no quedarnos con una única página.

## Additional context
<img width="413" alt="Captura de pantalla 2021-03-16 a las 19 04 39" src="https://user-images.githubusercontent.com/68591149/111358364-8f235b80-868a-11eb-940b-34f363bdd761.png">

**Comment by yceballost** [comment]
lo vemos con appscore el martes 24 y te respondemos por aquí!

**Comment by yceballost** [comment]
Encontramos el problema que en TV se usa un componente visualmente igual que este pero con un comportamiento diferente. Si coretizamos esto, debería cambiar el comportamiento que tiene actualmente el de TV y que se adapte al mismo comportamiento de este componente o que se modifique la UX de TV
