### ISSUE TITLE
Nuevo componente Explore Evolution II

### ISSUE THREAD

**Issue by saraenriquez** [Telefonica/mistica-design#373]
### Context
Para la nueva evolución de Explore Evolution vamos a necesitar nuevos componentes que den respuesta a las nuevas necesidades del producto Explora.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
(Write your answer here.)

---

## Is your component request related to a problem? Please describe.
En Explora hay demasidado contenido sin jerarquía y necesitamos destacar el contenido relevante para el usuario de alguna forma. Que cada usuario vea cosas que le interesan de verdad.

## Describe the solution you'd like and needs
Este componente aporta al usuario contenido relevante y que fomente la compra gracias a la personalización.

## Describe alternatives you've considered
Hemos pensado hacer otro tipo de carrusel pero al final nos gustaría hacer un full width para que sea más inmersivo.

## Additional context
<img width="463" alt="Captura de pantalla 2021-03-16 a las 19 04 54" src="https://user-images.githubusercontent.com/68591149/111358873-2092cd80-868b-11eb-89f4-028e7362efd6.png">

**Comment by yceballost** [comment]
lo vemos con appscore el martes 24 y te respondemos por aquí!

**Comment by yceballost** [comment]
Estaría bien tener una definición global para un componente carrusel, este ahora mismo difiere del uso que tiene actualmente los carruseles de la start screen o de la start tab.
