### ISSUE TITLE
Change the checkbox to a rounded square format

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#380]
The radio (Controls/RadioOn) and the checkbox (Controls/CheckboxOn) button have the same format and I would like to suggest to change the format of the check. The ideia is change the check box to a rounded square, so the user can have a clear differentiation between both.

**Comment by yceballost** [comment]
will be review tomorrow at 4pm. We will reply after!

**Comment by yceballost** [comment]
![MicrosoftTeams-image (20)](https://user-images.githubusercontent.com/6722153/113718773-44c35680-96ed-11eb-94d6-a5786a146cf2.png)

**Comment by yceballost** [comment]
We already talk with develop and there is no problem to evolve this component 👍. From design team we think that it is a good change to improve the difference between radio and checkbox.

Thanks Henrique, we are going to work on it.

**Comment by yceballost** [comment]
We are going ahead with this component request, already done ticket for development.

https://jira.tid.es/browse/WEB-159
https://jira.tid.es/browse/IOS-6669

When they are date release we will do the release in design libraries.

Specs are already updated with this change
https://zpl.io/Vx7KGgm
https://zpl.io/V4LPkDM
https://zpl.io/VQkoLmn

thanks guys!

**Comment by henriquebarrosr** [comment]
thanks, guys!

**Comment by ghost** [comment]
thanks, guys! 😃
