### ISSUE TITLE
Info Button Layout broken in Desktop

### ISSUE THREAD

**Issue by alvaromillans** [Telefonica/mistica-design#381]
## Describe the bug
The Button Layout with the price in Desktop library is broken. The top divider breaks the component. 

![Screen Shot 2021-04-06 at 11 14 40](https://user-images.githubusercontent.com/2741457/113688129-4e3ac780-96c9-11eb-9080-59b174df946b.png)

## Expected behavior
Should this component have more width in order to cover the desktop width?

## Details (please complete the following information):

- [x] iOS 
- [x] Android
- [x] Desktop

Component name: `e.g. buttons/layouts/ButtonFixedFooterLayout/InfoButton

## Sketch file
If applicable, add a sketch URL to help us to solve the problem.

**Comment by yceballost** [comment]
Need we this component in desktop? I feel this component doesn't works as mobile version.

**Comment by yceballost** [comment]
anyway, I fixed the bug
