### ISSUE TITLE
Add the boxed state to the List custom view component.

### ISSUE THREAD

**Issue by mariamoli** [Telefonica/mistica-design#382]
### Context
If you think there is a component missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new component from Design to Development.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
(Write your answer here.)
Si

**When will I receive a reply?**
We usually review component request Tuesdays at 16:00 (CEST), after the meeting, we will reply in this component request.

---

## Is your component request related to a problem? Please describe.
En desarrollo podemos meter un link en un list boxed pero no dese sketch, tendríamos que romper dicho componente.

## Describe the solution you'd like and needs
Crear la opción de que el custom view sea boxed.

## Describe alternatives you've considered
En realidad es una cosa que ya esta así desarrollada

**Comment by yceballost** [comment]
it is just a bug :P, already exists in dev
