### ISSUE TITLE
Camilo not working with the Button component

### ISSUE THREAD

**Issue by mariamoli** [Telefonica/mistica-design#385]
## Describe the bug
Camilo is not working with the Button component

## To Reproduce
1. Go to 'Button component'
2. Click on 'Camilo and select Telefónica'
3. See error

## Expected behavior
Change the type to the Telefonica one

## Details (please complete the following information):

- [x] iOS 
- [x] Android
- [x] Desktop

Component name: `e.g. bars/navBar/regular`
Sketch version: 71

## Sketch file
https://telefonicacorp.sharepoint.com/:u:/s/Colabora_TCX/EfZetrjbkapNjueN-9Y4WkwBIhnPTp2RoMzCnj-rJDNwVg?e=gT9iBh

**Comment by yceballost** [comment]
solved doing `File > Sync library components`
