### ISSUE TITLE
Section Title with different size in Safari browser

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#416]
## Describe the bug
The Section Title component, when opened in the Safari browser, appears slightly smaller than the default set.

## To Reproduce
1. Go to Safari browser
1. Go to 'https://brandfactory.telefonica.com/d/iSp7b1DkYygv'
2. Click on 'Get Started'
3. Click on 'Components
4. Click on 'Section Title'
5. See error

## Expected behavior
Match the Section Title font settings in Chrome and Safari.

## Details (please complete the following information):

- [x] iOS 
- [x] Android
- [x] Desktop

Component name: Text Style Section Title
Sketch version: 72.4

## Sketch file
Added a Sketch file demonstrating comparison.
[Novum_SectioTitle.zip](https://github.com/Telefonica/mistica-design/files/6688987/Novum_SectioTitle.zip)
![image](https://user-images.githubusercontent.com/6722153/122938870-68ed1600-d373-11eb-8c97-590b539e3d8e.png)

## Additional context
It’s recommended to play the same behavior in the Chrome browser to see the difference.

**Comment by yceballost** [comment]
Thanks for this report!!

I can't see size differences in my Chrome and Safari, can you check if in your Safari you have the Zoom to 100%? You can set to default doing `cmd + 0`

I can see differences between fonts, in Chrome use Roboto and Safari use San Francisco

**Comment by ghost** [comment]
Hi Yayo! How are you?

I tried to reset the zoom on both browsers, but the difference persists. On the Sketch Style’s libraries, the difference doesn’t exist, only when we open the Section Title on different browsers (a height difference of nearly 2px).

I added some more pages on the Sketch File with the comparison, to explain this with more details. 
**Sketch file:** [Novum - Section Title v02.zip](https://github.com/Telefonica/mistica-design/files/6696289/Novum.-.Section.Title.v02.zip)

Any doubt, please send me a message.

Thanks! ✌️

**Comment by yceballost** [comment]
Try to check the font size in both browsers, it is not the same as zoom configuration, although they look similar

In safari: https://support.apple.com/en-gb/HT207209
In chrome: chrome://settings/fonts (default is 16px)

https://user-images.githubusercontent.com/6722153/123073305-976ffd00-d416-11eb-9593-62f290361688.mp4

I'm almost sure that is something from your configuration instead of Mística bugs
