### ISSUE TITLE
Text overlap in List

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#430]
## Describe the bug
When I include a list symbol 2Line Full Width IOS and insert a new 2line text content is overlapping the navigation icon ">"

## To Reproduce
1. Go to '+ > Symbols > Mistica iOS > Lists > Navigation'
2. Click on 'FullWidth — 2L' to add a list item
3. Mark 'Choose icon size' to No Symbol
3. Mark 'Line 2 Navigation' to No Symbol
4. Fill 'Line 1 Navigation' with a two-lines extension text

## Expected behavior
The text field needs to break before the >, and do not overlap it.

## Details (please complete the following information):

- [x] iOS 
- [x] Android
- [x] Desktop

Component name: `List Navigation Full Width 2l
Sketch version: 76.1

## Sketch file
[componet-list-ios 1.sketch.zip](https://github.com/Telefonica/mistica-design/files/7196726/componet-list-ios.1.sketch.zip)

## Additional context
<img width="302" alt="Captura de Tela 2021-09-20 às 10 18 15" src="https://user-images.githubusercontent.com/79213135/134027550-61cddcc6-c0a0-4d9d-baf2-879c6af148ac.png">

**Comment by yceballost** [comment]
Thanks for reporting! You can solve it making `SHIFT + ENTER` to make a line break. But I released a new version of libraries trying to avoid this kind of problems!

**Comment by ghost** [comment]
gracias, máquina!
