### ISSUE TITLE
Vivinho's icon on Success Screen Template

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#433]
### Context
We are doing a process of standardization of our success screen template and, together with the Product Team, we chose to return with the Vivinho’s icon that we had available before.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
Yes

**When will I receive a reply?**
We usually review component request Tuesdays at 16:00 (CEST), after the meeting, we will reply in this component request.

---

## Is your component request related to a problem? Please describe.
No, it’s just a rollback in a configuration that was already available for the others BU and has been disabled before.

## Describe the solution you'd like and needs
We chose to return with the Vivinho’s icon on our Success screen template, with the standard animation already used in the other BU’s.

## Describe alternatives you've considered
We consider returning with the solution that was already implemented earlier, as demonstrated on [this Sketch file.](https://github.com/Telefonica/mistica-design/files/7384554/novum_success-screens.zip)

## Additional context
No additional context needed for this case

**Comment by yceballost** [comment]
OH! That's a bug. Success Feedback Screen component in Vivo still has the Vivinho icon and the animation. I think that could be a bug from Sketch library.

In the last meeting, I understood that you want to include icon in Error Feddback Screen, not on Success. (Probably I missunderstood xD)

Can you confirm?

I'm gonna fix the bug on Success Feedback Screen anyway!

Thanks!

**Comment by yceballost** [comment]
I tested Sketch document attached, and it is working for me. 

1. Make sure that you have libraries updated
2. Reset component
3. Use camilo

**Comment by ghost** [comment]
Hi Yayo!
I opened this ticket by mistake, the adjustments will be on the feedback screens. You can you discard this one.
