### ISSUE TITLE
Icons on feedback screens (Informative and Error)

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#434]
### Context
We are doing a process of standardization of our feedback screens and, together with the Product Team, we decide to return with the icons on the Informative and Error feedback screens that we had available before.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
Yes

**When will I receive a reply?**
We usually review component request Tuesdays at 16:00 (CEST), after the meeting, we will reply in this component request.

---

## Is your component request related to a problem? Please describe.
No, it’s just a rollback in a configuration that was already available for the others BU and has been disabled before.

## Describe the solution you'd like and needs
We chose to return with the icons on our feedback screens (Informative and Error), with the standard animation already used in the other BU’s.

## Describe alternatives you've considered
We consider returning with the solution that was already implemented earlier, as demonstrated on [this attached Sketch file](https://github.com/Telefonica/mistica-design/files/7392742/Vivo_FeedbackScreens.zip).
![image](https://user-images.githubusercontent.com/6722153/138508317-af4463a4-f102-4ff6-b2b8-0dd6f45c0cf2.png)

## Additional context
No additional context needed for this case.

**Comment by yceballost** [comment]
Your wishes is my command ✨

https://jira.tid.es/browse/ANDROID-9989
https://jira.tid.es/browse/IOS-7087
https://jira.tid.es/browse/WEB-377

In sketch still showing icon for Vivo, right? It is just a task for development, right?

**Comment by ghost** [comment]
yeah! 👍 

it's just an adjustment on the dev's spot.

**Comment by yceballost** [comment]
closed and integrated in ios android and web
