### ISSUE TITLE
Video support for media card

### ISSUE THREAD

**Issue by pladaria** [Telefonica/mistica-design#438]
### Context
Explore needs a media card with video support

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
yes

**When will I receive a reply?**
We usually review component request Tuesdays at 16:00 (CEST), after the meeting, we will reply in this component request.

---

## Is your component request related to a problem? Please describe.
no

## Describe the solution you'd like and needs

For the explore bumpers we need to provide a video media in MediaCards and in banners (which right now they use Image).

The requirements from our side (explore) are:

We need an autoLoop property (after the video ends, it restarts).
By default, we need autoPlay, but you could create a prop for it.
By default, no audio (create a prop if you deem it necessary)
Allow the ability of providing an static image as fallback.
If possible, we could provide a list of sources with different resolutions, but we can also handle it outside the component.
It would be nice if all these requirements are fulfulled by the Video component itself, so it can be more reusable.

Note: in our use-cases, clicking in the video should not pause it. Instead, usually our cards are inside a Touchable, which should make the entire card actionable. This behaviour should be maintained when replacing the images with a video url.

## Describe alternatives you've considered
No alternatives (besides creating a custom component from scratch)

## Additional context
Explore needs this ASAP. This is blocking for them

**Comment by kydorn** [comment]
To clarify, we need this to allow the use of "bumpers" in both banners and MediaCards, so a Video component would also be greatly appreciated (so other styles like border-radius and such behave the same as with the Image component).

**Comment by yceballost** [comment]
Specs for video component
https://www.figma.com/file/dvMqeg6s8tDh9Hyxu7IYDl/%F0%9F%94%B8-Subatomic-Components?node-id=0%3A2

**Comment by yceballost** [comment]
already developed
https://tinyurl.com/yay2q654
