### ISSUE TITLE
Evolve Highlighted card w/ tag + text

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#441]
### Context
If you think there is a component missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new component from Design to Development.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/new-components-1603450886)?**
Yes

**When will I receive a reply?**
We usually review component request Tuesdays at 16:00 (CEST), after the meeting, we will reply in this component request.

---

### Is your component request related to a problem? Please describe.
NT team need to use more information inside Highlighted card. Have the possibility to add a tag or extra text line.

### Describe the solution you'd like and needs
<img width="773" alt="MicrosoftTeams-image (14)" src="https://user-images.githubusercontent.com/6722153/150127731-d87e5a27-57d6-4928-8dac-56ee6fcd4546.png">
<img width="250" alt="MicrosoftTeams-image (13)" src="https://user-images.githubusercontent.com/6722153/150127746-49f426bc-7631-4cf5-ae06-09fc7b513e7b.png">

### Describe alternatives you've considered
[Some alternatives here ](https://ibit.ly/FVuY) but I don't really like because most of them are based in fragments

**Comment by yceballost** [comment]
@PatriRoman propone que la imagen de la card escale desde el centro en lugar de abajo

**Comment by lauraocana** [comment]
Se me ocurre que podríamos evolucionar la Media Card para que pueda tener la imagen a derecha o izquierda del contenido y ya tendríamos todas las posibilidades en un mismo componente o bien, añadir los mismos elementos que tiene la Media Card a la Highlighted Card para hacerla más flexible ¿cómo lo veis?

**Comment by yceballost** [comment]
> Se me ocurre que podríamos evolucionar la Media Card para que pueda tener la imagen a derecha o izquierda del contenido y ya tendríamos todas las posibilidades en un mismo componente o bien, añadir los mismos elementos que tiene la Media Card a la Highlighted Card para hacerla más flexible ¿cómo lo veis?

justo la idea de hacer que la media admita imagen a ambos lados era la idea que le planteamos a desarrollo y que a nosotros nos encaja más. De esta manera nos cargaríamos la highlighted posiblemente.

Habrá que pensar si a la media se le añadiría también la posibilidad de tener fondo de color

**Comment by aweell** [comment]
Otro problema conceptual que anticipo es...(ademas del inverse), si el único elemento requerido es la imagen para la media como encaja eso en el merge de las dos? Actualmente la highlighted puedes prescindir del media asset para tener una card funcional compacta. Igualando los elementos a la media y la data podrías tener un hermano del medio entre la snap y las dos mayores, que tiene un poco de cada casa...

**Comment by yceballost** [comment]
close because will be resolved with media card evolution
