### ISSUE TITLE
Dismiss in Cards

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#443]
### Context
If you think there is a component missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new component from Design to Development.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute/how-to-contribute-1)?**
Yes

**When will I receive a reply?**
We usually review component request Tuesdays at 16:00 (CEST), after the meeting, we will reply in this component request.

---

### Is your component request related to a problem? Please describe.
Add the possibility to add a dismiss action in a media & data card, like highlighted card.

### Describe the solution you'd like and needs
Same behavior like highlighted card should be the way to evolve these cards to have a feature parity

### Describe alternatives you've considered
no one more

### Additional context
This need is a request from O2

**Comment by AnaMontes11** [comment]
Ready to review:
 
 🪵 [Figma branch](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/tNAtEmIdc7KYY5VTBmKaMh/M%C3%ADstica-Mobile?node-id=0%3A661)

**Comment by yceballost** [comment]
https://github.com/Telefonica/mistica-web/pull/492
