### ISSUE TITLE
[Figma] Carrousel not adapting to hightlighted card height

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#490]
Reported: Montse Morales

### Describe the bug
When selecting highlighted card, the height of the carrousel doesn't adapt.

### To Reproduce
1. Go to carousel component
2. Replace component to highlighted card
3. See an error

### Expected behavior
Carousel have to be adapted to highlighted card

### Details (please complete the following information):

- [x] Mobile 
- [x] Desktop

Component name: `carousel`

**Comment by aweell** [comment]
Al tener el `placeholder` el height definido como `hug`, cualquier elemento que tenga una altura menor que el propio contenedor del `placeholder` seguirá manteniendo su tamaño.

**Ejemplo 1:**

El `placeholder` tiene 232px de altura
La `dataCard` tiene 264px por defecto

Al reemplazar por la `dataCard` el contenedor ajustará su altura a 264px y se mantendrá en `hug`

**Ejemplo 2:**

El `placeholder` tiene 232px de altura
La `highlightedCard` tiene 148px de altura por defecto

Al reemplazar por la `highlightedCard` el contenedor mantendrá su altura a 232px y cambiará a `fixed`

Para resolver este problema habría que determinar cual es la altura mínima de un elemento dentro de un carrousel (probablemente una snapCard con sólo un elemento) y que por defecto el `placeholder` tenga esa altura con el `height` a `hug`

**Comment by yceballost** [comment]
mmm qué curioso, no parece ser un comportamiento esperado del hug, no?

Si se soluciona reduciendo el tamaño del placeholder haría eso.

**Comment by aweell** [comment]
> mmm qué curioso, no parece ser un comportamiento esperado del hug, no?
> 
> Si se soluciona reduciendo el tamaño del placeholder haría eso.

Es rarísimo si, el `hug` cambia a `fixed` cuando cualquiera de los hijos está a `fill` en el mismo eje, en este caso probé con cambiar tanto la imagen de la card a fixed como el relleno del componente imagen (es el único elemento que está a fill en el eje y) y nada de nada. No se que se me puede estar escapando... le daré otra probada y sino el workaround funciona
