### ISSUE TITLE
Componentizar Specs

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#508]
Hacer que todas las specs usen componentes de la librería de Figma. Al ser specs importadas de Sketch se rompieron todos los enlaces.

Componentizar Specs lentamente:
- [x] Alert / Dialogs
- [x]  Badge
- [x]  Buttons
- [x] #615 
- [x]  Callouts
- [x] #521
- [x]  Controls
- [x]  Divider
- [x]  Empty States
- [x]  Feedbacks Screen
- [x] #560
- [x]  Headers
- [x]  Highlighted Card
- [x] #522
- [x] #524
- [x] Lists
- [x]  Media Card
- [x]  Data Card
- [x]  Popovers
- [x]  Section Title
- [x]  Snackbars / Croutons
- [x] #525
- [x]  Tabs
- [x]  Tags
- [x]  Texts
- [x]  Tooltips
- [x] #526

**Comment by AnaMontes11** [comment]
En las **specs de Callout** que se han revisado como parte del issue [#553 ](https://github.com/Telefonica/mistica-design/issues/553) Mistica Evolution hay un **Frame antiguo "[Banners · Tablet y Desktop Copy 2](https://www.figma.com/file/LzhzNPzE8nY9d7Yvo10d5d/branch/C4daEQAYfRna66yT7C57F5/Callouts-Component-Specs?node-id=0%3A352)"** y otros elementos que no se corresponde con estas specs.

**Comment by yceballost** [comment]
componentizadas las specs de stepper con el último update
