### ISSUE TITLE
Navigation bar Figma refactor or replacement

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#509]
Las navigation bar en Figma tienen mucho margen de mejora. Actualmente existen demasiadas variantes y con múltiples bugs.

1. No tenemos la Regular NavBar con el subtitle
3. No tenemos la Search Bar
4. No tenemos la Modal Bar

**Comment by aweell** [comment]
Mejor la llamaría: **"Navigation bar Figma: refactor o replacement"**

https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/bb6pIZc5YgmJWiLj5h4thn/M%C3%ADstica-Mobile?node-id=0%3A160

**Comment by yceballost** [comment]
> Mejor la llamaría: **"Navigation bar Figma: refactor o replacement"**
> 
> [figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/bb6pIZc5YgmJWiLj5h4thn/M%C3%ADstica-Mobile?node-id=0%3A160](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/bb6pIZc5YgmJWiLj5h4thn/M%C3%ADstica-Mobile?node-id=0%3A160)

por qué decidiste hacerla una nueva y no tocar la actual? crees que podría romper mucho?

**Comment by aweell** [comment]
> > Mejor la llamaría: **"Navigation bar Figma: refactor o replacement"**
> > [figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/bb6pIZc5YgmJWiLj5h4thn/M%C3%ADstica-Mobile?node-id=0%3A160](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/bb6pIZc5YgmJWiLj5h4thn/M%C3%ADstica-Mobile?node-id=0%3A160)
> 
> por qué decidiste hacerla una nueva y no tocar la actual? crees que podría romper mucho?

Sería bastante bueno a nivel de mantenimiento cambiar las props `Back` y `Left Icon` a boolean, esto supone eliminar 2/3 de las variantes.

Para el fix del punto 2:

> La Large Navigation Bar no está bien construida? Al poner el perfil se introduce el right icon automáticamente y no se puede meter el perfil sin este icono.

Está arreglado en [esta rama](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/GkpRHHYA0QxZpb3ur3RN0o/M%C3%ADstica-Mobile?node-id=0%3A160), valoraría incluir este cambio en esta release, ya que no rompemos nada y valorar en futuras hacer el breaking? WDYT?

**Comment by yceballost** [comment]
me parece bien

**Comment by aweell** [comment]
Perfe, saco esta y añado https://github.com/Telefonica/mistica-design/issues/634 a la 5.2.0
