### ISSUE TITLE
Incoherent Dialogs Specs

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#533]
### Describe the bug
En las Dialogs Specs hay medidas que no se corresponden.

### Expected behavior
Que el texto de la descripción de las specs se corresponda con lo representado en la imagen de ejemplo y en los componentes (librería y código).
<img width="733" alt="Captura de pantalla 2022-06-28 a las 9 42 07" src="https://user-images.githubusercontent.com/88187691/176146807-d8fec71d-8b99-4c08-b736-4c487d4d8f43.png">

### Details (please complete the following information):
Revisar y corregir de dónde viene el error:
- [x] Specs 
- [x] Librería
- [x] Creado Ticket a Apps Core para revisar este componente [APPS-7931](https://jira.tid.es/browse/APPS-7931(https://jira.tid.es/browse/WEB-615))]

Desde COL comentan que en las specs en mobile la altura mínima está a (320px) por lo que al eliminar el title queda un espacio raro:
![imgpsh_mobile_save](https://user-images.githubusercontent.com/88187691/178739612-5bdf8a98-e4fb-4e39-8502-60aef6ecaccc.jpg)

**DIALOGS MOBILE**
- [x] Añadir un ejemplo en las specs de elementos mínimos obligatorios en mobile.
- [x] Quitar el min-height en mobile.

### Figma file
[Dialogs Specs ](https://www.figma.com/file/xDudZU7n4T65sIP5QNHFQt/branch/Ii5UzCdUEAFNwW6StUdiZJ/Dialogs-Specs)

**Comment by AnaMontes11** [comment]
Comparto por aquí 2 aproach con la posible evolución de los Dialogs para que se ajusten más a nativo. También podríamos unificar el dismiss siguiendo lo planteado para las cards y aumentar ligeramente (8px) la destancia entre el (x) y el Title. Bajo mi punto de vista en los casos de mínimos sin title, el texto queda demasiado pegado.
Mi favorita sería la 2, aproximándose a nativo al eliminar el icon en mobile pero manteniendo el title en bold y unificando la description a regular. Qué os parecen? [Figma file](https://www.figma.com/file/xDudZU7n4T65sIP5QNHFQt/branch/Ii5UzCdUEAFNwW6StUdiZJ/Dialogs-Specs?node-id=857%3A1235)

<img width="1086" alt="Captura de Pantalla 2022-07-22 a las 10 38 29" src="https://user-images.githubusercontent.com/88187691/180399862-3f640c6d-0c1a-4a5f-b54d-c2ef72ef3f11.png">

**Comment by AnaMontes11** [comment]
Otra línea a valorar que comenta Álex es alinear el title con el dismiss:
<img width="220" alt="Captura de Pantalla 2022-07-22 a las 13 25 06" src="https://user-images.githubusercontent.com/88187691/180429943-098fc446-8b2b-425c-98e9-3920cd2ef763.png">

**Comment by aweell** [comment]
Un ejemplo del alineamiento del botón + añadir el estado hover a la acción de close:

https://codepen.io/AlexBueno/pen/rNdwwmj

**Comment by aweell** [comment]
Descartamos alinear el title con el dismiss. Volviendo a las specs, tal y como están planteadas ahora las cards y por mantener esa consistencia con éste componente es: 

* El close es un elemento colocado en posición absoluta en la esquina superior derecha del contenedor, no tiene márgenes con respecto a los límites del mismo.

Apectos que deberíamos tener en cuenta: 

El <button> que contiene este close debería medir un mínimo de 44x44px (https://www.w3.org/WAI/WCAG21/Understanding/target-size.html)

* En las cards actualmente el contenedor es de 48x48px y el contenido (la "x") se descentra ligeramente para cumplir con los 8px de margen que tiene con respecto a los límites del contenedor.
* En el dialog es un contenedor de 72x72px con un padding de 24px en desktop y de 56x56px, padding 16px en mobile.

Debería este button definirse siempre de la misma manera con respecto al contenedor? 

Ej: Siempre 48x48px, y siempre a 8px de los límites del contenedor. El resto de contenido debería respetar los paddings definidos para ese contenedor y no verse afectado por el espacio que ocupa el contenedor del close button. WDYT?

**Comment by yceballost** [comment]
> Debería este button definirse siempre de la misma manera con respecto al contenedor?

A priori tiene sentido que siempre siga una misma definición, tengo mis dudas en cuanto a que al final un dialog puede necesitar espaciados visualmente diferentes que una card, pero habrá que hacer pruebas y ver si seguir la misma definición que hay en cards funciona en dialogs.
