### ISSUE TITLE
→ Desktop landing modules: añadir variants a Mistica — Landing Modules

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#545]
**Meter las diferentes casuísticas  de los módulos dentro de Mistica — Landing Builder [BETA]**
- [x] Hero
- [x] Carousel
- [x] Breakers
- [x] Boxed breakers
- [x] Value proposition
- [x] Cards
- [x] Tariff & Pricing
- [x] Footer

**Comment by AnaMontes11** [comment]
Link al proyecto: [Mistica — Landing Modules [BETA]](https://www.figma.com/file/ybU9McfFGbSrtL87nLpFXS/%F0%9F%92%A0--Mistica-%E2%80%94-Landing-Modules-%5BBETA%5D?node-id=0%3A1)
