### ISSUE TITLE
Update specs with Mistica evolution changes

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#553]
Con la evolución de Mística y Movistar se actualizaron diversos componentes y no se han actualizado las specs. Debería haberse actualizado las specs antes de hacer estos cambios en código pero al paquetizarlo se decidió hacerlo de esta manera por agilidad.

Actualizar las specs de todos estos cambios ⬇️

---

## Small buttons

- [x] Paddings laterales de 8px → 12px ✅ Merged

## Feedbacks screens

- [x] Cambiar description de light → regular ✅ Merged

## Empty State
- [x] Cambiar description de light → regular

### mobile & desktop
Cambiar border radius de 4px → 8px
- [x] Cards ✅ Merged
- [x] Callouts ✅ Merged
- [x] Popovers ✅ Merged
- [x] Tooltips ✅ Merged
- [x] Listas Boxed ✅ Merged
- [x] Snackbar (?) (solo web) ✅ Merged
- [x] Empty state card
- [x] Forms ✅ Merged
- [x] Dialogs ✅ Merged
- [x] Dividers (borde redondeado) - EDIT: Este se cayo, hay que actualizar librerías para eliminar ese redondeado

### desktop
Cambiar border radius de 4px → 16px
- [x] Feedbacks ✅ Merged
- [x] Empty states

### ! solo desktop
Cambiar paddings en cards
- [x] Left & Right 16 → 24
- [x] Top & Bottom 24 → 32

En la media card se mantiene los 24px entre imagen y tag

Snap card
- [x] 16 → 24

## Tamaño icono empty state card
- [x] En desktop de 80 → 56
- [x] En mobile de 64 → 48

**Comment by AnaMontes11** [comment]
Por lo que estoy viendo, no estaría demás echarle una revisada general a las specs. Hay algunas cosas rotas o desactualizadas al margen de lo apuntado en esta issue. ¿Lo consideramos como tarea adicional?

**Comment by yceballost** [comment]
igual me llevaría este comentario a la issue #508 y desmarcaría aquellas en las que detectes cosas

**Comment by AnaMontes11** [comment]
> igual me llevaría este comentario a la issue #508 y desmarcaría aquellas en las que detectes cosas

Hecho!

**Comment by aweell** [comment]
Los dividers están definidos en la librería a 24px, que cambio serían necesario para que estén en la lista?

**Comment by yceballost** [comment]
> Los dividers están definidos en la librería a 24px, que cambio serían necesario para que estén en la lista?

añadir a las specs que su terminación es rounded

**Comment by yceballost** [comment]
Gente, hemos añadido un cambio de última hora por un problema de comunicación que hubo

## Feedbacks screens & Empty state
Cambiar descripción de text-preset-4/light → text-preset-3/regular
https://github.com/Telefonica/mistica-design/issues/565

**Comment by aweell** [comment]
> Gente, hemos añadido un cambio de última hora por un problema de comunicación que hubo
> 
> ## Feedbacks screens & Empty state
> Cambiar descripción de text-preset-4/light → text-preset-3/regular #565

Las dos ramas son mías, cambio yo las specs que están todavía sin mergear
