### ISSUE TITLE
New dark mode for Movistar & BackgroundBrandSecondary

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#578]
- [x] Create colors
- [x] Rename colors
- [x] OB COM presentation 
- [x] Design documentation
- [x] Duplicate Movistar Library
	- Tener una copia de la librería antes del cambio y llamarle Movistar Classic
- [x] Update brand libraries
- [x] Update UI Kit & Materials
	- [x] Actualizar templates a nueva marca
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-11317)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-7865)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-695) 

---

- [x] Cambiar el nombre del color `movistarProminentBlue` a `movistarBlueDark`
- [x] ~Cambiar las siguientes constantes de `movistarBlue` a `movistarBlueDark`~
	- ~backgroundBrand~
	- ~backgroundFeedbackBottom~
	- ~navigationBarBackground~
	- ~navigationBarDivider~
- [x] Cambiar la constante dividerInverse para que funcione sobre backgroundBrandSecondary
- [x] ~Crear backgroundBrandAlternative con `movistarBlue`~ (no es necesario aún)
- [x] ~Crear brandAlternative con `movistarBlueDark`~ (no es necesario aún)
- [x] ~Revisar tag active, sigue usando el `movistarBlue` o pasan a `movistarBlueDark`?~(usa movistarBlue)
- [x] ~Habilitar la posibilidad de que los componentes con inverse puedan ser "inverse-alternative"~ (no es necesario aún)
- [x] Dejaremos de usar `grey6` y en su lugar usaremos `movistarBlueDark`

---

### Discussed in https://github.com/Telefonica/mistica-design/discussions/562

<div type='discussions-op-text'>

<sup>Originally posted by **AnaMontes11** June 30, 2022</sup>
Con la llegada de la nueva marca Movistar se añade al azul de brand actual, otro azul brand más oscuro pero con gran relevancia siendo usado en textos y backgrounds por lo que tenemos que valorar cómo añadir este nuevo color a las constantes. 
Una solución podría ser crear un brandAlternative.

<img width="820" alt="Captura de pantalla 2022-06-28 a las 17 21 29" src="https://user-images.githubusercontent.com/88187691/176657353-c35a5502-6cad-4e24-880b-10cf79d9effd.png">

</div>

**Comment by yceballost** [comment]
related
https://github.com/Telefonica/mistica-design/issues/828

**Comment by AnaMontes11** [comment]
En la librería [BETA] Movistar (new) he creado la rama #578 dividerInverse --> movistarBlueDark dado que al revisar las constante listadas en las tareas de la issue, era la única  que faltaba por cambiar de movistarBlue a movistarBlueDark

**Comment by yceballost** [comment]
Creé este nuevo ticket para separar la tarea de aplicar los nuevos colores a dark mode de Movistar

https://github.com/Telefonica/mistica-design/issues/844

**Comment by AnaMontes11** [comment]
> Creé este nuevo ticket para separar la tarea de aplicar los nuevos colores a dark mode de Movistar
> 
> #844

Cerrada. Rama lista para mergear

**Comment by yceballost** [comment]
I reopened this issue to include the "last" approved definition
