### ISSUE TITLE
Revisar "neutralLow" en Solar

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#591]
Para fondos el newtralLow en Solar es muy fuerte.

**Tarea:**
Revisar cómo aplica en fondos y ajustar la constante a un tono más suave.

<img width="849" alt="Captura de Pantalla 2022-07-07 a las 14 41 39" src="https://user-images.githubusercontent.com/88187691/177786965-10745cfd-6d77-4602-85e0-a99d135632ee.png">

- [x] Cambiar en https://github.com/Telefonica/mistica-design/blob/production/tokens/solar-360.json
- [x] Android ✅
- [x] Cambiar en [zeus-web] [#273](https://github.com/Telefonica/zeus-web/pull/273)
- [x] Ticket a desarrollo
	- iOS [IOS-7527](https://jira.tid.es/browse/IOS-7527)
- [x] Actualizar Solar360 con Figma Tokens

**Comment by yceballost** [comment]
podemos cerrar esta ya?
