### ISSUE TITLE
Buttons documentation revamp

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#599]
Revisitar documentación de botones
- [x] Reducir documentación
- [x] Revisar bien algunos casos
- [x] #781 
- [x] #647
- [x] Corrección de traducción https://jira.tid.es/browse/LOC-975

**Comment by yceballost** [comment]
Igual estaría bien aprovechar
https://github.com/Telefonica/mistica-design/issues/781
https://github.com/Telefonica/mistica-design/issues/647

**Comment by aweell** [comment]
Intenté incluir los ejemplos de #798 en tipología/buttonLink pero aún no está disponible en desarrollo para mostrar en el ejemplo de playroom
