### ISSUE TITLE
Spinner documentation

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#600]
Añadir documentación de cuando usar un spinner (estaría bien diferenciar cuando usar un spinner o un loading bar)

https://github.com/Telefonica/mistica-design/discussions/499

**Comment by aweell** [comment]
Spinner doc update: https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/components/spinner
Loading bar doc update: https://brandfactory.telefonica.com/d/iSp7b1DkYygv/n-a#/components/loading-bar
