### ISSUE TITLE
Stepper Desktop wrong sizing

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#602]
El componente `stepper` en la librería de Desktop no se corresponde con el de las specs. Yo creo que es debido a que la librería de desktop se hizo más rápido y se hizo un copy paste de la de mobile.

**Comment by aweell** [comment]
Añado en esta issue los cambios relativos a las specs del stepper:

- [x] Text preset 8 --> Text presets 1 & 2 respectivamente para `Steps` y para `Label`/`Steps` en desktop

**Comment by aweell** [comment]
I've added the text `alignment` prop to the `_resources/steps` component in order to match the specs and the component implementation.

![Screenshot 2022-07-19 at 12 17 53](https://user-images.githubusercontent.com/44420072/179727969-b00d83f6-367d-4087-a62a-bfcc6e9a26a5.png)

**Comment by AnaMontes11** [comment]
En las specs de stepper, a parte del cambio de Álex, algunas cosas aparecen rotas. Añado por aquí que cuando publiquemos la librería, tendremos que:

- [x]  Actualizar las specs del stepper.
