### ISSUE TITLE
Update Breadcrumbs with underline state hover

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#615]
- [x] Review and update specs
- [x] Underline state hover & accessibility
- [x] Add Breadcrumbs in design documentation (post draft)
- [x] Ticket Review documentation UX Writing [Jira](https://jira.tid.es/browse/LOC-911)
- [x] Include breadcrumbs in UI Kits (only desktop)
- [x] Tickets desarrollo [Jira](https://jira.tid.es/browse/WEB-622)

**Comment by aweell** [comment]
https://github.com/Telefonica/mistica-design/discussions/623

Añado esto por aquí por si consideramos que tiene sentido valorarlo antes de hacer el update

**Comment by AnaMontes11** [comment]
En las specs actuales se indica que los breadcrumbs son exclusivos de web desktop, pero actualmente este componente lo tenemos en mobile también. Por coherencia actualizo specs.

**Comment by yceballost** [comment]
Please, pongamos un title más descriptivo en el title de la issue, tengamos en cuenta que ese titulo será lo que se refleje en el changelog por lo tanto debe ser más especifico.

**Comment by aweell** [comment]
Añadir en el ticket de desarrollo el cambio de estructura siguiendo estándar: https://www.w3.org/WAI/ARIA/apg/example-index/breadcrumb/index.html

![Screenshot 2022-08-04 at 16 21 49](https://user-images.githubusercontent.com/44420072/182871006-771dc50c-df2b-4a8b-a89e-c6c677807635.png)

**Comment by yceballost** [comment]
> Añadir en el ticket de desarrollo el cambio de estructura siguiendo estándar: [w3.org/WAI/ARIA/apg/example-index/breadcrumb/index.html](https://www.w3.org/WAI/ARIA/apg/example-index/breadcrumb/index.html)
> 
> ![Screenshot 2022-08-04 at 16 21 49](https://user-images.githubusercontent.com/44420072/182871006-771dc50c-df2b-4a8b-a89e-c6c677807635.png)

añade el ticket en el primer mensaje de la issue porfa!

**Comment by AnaMontes11** [comment]
> > Añadir en el ticket de desarrollo el cambio de estructura siguiendo estándar: [w3.org/WAI/ARIA/apg/example-index/breadcrumb/index.html](https://www.w3.org/WAI/ARIA/apg/example-index/breadcrumb/index.html)
> > ![Screenshot 2022-08-04 at 16 21 49](https://user-images.githubusercontent.com/44420072/182871006-771dc50c-df2b-4a8b-a89e-c6c677807635.png)
> 
> añade el ticket en el primer mensaje de la issue porfa!

Añadido arriba :)
