### ISSUE TITLE
→ Skeletons specs

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#616]
(comprobar que no es necesario añadir más definición)

**Comment by AnaMontes11** [comment]
Tras revisar las specs, añado la seccion Behavior para especificar que la experiencia de carga será progresiva. El contenido real irá reemplazando al skeleton tan pronto como esté disponible. Elimino la página Skeleton material para dejar con la info final el archivo. Añado review.

**Comment by AnaMontes11** [comment]
Tickets de los skeletons para Apps Core:
[Web](https://jira.tid.es/browse/WEB-614)
[iOS](https://jira.tid.es/browse/IOS-7577)
[Android](https://jira.tid.es/browse/ANDROID-10902)
