### ISSUE TITLE
Add Divider in RowList

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#622]
Actualmente desde desarrollo si metes una row sola sin que esté en una rowlist viene sin divider aunque en diseño no. Se detectan casos en los que a veces aparece el divider y en otros no. Se llega a un consenso interno en la weekly de que la rowList siempre va con divider.

**Comment by yceballost** [comment]
esto es porque el componente `<Row>` no trae divider, el que le pone el divider es el componente `<RowList>`
https://ibit.ly/4BM2

Creo que podríamos cerrar esta issue al no ser que alguien quiera cambiar este planteamiento

**Comment by AnaMontes11** [comment]
> esto es porque el componente `<Row>` no trae divider, el que le pone el divider es el componente `<RowList>` https://ibit.ly/4BM2
> 
> Creo que podríamos cerrar esta issue al no ser que alguien quiera cambiar este planteamiento

Si, lo sé. Para que tengas un poco más de contexto, esta fue una "discussion" en la weekly de diseño.
¿Cuándo una row va sola, se usa divider o no? (en diseño lo tenemos con divider pero en desarrollo no). 
Eso derivó en definir una lógica que los casos en los que se muestra una única row se debería usar la boxed row y de si aparecen varias, usar rowList pero se descartó xq desde CMS esto no se puede controlar. Finalmente se habló de reportar que las row que van solas también muestren divider e igualar con diseño.

**Comment by yceballost** [comment]
una `<Row>` siempre va dentro de una `<RowList>` asi que sí, siempre lleva divider.

https://ibit.ly/MAn0

No veo que haya que hacer nada
