### ISSUE TITLE
O2 - Add world-device icon

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#626]
- [x] Rolling plan 

| Weight | Example |
| :------ | :------ |
| light | ![Rolling plan _1Primary](https://user-images.githubusercontent.com/44420072/179189403-37d65a1a-7d85-43f3-be0c-7f901c596242.svg)|
| regular | ![Rolling plan _2Secondary](https://user-images.githubusercontent.com/44420072/179189575-f5026031-631c-4b24-aac3-f3ef1977d1e4.svg)|
| filled | ![Rolling plan _3Solid](https://user-images.githubusercontent.com/44420072/179189604-6b7c4716-ddff-4b91-8a76-ae6a3c97c7b3.svg)|

- [x] International minutes → renamed to `world-device`

| Weight | Example |
| :------ | :------ |
| light | ![International minutes _1Primary](https://user-images.githubusercontent.com/44420072/179189882-807ac673-34a0-4f30-b683-0c11cc3779a9.svg)|
| regular | ![International minutes _ 2Secondary](https://user-images.githubusercontent.com/44420072/179189922-2cc9bf89-82e0-43ac-9973-14e8efd8cf71.svg)|
| filled | ![International minutes _3Solid](https://user-images.githubusercontent.com/44420072/179189950-bd05e6ed-98c8-44eb-af07-24cdd5b2def3.svg)|

**Comment by yceballost** [comment]
El icono de rolling plan lo dejamos on hold
