### ISSUE TITLE
Update stepper specs

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#633]
En las specs de stepper, a parte del cambio de Álex, algunas cosas aparecen rotas. Añado por aquí que cuando publiquemos la librería, tendremos que:

- [x]  Actualizar las specs del stepper.

_Originally posted by @AnaMontes11 in https://github.com/Telefonica/mistica-design/issues/602#issuecomment-1189198897_

**Comment by yceballost** [comment]
esto ya esta hecho, no?
