### ISSUE TITLE
Evolve Dialogs to Alert

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#636]
**DIALOGS MOBILE**

 Se propone evolucionar los Dialogs para acercarlos a nativo.

 Revisar jerarquía de texto:
-  Subtitle regular 16 pt y el título de 20 pt a 18 pt (para acercarlo a los nativos)
-  Hacer el IconWrapper responsive y bajarlo a 40 o que desaparezca en mobile
-  Crear propuestas con este acercamiento a nativo.

Esta issue forma parte de la: #533 (revisar hilo)

🪵 Figma Dialogs Specs
[#636 Dialogs Update](https://www.figma.com/file/xDudZU7n4T65sIP5QNHFQt/branch/QA9tp2XMREMXjqWFULYsSq/Dialogs-Specs?node-id=958%3A1749)

**Comment by AnaMontes11** [comment]
Los actuales Dialogs evolucionan para acercarse a nativo y pasan a llamarse Alerts.

**Ajustes:**

1. Se elimina el close icon.
2. Desaparece el icon.
3. Title pasa  de text-preset-5 (bold) a text-preset-4 (regular)
4. Description pasa de text-preset-3 (light) a text-preset-3 (regular)
5. Cambio de nombre de Dialogs --> Alerts para dejar libre el componente dialog.

**Tareas:**

- [x] Actualizar specs
- [x] Cambiar en librería mobile
- [x] Cambiar en librería desktop
- [x] Crear ticket web → [WEB-615](https://jira.tid.es/browse/WEB-615)
- [x] Actualizar documentación BF
- [x] Actualizar UI kits (desktop y mobile)

**Next Step:** Crear el componente Dialog para que dentro se pueda meter lo que se quiera (con close icon, etc.)
#588 


![Captura de Pantalla 2022-08-04 a las 14 43 02](https://user-images.githubusercontent.com/88187691/182849845-167145ca-0fae-4373-a9fb-fa601641175d.png)

**Comment by yceballost** [comment]
Qué ocurre con los dialogs actuales que no contemplen una acción de escape? 

Un dialog actual que tenga un unico botón de comprar porque al existir la "x" en el dialog no necesitaban la acción de "cancelar"

**Comment by yceballost** [comment]
no parece que vaya a ser algo breaking
