### ISSUE TITLE
ReadOnly state in inputFields

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#698]
Definir un estado para el readOnly según lo hablado en la discussion

- [x] Update specs
- [x] Update design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-11340)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-7883)
- [x] Web ticket - https://github.com/Telefonica/mistica-web/pull/528

### Discussed in https://github.com/Telefonica/mistica-design/discussions/530

<div type='discussions-op-text'>

<sup>Originally posted by **AnaMontes11** June 27, 2022</sup>
Al eliminar las constantes `textDisabled` y `textLinkDisabled` para los estados deshabilitados y usar alfa al 50% se detecta que con esta solución los DISABLED TEXT INPUT WITH CONTENT no acaban de funcionar bien porque el input text sigue pareciendo editable (textPrimary --> grey6).

En caso de considerarlos como «readonly» y no como «disabled», tiene sentido que lleve el alfa si es de solo lectura aunque no sea editable? esto daría problemas de accesibilidad. Bajo mi punto de vista, al no entenderse como «disabled» el input text no debería llevar alfa.

Veo que aunque parecidas, son casos de uso diferentes.

![ae159bd9-5ec7-4c05-b74a-f564ee696d47](https://user-images.githubusercontent.com/88187691/175934645-284a5273-77aa-4cbb-8219-3f1dc578397b.jpg)

Original issue: [[ANDROID-10105 Disable states with alpha 50%]](url)</div>

**Comment by yceballost** [comment]
deberíamos añadir estos estados a Figma?
 @aweell @AnaMontes11 

edit: me contesto yo solo, sí.

Y lo mismo con los disabled, encontré una forma muy easy de añadir el estado disabled, ahora mi pregunta es.. 

podría existir un disabled + readOnly? por poder en código podrías pero no sé si es un estado bastante poco necesario de tener en Figma, y diría incluso de evitarlo
https://ibit.ly/ys3y

**Comment by aweell** [comment]
Disabled + readonly = disabled con value = ese value no se va a submitear. Esa combinación no la contemplaría.

**Comment by AnaMontes11** [comment]
Considerando que es tan corner case, no la incluiría.
