### ISSUE TITLE
Add overInverse and inverse props to components

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#729]
El planteamiento actual de los estados inverse difiere de la implementación.

El objetivo es que los componentes tengan las siguientes props:

* `overInverse`: el elemento está sobre un `backgroundBrand`
* `inverse`: el componente tiene una variante inverse que lo destaca del fondo (ej. `snapCard` o `highlightedCard`)

Con éstas dos propiedades se pretende resolver el problema que tienen algunos componentes actualmente, donde alguno de sus elementos nos se comporta como sería esperado.

- [x] Cambiar la prop `inverse` por `overInverse` en todos los componentes
- [x] En aquellos casos en los que haya una variante `colorful`, cambiar esta por `inverse`

### Componentes afectados

| Componente | Cambio |
| :-------- | :------ |
| Asset wrapper | Añadidas variantes inverse para los iconos |
| Boxed | Renombrado: colorful -> inverse / inverse -> Over inverse |
| Avatar | Renombrado: inverse -> Over inverse |
| Button | Renombrado: inverse -> Over inverse |
| ButtonGroup | Añadidas variantes Over inverse |
| ButtonFixedFooterLayout | Añadidas variantes Over inverse <sup>1</sup> |
| Breadcrumbs | Renombrado: inverse -> Over inverse |
| Callout | Renombrado: inverse -> Over inverse |
| Highlighted card | Añadidas variantes Over inverse + Renombrado: colorful -> inverse |
| Media card | Añadida variante Over inverse |
| Data card | Añadida variante Over inverse |
| Snap card | Renombrado: colorful -> inverse / inverse -> Over inverse |
| Checkbox + text | Añadidas variantes Over inverse |
| Divider | Renombrado: inverse -> Over inverse |
| Empty state card | Añadida variante Over inverse |
| Row | Añadidas variantes Over inverse |
| Boxed row | Añadidas variantes Inverse y Over inverse |
| Skeletons | Renombrado: inverse -> Over inverse |
| Spinner | Renombrado: inverse -> Over inverse |
| Tag | Renombrado: inverse -> Over inverse |
| Text link | Renombrado: inverse -> Over inverse |
| Title | Añadidas variantes Over inverse |

<sup>1</sup> El ButtonFixedFooterLayout permite un container bg pero no directamente un inverse, quizás ese no es el uso adecuado?

**Comment by yceballost** [comment]
can you detail which components have these changes?

**Comment by aweell** [comment]
Incluida tabla en la issue description con los cambios por componente
