### ISSUE TITLE
→ Inverse | Controls inverse variant

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#736]
- [x] Update specs
- [ ] Design documentation
- [x] [Add to mobile library](https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/branch/HRjIjMZr0wBbZZyiVohuYr/M%C3%ADstica-Mobile?m=auto&t=emiGOhm9p16Dkr7K-1)
- [x] [Add to desktop library](https://www.figma.com/design/DSWhPLyJzbliP1fBrLxDUR/branch/TMvB9XsnSp2E92BJHcvEnk/M%C3%ADstica-Desktop?m=auto&t=ROZqEHCUTG8WPa2Y-1)
- [ ] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-15310)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10643)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2084)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/494

<div type='discussions-op-text'>

<sup>Originally posted by **yceballost** June 24, 2022</sup>
Actualmente los controles no tienen una versión inverse para ser usados sobre fondos de marca.

![image](https://user-images.githubusercontent.com/6722153/175557101-0380d126-a9d5-418a-ae94-3d8342649d90.png)

https://ibit.ly/bRHI

Es cierto que actualmente no es algo que ningún equipo haya demandado, por lo que no creo que tenga que tener mucha prioridad, pero es algo que he visto pasar rozando cerca de Mística y me gustaría abrir el debate por si creéis que es algo que debería cubrir Mística y cómo.</div>

### Edit 31/10/23

- [ ] Revisar variante inverse del counter

**Comment by aweell** [comment]
La añado como tarea de la https://github.com/Telefonica/mistica-design/issues/729

**Comment by aweell** [comment]
Añado el progress a esta issue, que no está funcionado para ninguna marca salvo Blau en la actualidad.

**Comment by yceballost** [comment]
https://www.figma.com/file/1F6jqwc0XCvNO8LWxTnDea/Untitled?type=design&node-id=125%3A8521&t=FBceoU6UWPPfZ4jT-1

**Comment by AnaMontes11** [comment]
Para las row, el icon with action también necesitaría una versión inverse

**Comment by yceballost** [comment]
Discussion made by Vivo → https://github.com/Telefonica/mistica-design/discussions/1747
