### ISSUE TITLE
Change spinner size in buttons

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#754]
Cambiar el tamaño de los spinners en los botones a 16px, actualizar specs si tocase.

- [x] Update specs
- [x] Update BF
- [x] Update mobile library
- [x] Update desktop library

Implementation:

- [ ] #1265
- [x] [web PR → ](https://github.com/Telefonica/mistica-web/pull/530/files#diff-9ceb281782ccd5ad1b5592e97235932f3b4ce69481d179409f46da5a318a56f1)

**Comment by aweell** [comment]
He añadido a la documentación de botones una sección con el tamaño del spinner para que quede registrado.

**Comment by yceballost** [comment]
Está registrado en las specs tb?

**Comment by aweell** [comment]
Corrijo, está registrado en las specs, lo añado a la documentación de BF

**Comment by aweell** [comment]
Esta duplicada esta issue: https://github.com/Telefonica/mistica-design/issues/769

Traigo la info y la cierro
