### ISSUE TITLE
NavBar title reset when update — WORKAROUND HERE

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#758]
El equipo de O2 España tiene el problema que al actualizar las navbar se le resetean todos los titles.

Archivo para pruebas
https://www.figma.com/file/Mm2mLXzYLEvcskwrgOwNAJ/O2_app_Draft_In-progress?node-id=405%3A8720

**Comment by aweell** [comment]
Este bug puede resolverse re-enlazando todas las instancias del componente a la librería:

1. Usa un plugin como [select layers](https://www.figma.com/community/plugin/799648692768237063/Select-Layers)
2. Selecciona en tu documento todas las capas llamadas: `iOS/NavBar + StatusBar` (En el caso de que la navbar esté incluida de manera independiente puede hacerse de la misma manera llamando al componente `iOS/NavBar`.

![Screenshot 2022-09-13 at 14 13 18](https://user-images.githubusercontent.com/44420072/189897996-b93afae9-94ac-4c3c-84ef-e92438d298f9.png)

3. Una vez seleccionadas las capas, re-selecciona el componente desde la lista disponible para hacer swap de la instancia.

![Screenshot 2022-09-13 at 14 12 22](https://user-images.githubusercontent.com/44420072/189897794-3265b61f-ec7d-496e-b307-a434745d2199.png)

4. El texto debería ahora mantenerse al realizar la actualización del componente
