### ISSUE TITLE
Change button spinner sizes

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#769]
Cambiar los iconos de los botones para que exista más consistencia visual entre spinners e iconos.

Icon default = 24
Spinner default = 20
Icon small = 20
Spinner small = 16

- [ ] ios ticket
- [ ] android ticket
- [x] [web PR → ](https://github.com/Telefonica/mistica-web/pull/530/files#diff-9ceb281782ccd5ad1b5592e97235932f3b4ce69481d179409f46da5a318a56f1)

**Comment by aweell** [comment]
Duplicada. Cubierta en #754
