### ISSUE TITLE
Mistica component: Modal web

### ISSUE THREAD

**Issue by raulredondoj** [Telefonica/mistica-design#777]
### Describe the bug
El componente modal para web parece roto. 

- El título no está alineado arriba
- Hay un espacio tocho blanco (sospecho que para el asset que aparece oculto por defecto)
- Las acciones están fuera de marco y no se ven

### To Reproduce
Buscar componente en libreria > insertar

### Details (please complete the following information):
- Desktop
- Movistar

Component name: `modal`

### Figma file
[If applicable, add a Figma URL to help us to solve the problem.](https://www.figma.com/file/8yi6qL0c45rS1Pqxl4ozB8/Appointment-Booking_Moves?node-id=208%3A14991)

**Comment by yceballost** [comment]
No existe ningún componente llamado `modal` en Mística 🤔 estás seguro de que estás cogiendo componentes de la librería?

**Comment by raulredondoj** [comment]
y de dónde sale el modal view? quizá de un import de sketch en local components... 
edit >
el componente que debía estar usando es alert
