### ISSUE TITLE
Mistica Desktop > fields > text area corner radius no 8px

### ISSUE THREAD

**Issue by raulredondoj** [Telefonica/mistica-design#778]
### Describe the bug
en la librería de mistica desktop, el text area no tiene actualizado el nuevo corner radius de 8px

### To Reproduce
assets > buscar > textArea > insert

### Details (please complete the following information):

- Desktop

Component name: textArea

### Figma file
https://www.figma.com/file/8yi6qL0c45rS1Pqxl4ozB8/Appointment-Booking_Moves?node-id=0%3A2540

**Comment by aweell** [comment]
Muy buenas @raulredondoj!

El componente `textarea` no existe de manera independiente en la librería desktop de mística (Este caso puede ser una variante que se eliminara y quedara el residuo o "no idea"). Para usar este componente debes indicar la variante `textArea` dentro de `InputFields[D]`. 

El arreglo en este caso es bastante sencillo, con un plugin como Select Layers: 

1. Selecciona por nombre todas aquellas que se llamen `Input Fields/TextArea/Inactive`.
2. Haz un "swap instance" por el componente `InputFields[D]` y cambia a la variante `textArea`
3. El texto debería mantenerse, en el caso de mobile deseleccionaría esos casos y repetiría el proceso para reemplazarlo por el correcto.

**Comment by raulredondoj** [comment]
gracias, sí es un problema del import de sketch que me ha creado un librería o algo nueva local y claro en el selector no se ve una mierda
