### ISSUE TITLE
Mística desktop > input fields/Terms&Conditions text overlap

### ISSUE THREAD

**Issue by raulredondoj** [Telefonica/mistica-design#779]
### Describe the bug
los textos (normal y link) se solapan en componente para aceptar terminos y condiciones

### To Reproduce
assets > terms...>insert

### Expected behavior
que el texto empuje y se reorganice

### Details (please complete the following information):

- Desktop

Component name: inputFields/Terms&Conditions

### Figma file
https://www.figma.com/file/8yi6qL0c45rS1Pqxl4ozB8/Appointment-Booking_Moves?node-id=0%3A2540

**Comment by aweell** [comment]
El replacement para `inputFields/Terms&Conditions` se llama `Checkbox + Text [D]`. Los elementos han cambiado de nombre así que es muy probable que se pierda el contenido al hacer swap.
