### ISSUE TITLE
Carousel and CenteredCarousel Arrows positioning issues

### ISSUE THREAD

**Issue by wyunreal** [Telefonica/mistica-design#780]
Hello, I'll enumerate all the issues I found trying to use Carousel and CenteredCarousel in mobile, tablet and desktop screen sizes, when a mouse is present: 

## Carousel Arrows collides with next column in a multi column layout.

![CarouselInLargeDesktopArrowCollidesWithColumn](https://user-images.githubusercontent.com/7761987/191061227-8a1b8115-51d2-47dd-a921-8111d90402dd.png)

![CarouselSmallDesktopArrowCollidesWithColumn](https://user-images.githubusercontent.com/7761987/191061235-79e61749-9bc4-4cb0-bafd-ac1fe7757225.png)

![CenteredCarouselDesktopArrowOnNextColumn](https://user-images.githubusercontent.com/7761987/191061242-f3315572-35f6-4437-b5c8-80e43d38f688.png)

As seen on the picture, when the layout uses more than one column, the arrows are placed overlapping near columns:
- This happens on both sides of the carousel.
- This happens on tablet, small desktop and large desktop.

## In mobile, or in a small column in desktop layouts, the arrow is displayed on top of the next/previous slide indicator:

![CarouselWhenMouseInMobile1](https://user-images.githubusercontent.com/7761987/191061237-68b106e4-41ba-42e8-9f7e-c463c6d7154e.png)
![CarouselWhenMouseMobile2](https://user-images.githubusercontent.com/7761987/191061239-f573b4ba-115b-49b0-8b73-44abc5adf9df.png)

In this case, a solution could be just hide the next/previous slide chunks when the mouse is present and thus, when the arrows are displayed.
- Also the mediaqueries being used in the carousel are taking the whole screen width into account instead of the container.

**Comment by aweell** [comment]
Actualizar specs incluyendo comportamiento en función del ancho de columna
