### ISSUE TITLE
Tab bar icons change selecting iOsX tabbar

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#834]
### Describe the bug
Tab bar changes completly when selecting Xphone
<img width="659" alt="image" src="https://user-images.githubusercontent.com/95479574/193043042-e39cbfe7-3390-4601-9127-a5630b91998f.png">

### To Reproduce
3. See error

### Expected behavior
Tab bar icons should be the same when activating iPhone X tab bar

### Details (please complete the following information):

- Mobile 

Component name: `tab bar`

### Figma file
If applicable, add a Figma URL to help us to solve the problem.

**Comment by yceballost** [comment]
Can u link your figma file to check what happened in this component? 

I tried by my own side and the component is working properly 

you can try 3 things:
1. Try to relink the component from Mística Mobile
2. Reset this component
3. Add a new tabBar from Mística Mobile

**Comment by MontseTelefonica** [comment]
Ok, found the problem. We were using a non-mistica component. So many bastards around here......
https://www.figma.com/file/DsZBditXKLfAI9QeMJfv5Z/Hub-Novum?node-id=1405%3A74223

**Comment by yceballost** [comment]
😬

So, can we close this issue?

**Comment by MontseTelefonica** [comment]
All good!
