### ISSUE TITLE
O2UK color libraries dark mode > brand token improvement

### ISSUE THREAD

**Issue by raulredondoj** [Telefonica/mistica-design#838]
### Describe the bug
The colour  in dark mode #808CD2 is not accessible when used as background with text with a foreground #ffffff (or similar) color

### Expected behavior
AA compliance

### Details (please complete the following information):
O2

Component name: `e.g. bars/navBar/regular`
colour token "brand"

### Figma file
[If applicable, add a Figma URL to help us to solve the problem.](https://www.figma.com/file/Ik2FTRIoAjJLReHCnKTF9u/Live-person-support-chat-O2UK?node-id=216%3A2872)

**Comment by yceballost** [comment]
done in #1593
