### ISSUE TITLE
Error size in Web/Dialogue icon

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#839]
La property icon en el componente Web/Dialog muestra el icono a 40px pero en las specs lo tenemos definido a 64px al igual que se muestra en [implementación](https://acortar.link/RPgsqy).
Revisar el componente en la librería de Mobile y ajustar el tamaño a 64px.

<img width="360" alt="Captura de Pantalla 2022-10-04 a las 14 10 53" src="https://user-images.githubusercontent.com/88187691/193816575-da583cdc-2601-4f53-a95c-eadc6b01f426.png">

**Comment by yceballost** [comment]
La librería de Figma ya trae los últimos cambios, falta desarrollo por evolucionar los dialogs y ajustarlos a las specs.

Ya están con ello
https://github.com/Telefonica/mistica-web/pull/554

Habrá que revisar en esa PR que tenga los últimos cambios

Creo que esta issue se podría cerrar
