### ISSUE TITLE
Add Movistar Tokens icon

### ISSUE THREAD

**Issue by elenagomezg** [Telefonica/mistica-design#851]
### Context
If you think there is a icon missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new icon from Design to Development.

- [x] **Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute/how-to-contribute)?**  
- [x] **Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?**  

---

### Is your icon request related to a need? Please describe.
I need the icon of the new loyalty program called 'Tokens de Movistar'. It is already designed, we need to have it available in Mística Icons Library.

### Describe or attach a screenshot of the solution you'd like and needs
This is the entry point of the program:
<img width="360" alt="Store-Explora" src="https://user-images.githubusercontent.com/116157691/196653156-438d9335-c01b-42e4-bd36-9693b0a2e2cf.png">

### Describe icon alternatives you've considered
Doesn't apply.

### Additional context?
It is the icon of the program so it is posible that it can be used in other contexts, apart from the entry point.

### Attach your svg icon with 3 weights (light / regular / filled)

Light
![Token 0 Light](https://user-images.githubusercontent.com/116157691/196653832-a68474cb-6141-420b-b9e5-fde852fd6d31.svg)

Regular
![Token 1 Medium](https://user-images.githubusercontent.com/116157691/196653856-cbd77917-65a6-4862-b274-a9dbdb78a3b2.svg)

Filled
![Token 2 Masa Hover](https://user-images.githubusercontent.com/116157691/196653897-d2e3cfd3-682f-4612-907c-6a8e6f41bf75.svg)

**Comment by yceballost** [comment]
Ya está disponible en las librerías de Figma, pronto estará disponible en código, cuando salga la siguiente versión!

Gracias por aportar a Mística! ＾◡＾
