### ISSUE TITLE
Display Data Card component

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#864]
- [x] #865
- [x] #866
- [x] #867
- [x] #868
- [x] #869
- [x] → [Android ticket](https://jira.tid.es/browse/ANDROID-11316) 
- [x] → [iOS ticket](https://jira.tid.es/browse/IOS-7864)
- [x] → [Web ticket](https://jira.tid.es/browse/WEB-694)

**Comment by HectorSancho** [comment]
Specs acabadas: https://www.figma.com/file/tKdPOfcUALzVIh5oizFbm7/Cards-Specs?node-id=1868%3A3853
