### ISSUE TITLE
Fix inverse state in tags

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#877]
- [x] Update Tags Specs
- [x] #920
- [x]  [Android ticket](https://jira.tid.es/browse/ANDROID-11348)
- [x] [ iOS ticket](https://jira.tid.es/browse/IOS-7888)
- [x]  [Web ticket](https://jira.tid.es/browse/WEB-705)

Las tags sobre imágenes en dark mode se rompen.

Aprovecharía para cambiar quizás la definición actual de los estados inverse en light. @AnaMontes11 comentó en algún momento que aplicaría el mismo estado que el _no-inverse_ en el inverse y no cambiar a blanco puro en estado inverse.

**Comment by AnaMontes11** [comment]
Tras varias pruebas concluimos realizar los siguientes ajustes:

**Light Mode:**
- [x] Ajustar las _inverse_ para que **se muestren igual** que las _no-inverse_
 
Las no-inverse las mantenemos sin tocar.

**Dark Mode:**
- [x] **Las _inverse_ se mostrarán con background blanco sólido** igual que las _inverse_ actuales en light.

**Las no-inverse las mantenemos sin tocar.** _Una posible mejora a futuro (a falta de hacer las pruebas necesarias), es que el background en vez de llevar en successLow en white con 5% de opacidad lleve successHigh con 5% de opacidad. Y así con todas. De manera que quedan más integradas._

**Comment by AnaMontes11** [comment]
Update mobile library*
Update desktop library*
Update UI Kit & Materials*

_*Las tags en las librerías en Figma no las tocamos por el momento. A futuro podemos valorar añadir unas props específicas para dark mode._

**Comment by aweell** [comment]
Completed waiting for web to update documentation

**Comment by AnaMontes11** [comment]
Reabrimos esta issue debido a que en nativo no se pueden aplicar constantes light en dark.
Como solución se plantea crear nuevas constantes "inverse" para light y dark.
