### ISSUE TITLE
toggleButton component

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#880]
- [x] Specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/projects/WEB/issues/WEB-198?filter=allissues)

**Comment by yceballost** [comment]
Tendría sentido tener diferentes tipos de animaciones?

No es lo mismo dar un like ❤️ que podría usar una animación de un pequeño escalado que hacer un cambio de modo light/dark

https://user-images.githubusercontent.com/6722153/198359681-2f3ac20f-2f25-406c-b053-f92c43687fb0.mov

**Comment by aweell** [comment]
Me encaja esta idea planteando una serie de acciones prefefinidas para este toggle donde cada una se comporte de una manera (añado ideas sobre los dos ejemplos)

* Show/Hide del input password
* Play/Pause
* Closed/Open (para habilitar o deshabilitar edición de cambios)

En la main navigation bar ahora mismo el menú se está animando entre dos estados también, podría reemplazarse por este componente.


Que pasaría en el caso de que se necesitar algo custom? Se le pasarían los iconos/imágenes para los dos estados y no tendría animación?
