### ISSUE TITLE
iconButton bounding box definition

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#881]
Add to iconButton definition what is the min tap area for interaction.

- [ ] Update specs
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket (?)
- [ ] iOS ticket (?)
- [ ] Web ticket

**Comment by aweell** [comment]
I close this issue since it was already solved with https://github.com/Telefonica/mistica-design/issues/1601
