### ISSUE TITLE
5G, 4G, 3G, 2G icons in Blau

### ISSUE THREAD

**Issue by DiegodeMiguel** [Telefonica/mistica-design#916]
We need to create new icons for Blau & O2 mein brand to use into support (speed check coverage). It describe the type of network coverage.

I attach the svg that the OB sent to us. 

### Attach your svg icon with 3 weights (light / regular / filled)
Light

Regular

Filled
![5Gicon (2)](https://user-images.githubusercontent.com/106736588/203290395-e43d17e2-0284-4b48-aa27-08b2a5372921.svg)

**Comment by AnaMontes11** [comment]
Añadidos iconos 5G, 4G, 3G y 2G 3m Regular y Filled

**Comment by yceballost** [comment]
Published in Figma we will add it to mistica-web soon!
