### ISSUE TITLE
Primitives or Atoms

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#917]
- [x] Create a glossary page in brand factory with these definitions

### Discussed in https://github.com/Telefonica/mistica-design/discussions/912

<div type='discussions-op-text'>

<sup>Originally posted by **AnaMontes11** November 16, 2022</sup>
Actualmente en la documentación, hablamos de Átomos y en otros de Primitives (storybook por ejemplo). 
De cara a unificar y decidirnos uno, ¿qué término deberíamos usar? </div>

**Comment by aweell** [comment]
En qué categoría incluiríais está página? La que mas me encaja es al final de fundamentals, pero no se si deberíamos crear una específica para esto...

**Comment by yceballost** [comment]
y en get started? evitaría crear una categoría nueva para esto unicamente, la verdad

![image](https://user-images.githubusercontent.com/6722153/203616338-7344f9ad-b2e9-4d3f-b3ff-24cd0343e4c9.png)

quizás esta sección renombrarla ya que no tiene mucho dinamismo

**Comment by aweell** [comment]
Lo veo 100%, renombrarla como additional resources y meter glossary ahí

**Comment by yceballost** [comment]
me encaja, sí

**Comment by AnaMontes11** [comment]
Lo veo bien. También se me ocurre otra opción posible, (dado que a priori no tenemos mucha terminología que genere dudas) es meterlo dentro de FAQs: ¿What are Primitives and Atoms? / What do we mean by Primitives and Atoms?
