### ISSUE TITLE
Add asset presets to data card specs

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#923]
Add types of assets allowed in data cards specs like snap card

- Circle image
- Icon in circle

anything else?

**Comment by AnaMontes11** [comment]
Icon (24x24) without circle also added

**Comment by AnaMontes11** [comment]
Tiene relación con #940

**Comment by AnaMontes11** [comment]
> Add types of assets allowed in data cards specs like snap card
> 
> * Circle image
> * Icon in circle
> 
> anything else?

Added Square image like Snap Card: [Figma Specs](https://www.figma.com/file/tKdPOfcUALzVIh5oizFbm7/Cards-Specs?node-id=201%3A7100&t=MBOJd8CTEEMViChm-1)
