### ISSUE TITLE
Elementos mínimos mediaCard

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#934]
Actualmente en las specs de la media card existe una contradicción en los elementos mínimos. En el texto se indica que una media puede contener únicamente una imagen, sin embargo en el ejemplo que lo acompaña se muestra una card con una imagen + descripción.

En la documentación de BF también se incluye la imagen como elemento mínimo.

Referencia

![Screenshot 2022-11-29 at 12 44 45](https://user-images.githubusercontent.com/44420072/204520601-b2bd4615-faa6-4e16-bad7-9f9b1ed37c4b.png)

- [x] Actualizar las specs con los mínimos correctos

En el caso de que la descripción sea un elemento mínimo, añadir esta definición a las specs + documentación y abrir ticket

**Comment by yceballost** [comment]
esto se hizo, verdad? @aweell 

cierralo si eso
