### ISSUE TITLE
Mística Wrapper '22

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#953]
We can differenciate between Figma and other stuff like misc and code things

In Figma:
- Most used components in mobile
- Most used components in desktop
- Component more detached
- Most used icons
---
Other:
- New members in Mística community
- New X components in library (web mainly)
- New X versions in mistica (web, ios, android) along the year
- New teams using Mística (?)
	- Digital Growth
	- O2 España
	- Smart Wifi
	- Metaverso
---
Design documentation analytics
- Component documentation more visited
- Trend of users
- New users
- Avg. session duration
- Hour of the day with more activity in site
- Country visitors

**Comment by aweell** [comment]
5 Slides:

Cross: 

* Comparte el wrapped

**1 Portada**

**1.5 Transición a adopción**



**2 Adopción**

* Nuevos miembros de mística
* Equipos que han adoptado mística este año (6)
* Nuevas colaboraciones en mística design

------------------
* Diseñadores usando mística (

**2.5 Transición a uso**

**3 Uso**

* Componentes e iconos mas usados
* Que componente se detachea mas
* Datos BF

**4 Ahorro** ¿¿

* Datos de ahorro del componente mas usado ???

**4.5 Transición a futuro**


**5 A futuro + contacto**

* Incluir info sobre discussions
