### ISSUE TITLE
Play icon without circle

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#962]
### Context
If you think there is a icon missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new icon from Design to Development.

- [x] **Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute/how-to-contribute)?**  
- [x] **Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?**  

---

### Is your icon request related to a need? Please describe.
A clear and concise description of what the need is. Ex. I need an icon to symbolize rain [...]
Play icon for small player in display visual card for video content. The actual play icon in telefonica set has a circle. We need to rename the actual icon to `play-circle-regular` (or similar) and create a new one called `play-regular` without circle.

### Describe or attach a screenshot of the solution you'd like and needs
![image](https://user-images.githubusercontent.com/6722153/208681790-5b5cebb2-9a7b-49fe-9235-8bd7fcc6f762.png)

### Attach your svg icon with 3 weights (light / regular / filled)
  
Light

Regular

Filled

**Comment by aweell** [comment]
Should be consider as a breaking change? Since the current icons are renamed and old names are user for the new icons?
![Screenshot 2022-12-21 at 09 45 41](https://user-images.githubusercontent.com/44420072/208860176-1d57a3c3-8fc2-4b83-8007-b3e58f90bab1.png)
