### ISSUE TITLE
List title doesn't preserve content between variants

### ISSUE THREAD

**Issue by MontseTelefonica** [Telefonica/mistica-design#980]
### Describe the bug
Al cambiar un Row a centered, no conserva el campo title y lo resetea a default

### To Reproduce
1. Selecciona un Row[D] en Mistica Desktop library
2. Cambia el titulo
3. Ahora selecciona la opción "Centered"

### Expected behavior
Al seleccionar la opción centered, debería mantener el título

### Details (please complete the following information):
Mistica Desktop library

- Figma

Component name: `e.g. list/Rows`

https://user-images.githubusercontent.com/95479574/210523113-58ffda10-4068-4822-a55f-5a6017120ee4.mov

**Comment by aweell** [comment]
Buenas @MontseTelefonica,

Estamos en ello para resolverlo en la siguiente release :wink:
