### ISSUE TITLE
Button examples without PreviewTools and some errors

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#982]
There are some buttons documentation examples without `<PreviewTools />` component, that cause a dark mode examples when the user have dark mode in the system
![image](https://user-images.githubusercontent.com/6722153/211304764-45ab640a-86ca-4b98-9049-dafb4b72c08a.png)

also there are some broken examples in the same documentation
![image](https://user-images.githubusercontent.com/6722153/211304821-804bdcb2-91bb-418f-86a6-2d898afec3ac.png)

**Comment by aweell** [comment]
Fixed
