### ISSUE TITLE
wrong description name in movistar tokens

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#987]
Is it expected?
https://github.com/Telefonica/mistica-design/blob/b537be6d459e238ba8e34fc11fdbc42ac0b2fce3/tokens/movistar-classic.json#L158-L167

https://github.com/Telefonica/mistica-design/blob/b537be6d459e238ba8e34fc11fdbc42ac0b2fce3/tokens/movistar.json#L158-L166

**Comment by aweell** [comment]
Pues hay una parte intencionada y otra no:

La **no** intencionada:

```
 "value": "rgba({palette.white}, 0.1)", 
   "type": "color", 
   "description": "movistarBlue" 
```

Ese `movistarBlue` en la description debería ser un white

La **si** intencionada

Al pantear el `backgroundBrand` de la nueva skin movistar con el azul oscuro, la cantidad de blanco necesaria para resaltar el hover era menor que para el azul claro de movistar-classic, por eso el 0.1 de diferencia.

**Comment by yceballost** [comment]
mantenemos esto por ser un bug de la description
