### ISSUE TITLE
singleparent icon

### ISSUE THREAD

**Issue by ghost** [Telefonica/mistica-design#991]
### Context
If you think there is a icon missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new icon from Design to Development.

- [x] **Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute/how-to-contribute)?**  
- [x] **Have you read the [Contributing document for icons](https://github.com/Telefonica/mistica-icons/blob/production/CONTRIBUTING.md)?**  

---

### Is your icon request related to a need? Please describe.
We are developing a UX Design project for VIVO's Online Store from a business demand for the inclusion of thematic tags in store products. We checked all the icon options available in the Brand Factory and we did not find two different icons to represent Mother's Day and Father's Day in these tags. In addition, we are concerned about gender issues and diversity. So, our intention is expressing our respect choosing icons with no gender stereotype attached and focusing in the affection between parents and child.  

### Describe or attach a screenshot of the solution you'd like and needs
Currently, there is a family icon which could be used in the case of both fathers' and mothers' days. However, it is an internal requisite that we can not repeat the icons, and, furthermore, this particular icon has a Gestalt problem because it resembles an animal (chicken face, or a dog) when applied in small size. The solution we propose is to edit the current icon for a family, removing one of the parent figures that composes it.

### Describe icon alternatives you've considered
We thought of some alternatives to bring in more diversity and represent parenting without gender stereotypes (in line with the "Todos en la foto" 2022 campaign and other initiatives like "Vivo Diversidade" ones). We kept the heart image to express the affection and the figure of paternal/maternal parent with the child, since it will be used to represent the fathers' or mothers' day. Attached we send the studies we did in Figma (live). 

### Additional context?
Currently there is an icon which represents family in the icons library, however we evaluate that the drawing has a Gestalt problem and so we suggest redrawing with a variation. Our idea is to represent only the father or mother with the child, so that it encompasses the different forms of parenting, taking into consideration that many people may have been raised by only one parent, or even another relative. So the icon represent not only the family formed necessarily by a man together with a woman and a child.

### Attach your svg icon with 3 weights (light / regular / filled)
  
[icons_proposal_SVG.zip](https://github.com/Telefonica/mistica-design/files/10425935/icons_proposal_SVG.zip)

- [x] Light
- [x] Regular
- [x] Filled

**Comment by yceballost** [comment]
nice! 

do you think that having two icons very similar but just flipped is enough to represent both concepts? Why don't include only one to represent both concepts?

**Comment by ghost** [comment]
Our idea to flip the icon was to represent a father or a mother without gender distinction. We thought in two versions as one of the project's requirements is avoid repeating the same icon in our tags.  

We totally agree in creating just one version, as there is no problem using one icon flipped in other occasion. 

We are not sure what are the rules of icon application here, is it ok to use flipped icons?

**Comment by AnaMontes11** [comment]
Hello Henrique, yes it is a necessary icon. We will add it as a single-parent family concept. As there is no gender distinction, we believe that the use of the same version for both cases is clear enough, so we do not see the need to flip the icon.

**Comment by yceballost** [comment]
> We are not sure what are the rules of icon application here, is it ok to use flipped icons?

mmm nope, in development don't have the possibility to flip icons. If you need to use both icons we have two ways:
1. Include both icons to Mística and call each icon from library
2. Including one version in Mística and the flipped version will be exported manually from the product team (design + dev)

Can you illustrate with some visual examples?

I made this example to give more information to evaluate the request but maybe will be great to have an example more accurate to what you need or how did you use it
https://rebrand.ly/agdapx3

In my personal opinion the icon doesn't really provide critical information to users to have both variations

---

Trying to think about the need, another way to differentiate mono parental icons could be making a version for: father + child, mother + child but using man and woman iconic forms. 

Yes, I know, using man and woman silluettes maybe is not following the diversity rules but in the other hand this forms are a standard in the world in terms of icon language. dont kill me.

**Comment by ghost** [comment]
First of all, we would like to thank you for sending the visual examples :)

Analysing your suggestions, we agree with the second one: 
- Including one version in Mística and the flipped version will be exported manually from the product side

We suggest to name it as "parenting" or "mother/father".

Thank you!

**Comment by yceballost** [comment]
we will add it for the next release, thanks Henrique for the new icon and your understanding <3
https://github.com/Telefonica/mistica-design/milestone/19

**Comment by ghost** [comment]
thank you!

**Comment by AnaMontes11** [comment]
You can search for it as "singleparent-family" and it will appear together with the other "family icons".
